from __future__ import annotations

from enum import StrEnum


class LandedCostFields(StrEnum):
    doc_entry = 'DocEntry'
    landed_cost_number = 'LandedCostNumber'
    posting_date = 'PostingDate'
    due_date = 'DueDate'
    vendor_code = 'VendorCode'
    vendor_name = 'VendorName'
    broker = 'Broker'
    broker_name = 'BrokerName'
    closed_document = 'ClosedDocument'
    file_number = 'FileNumber'
    remarks = 'Remarks'
    reference = 'Reference'
    document_currency = 'DocumentCurrency'
    document_rate = 'DocumentRate'
    projected_customs = 'ProjectedCustoms'
    actual_customs = 'ActualCustoms'
    actual_customs_fc = 'ActualCustomsFC'
    tax1 = 'Tax1'
    tax2 = 'Tax2'
    before_tax = 'BeforeTax'
    total = 'Total'
    total_freight_charges = 'TotalFreightCharges'
    projected_customs_fc = 'ProjectedCustomsFC'
    tax1_fc = 'Tax1FC'
    tax2_fc = 'Tax2FC'
    before_tax_fc = 'BeforeTaxFC'
    total_fc = 'TotalFC'
    total_freight_charges_fc = 'TotalFreightChargesFC'
    series = 'Series'
    customs_affects_inventory = 'CustomsAffectsInventory'
    amount_to_balance = 'AmountToBalance'
    amount_to_balance_fc = 'AmountToBalanceFC'
    billof_lading_number = 'BillofLadingNumber'
    transport_type = 'TransportType'
    transaction_number = 'TransactionNumber'
    journal_remarks = 'JournalRemarks'
    attachment_entry = 'AttachmentEntry'
    landed_cost_item_lines = 'LandedCost_ItemLines'
    landed_cost_cost_lines = 'LandedCost_CostLines'
    business_partner = 'BusinessPartner'
    shipping_type = 'ShippingType'
    journal_entry = 'JournalEntry'
    purchase_delivery_notes = 'PurchaseDeliveryNotes'

class LandedCostsCodeFields(StrEnum):
    code = 'Code'
    name = 'Name'
    allocation_by = 'AllocationBy'
    landed_costs_allocation_account = 'LandedCostsAllocationAccount'
