from __future__ import annotations

from ...base import FieldEnum, ODataField


class LandedCostFields(FieldEnum):
    doc_entry = ODataField('DocEntry')
    landed_cost_number = ODataField('LandedCostNumber')
    posting_date = ODataField('PostingDate')
    due_date = ODataField('DueDate')
    vendor_code = ODataField('VendorCode')
    vendor_name = ODataField('VendorName')
    broker = ODataField('Broker')
    broker_name = ODataField('BrokerName')
    closed_document = ODataField('ClosedDocument')
    file_number = ODataField('FileNumber')
    remarks = ODataField('Remarks')
    reference = ODataField('Reference')
    document_currency = ODataField('DocumentCurrency')
    document_rate = ODataField('DocumentRate')
    projected_customs = ODataField('ProjectedCustoms')
    actual_customs = ODataField('ActualCustoms')
    actual_customs_fc = ODataField('ActualCustomsFC')
    tax1 = ODataField('Tax1')
    tax2 = ODataField('Tax2')
    before_tax = ODataField('BeforeTax')
    total = ODataField('Total')
    total_freight_charges = ODataField('TotalFreightCharges')
    projected_customs_fc = ODataField('ProjectedCustomsFC')
    tax1_fc = ODataField('Tax1FC')
    tax2_fc = ODataField('Tax2FC')
    before_tax_fc = ODataField('BeforeTaxFC')
    total_fc = ODataField('TotalFC')
    total_freight_charges_fc = ODataField('TotalFreightChargesFC')
    series = ODataField('Series')
    customs_affects_inventory = ODataField('CustomsAffectsInventory')
    amount_to_balance = ODataField('AmountToBalance')
    amount_to_balance_fc = ODataField('AmountToBalanceFC')
    billof_lading_number = ODataField('BillofLadingNumber')
    transport_type = ODataField('TransportType')
    transaction_number = ODataField('TransactionNumber')
    journal_remarks = ODataField('JournalRemarks')
    attachment_entry = ODataField('AttachmentEntry')
    landed_cost_item_lines = ODataField('LandedCost_ItemLines')
    landed_cost_cost_lines = ODataField('LandedCost_CostLines')
    business_partner = ODataField('BusinessPartner')
    shipping_type = ODataField('ShippingType')
    journal_entry = ODataField('JournalEntry')
    purchase_delivery_notes = ODataField('PurchaseDeliveryNotes')

class LandedCostsCodeFields(FieldEnum):
    code = ODataField('Code')
    name = ODataField('Name')
    allocation_by = ODataField('AllocationBy')
    landed_costs_allocation_account = ODataField('LandedCostsAllocationAccount')
