# AUTO-GENERATED — do not edit by hand. Run ./generate_models.sh
# Re-exports every entity model for a flat import namespace.
# Usage: from b1sl.b1sl import entities as en  →  en.Item

from b1sl.b1sl.models._generated.complex_types import *
from b1sl.b1sl.models._generated.entities.businesspartners import (
    Activity,
    ActivityLocation,
    ActivityRecipientList,
    ActivityStatus,
    ActivitySubject,
    ActivityType,
    BusinessPartner,
    BusinessPartnerGroup,
    BusinessPartnerProperty,
)
from b1sl.b1sl.models._generated.entities.finance import (
    AssetClass,
    ChartOfAccount,
    CostCenterType,
    Currency,
    JournalEntry,
    JournalEntryDocumentType,
    ProfitCenter,
    VatGroup,
    WithholdingTaxCode,
)
from b1sl.b1sl.models._generated.entities.general import (
    KPI,
    AccountCategory,
    AccountSegmentation,
    AccountSegmentationCategory,
    AccrualType,
    AdditionalExpense,
    AlertManagement,
    AlternateCatNum,
    ApprovalRequest,
    ApprovalStage,
    ApprovalTemplate,
    AssetDepreciationGroup,
    AssetDocument,
    AssetGroup,
    AssetRevaluation,
    Attachments2,
    AttributeGroup,
    B1Session,
    Bank,
    BankChargesAllocationCode,
    BankPage,
    BankStatement,
    BarCode,
    BatchNumberDetail,
    BillOfExchangeTransaction,
    BinLocation,
    BinLocationAttribute,
    BinLocationField,
    BOEDocumentType,
    BOEInstruction,
    BOEPortfolio,
    BPFiscalRegistryID,
    BPPriority,
    BPVatExemptions,
    Branch,
    BrazilBeverageIndexer,
    BrazilFuelIndexer,
    BrazilMultiIndexer,
    BrazilNumericIndexer,
    BrazilStringIndexer,
    Budget,
    BudgetDistribution,
    BudgetScenario,
    BusinessPlace,
    Campaign,
    CampaignResponseType,
    CashDiscount,
    CashFlowLineItem,
    CentralBankIndicator,
    CertificateSeries,
    ChecksforPayment,
    ChooseFromList,
    CIGCode,
    ClosingDateProcedure,
    Cockpit,
    ColumnPreferences,
    CommissionGroup,
    Contact,
    CostElement,
    Country,
    County,
    CreditCard,
    CreditCardPayment,
    CreditPaymentMethod,
    CUPCode,
    CustomerEquipmentCard,
    CustomsDeclaration,
    CustomsGroup,
    DeductibleTax,
    DeductionTaxGroup,
    DeductionTaxHierarchy,
    DeductionTaxSubGroup,
    DefaultElementsforCR,
    Department,
    Deposit,
    DepreciationArea,
    DepreciationType,
    DepreciationTypePool,
    DeterminationCriteria,
    Dimension,
    DistributionRule,
    DNFCodeSetup,
    Document,
    DunningLetter,
    DunningTerm,
    DynamicSystemString,
    EBooks,
    ElectronicFileFormat,
    EmailGroup,
    EmployeeIDType,
    EmployeeImage,
    EmployeeInfo,
    EmployeePosition,
    EmployeeRoleSetup,
    EmployeeStatus,
    EmployeeTransfer,
    EmploymentCategory,
    EnhancedDiscountGroup,
    EWBTransporter,
    ExceptionalEvent,
    ExpenseTypeData,
    ExportDetermination,
    ExtendedTranslation,
    FAAccountDetermination,
    FactoringIndicator,
    FinancialYear,
    FiscalPrinter,
    FormattedSearch,
    Forms1099,
    Gender,
    GLAccountAdvancedRule,
    GovPayCode,
    Holiday,
    HouseBankAccount,
    IdentificationCode,
    ImportDetermination,
    IndiaHsn,
    IndiaSacCode,
    Industry,
    IntegrationPackageConfigure,
    InternalReconciliation,
    IntrastatConfiguration,
    InventoryCycles,
    KnowledgeBaseSolution,
    LegalData,
    LengthMeasure,
    LocalEra,
    Manufacturer,
    MaterialGroup,
    Message,
    MobileAddOnSetting,
    MultiLanguageTranslation,
    NatureOfAssessee,
    NCMCodeSetup,
    NFModel,
    NFTaxCategory,
    NotaFiscalCFOP,
    NotaFiscalCST,
    NotaFiscalUsage,
    OccurenceCode,
    PackagesType,
    PartnersSetup,
    Payment,
    PaymentBlock,
    PaymentReasonCode,
    PaymentRunExport,
    PaymentTermsType,
    PickList,
    Picture,
    PM_ProjectDocumentData,
    PM_TimeSheetData,
    POSDailySummary,
    PostingTemplates,
    PredefinedText,
    PriceList,
    Project,
    PurchaseTaxInvoice,
    QueryAuthGroup,
    QueryCategory,
    Queue,
    RecurringPostings,
    Relationship,
    ReportType,
    RetornoCode,
    RouteStage,
    SalesForecast,
    SalesOpportunities,
    SalesOpportunityCompetitorSetup,
    SalesOpportunityInterestSetup,
    SalesOpportunityReasonSetup,
    SalesOpportunitySourceSetup,
    SalesPerson,
    SalesStage,
    SalesTaxAuthoritiesType,
    SalesTaxAuthority,
    SalesTaxCode,
    SalesTaxInvoice,
    Section,
    SerialNumberDetail,
    ServiceContract,
    ServiceGroup,
    ShippingType,
    ShortLinkMapping,
    SingleUserConnection,
    SpecialPrice,
    SQLQuery,
    SQLView,
    State,
    StockTaking,
    TargetGroup,
    TaxCodeDetermination,
    TaxCodeDeterminationTCD,
    TaxExemptReason,
    TaxInvoiceReport,
    TaxReplStateSubData,
    TaxReportFilter,
    TaxWebSite,
    Team,
    TerminationReason,
    Territory,
    TrackingNote,
    TransactionCode,
    TransportationDocumentData,
    TSRExceptionalEvent,
    UnitOfMeasurement,
    UnitOfMeasurementGroup,
    User,
    UserDefaultGroup,
    UserFieldMD,
    UserGroup,
    UserKeysMD,
    UserLanguage,
    UserObjectsMD,
    UserPermissionTree,
    UserQuery,
    UserTablesMD,
    ValueMappingCommunicationData,
    WebClientBookmarkTile,
    WebClientDashboard,
    WebClientFormSetting,
    WebClientLaunchpad,
    WebClientListviewFilter,
    WebClientNotification,
    WebClientPreference,
    WebClientRecentActivity,
    WebClientVariant,
    WebClientVariantGroup,
    WeightMeasure,
    WizardPaymentMethod,
    WTaxTypeCode,
    WTDCode,
)
from b1sl.b1sl.models._generated.entities.inventory import (
    CycleCountDetermination,
    InventoryCounting,
    InventoryCountingDraft,
    InventoryOpeningBalance,
    InventoryPosting,
    ItemGroups,
    ItemImage,
    ItemProperty,
    MaterialRevaluation,
    StockTransfer,
    Warehouse,
    WarehouseLocation,
    WarehouseSublevelCode,
)
from b1sl.b1sl.models._generated.entities.production import (
    ProductionOrder,
    ProductTree,
    Resource,
    ResourceCapacity,
    ResourceGroup,
    ResourceProperty,
)
from b1sl.b1sl.models._generated.entities.purchasing import LandedCost, LandedCostsCode
from b1sl.b1sl.models._generated.entities.sales import (
    BlanketAgreement,
    ContractTemplate,
    ServiceCall,
    ServiceCallOrigin,
    ServiceCallProblemSubType,
    ServiceCallProblemType,
    ServiceCallSolutionStatus,
    ServiceCallStatus,
    ServiceCallType,
)
from b1sl.b1sl.models._generated.enums import *
from b1sl.b1sl.models._overrides.inventory import Item

# --- Aliases for EntitySets (Singularized) ---
AssetCapitalization = AssetDocument  # From: AssetCapitalization
AssetCapitalizationCreditMemo = AssetDocument  # From: AssetCapitalizationCreditMemo
AssetManualDepreciation = AssetDocument  # From: AssetManualDepreciation
AssetRetirement = AssetDocument  # From: AssetRetirement
AssetTransfer = AssetDocument  # From: AssetTransfer
CorrectionInvoice = Document  # From: CorrectionInvoice
CorrectionInvoiceReversal = Document  # From: CorrectionInvoiceReversal
CorrectionPurchaseInvoice = Document  # From: CorrectionPurchaseInvoice
CorrectionPurchaseInvoiceReversal = Document  # From: CorrectionPurchaseInvoiceReversal
CreditNote = Document  # From: CreditNotes
DeliveryNote = Document  # From: DeliveryNotes
DownPayment = Document  # From: DownPayments
Draft = Document  # From: Drafts
EmployeeRolesSetup = EmployeeRoleSetup  # From: EmployeeRolesSetup
EmployeesInfo = EmployeeInfo  # From: EmployeesInfo
FormPreference = ColumnPreferences  # From: FormPreferences
GoodsReturnRequest = Document  # From: GoodsReturnRequest
IncomingPayment = Payment  # From: IncomingPayments
IntegrationPackagesConfigure = IntegrationPackageConfigure  # From: IntegrationPackagesConfigure
InventoryCycle = InventoryCycles  # From: InventoryCycles
InventoryGenEntry = Document  # From: InventoryGenEntries
InventoryGenExit = Document  # From: InventoryGenExits
InventoryTransferRequest = StockTransfer  # From: InventoryTransferRequests
Invoice = Document  # From: Invoices
ItemGroup = ItemGroups  # From: ItemGroups
NCMCodesSetup = NCMCodeSetup  # From: NCMCodesSetup
OccurrenceCode = OccurenceCode  # From: OccurrenceCodes
Order = Document  # From: Orders
PaymentDraft = Payment  # From: PaymentDrafts
ProjectManagementTimeSheet = PM_TimeSheetData  # From: ProjectManagementTimeSheet
ProjectManagement = PM_ProjectDocumentData  # From: ProjectManagements
PurchaseCreditNote = Document  # From: PurchaseCreditNotes
PurchaseDeliveryNote = Document  # From: PurchaseDeliveryNotes
PurchaseDownPayment = Document  # From: PurchaseDownPayments
PurchaseInvoice = Document  # From: PurchaseInvoices
PurchaseOrder = Document  # From: PurchaseOrders
PurchaseQuotation = Document  # From: PurchaseQuotations
PurchaseRequest = Document  # From: PurchaseRequests
PurchaseReturn = Document  # From: PurchaseReturns
Quotation = Document  # From: Quotations
ReportFilter = TaxReportFilter  # From: ReportFilter
ReturnRequest = Document  # From: ReturnRequest
Return = Document  # From: Returns
SalesOpportunity = SalesOpportunities  # From: SalesOpportunities
SalesOpportunityCompetitorsSetup = SalesOpportunityCompetitorSetup  # From: SalesOpportunityCompetitorsSetup
SalesOpportunityInterestsSetup = SalesOpportunityInterestSetup  # From: SalesOpportunityInterestsSetup
SalesOpportunityReasonsSetup = SalesOpportunityReasonSetup  # From: SalesOpportunityReasonsSetup
SalesOpportunitySourcesSetup = SalesOpportunitySourceSetup  # From: SalesOpportunitySourcesSetup
SelfCreditMemo = Document  # From: SelfCreditMemos
SelfInvoice = Document  # From: SelfInvoices
StockTransferDraft = StockTransfer  # From: StockTransferDrafts
TaxCodeDeterminationsTCD = TaxCodeDeterminationTCD  # From: TaxCodeDeterminationsTCD
TransportationDocument = TransportationDocumentData  # From: TransportationDocument
UserFieldsMD = UserFieldMD  # From: UserFieldsMD
ValueMappingCommunication = ValueMappingCommunicationData  # From: ValueMappingCommunication
VendorPayment = Payment  # From: VendorPayments
WitholdingTaxDefinition = WTDCode  # From: WitholdingTaxDefinition

__all__ = [
    "AccountCategorySourceEnum",
    "AccountSegmentationTypeEnum",
    "AcquisitionPeriodControlEnum",
    "AcquisitionProRataTypeEnum",
    "ActivityRecipientObjTypeEnum",
    "AlertManagementDocumentEnum",
    "AlertManagementFrequencyType",
    "AlertManagementPriorityEnum",
    "AlertManagementTypeEnum",
    "AmountCatTypeEnum",
    "ApprovalTemplateConditionTypeEnum",
    "ApprovalTemplateOperationTypeEnum",
    "ApprovalTemplatesDocumentTypeEnum",
    "AreaTypeEnum",
    "AssesseeTypeEnum",
    "AssetDocumentStatusEnum",
    "AssetDocumentTypeEnum",
    "AssetOriginalTypeEnum",
    "AssetStatusEnum",
    "AssetTransactionTypeEnum",
    "AssetTypeEnum",
    "AttributeGroupFieldTypeEnum",
    "AuthenticateUserResultsEnum",
    "AutoAllocOnReceiptMethodEnum",
    "AutomaticPostingEnum",
    "BADivationAlertLevelEnum",
    "BADocumentStatus",
    "BankStatementDocTypeEnum",
    "BankStatementRowSourceEnum",
    "BankStatementStatusEnum",
    "BaseDateSelectEnum",
    "BatchDetailServiceStatusEnum",
    "BinActionTypeEnum",
    "BinLocationFieldTypeEnum",
    "BinRestrictItemEnum",
    "BinRestrictTransactionEnum",
    "BinRestrictUoMEnum",
    "BinRestrictionBatchEnum",
    "BlanketAgreementBPTypeEnum",
    "BlanketAgreementDatePeriodsEnum",
    "BlanketAgreementDocTypeEnum",
    "BlanketAgreementMethodEnum",
    "BlanketAgreementStatusEnum",
    "BlanketAgreementTypeEnum",
    "BoAPARDocumentTypes",
    "BoAccountTypes",
    "BoActivities",
    "BoAdEpnsDistribMethods",
    "BoAdEpnsTaxTypes",
    "BoAddressType",
    "BoAeDistMthd",
    "BoAlertTypeforWHStockEnum",
    "BoAllocationByEnum",
    "BoApprovalRequestDecisionEnum",
    "BoApprovalRequestStatusEnum",
    "BoBOETypes",
    "BoBOTFromStatus",
    "BoBOTToStatus",
    "BoBarCodeStandardEnum",
    "BoBaseDateRateEnum",
    "BoBaselineDate",
    "BoBlockBudget",
    "BoBoeStatus",
    "BoBpAccountTypes",
    "BoBpsDocTypes",
    "BoBudgetAlert",
    "BoBusinessAreaEnum",
    "BoBusinessPartnerGroupTypes",
    "BoBusinessPartnerTypes",
    "BoCardCompanyTypes",
    "BoCardTypes",
    "BoChangeLogEnum",
    "BoCheckDepositTypeEnum",
    "BoClosingDateProcedureBaseDateEnum",
    "BoClosingDateProcedureDueMonthEnum",
    "BoCockpitTypeEnum",
    "BoConsumptionMethod",
    "BoContractTypes",
    "BoCorInvItemStatus",
    "BoCpCardAcct",
    "BoCurrencyCheck",
    "BoCurrencySources",
    "BoDataOwnershipManageMethodEnum",
    "BoDataSourceEnum",
    "BoDateTemplate",
    "BoDeductionTaxGroupCodeEnum",
    "BoDefaultBatchStatus",
    "BoDepositAccountTypeEnum",
    "BoDepositCheckEnum",
    "BoDepositPostingTypes",
    "BoDepositTypeEnum",
    "BoDocItemType",
    "BoDocLineType",
    "BoDocSpecialLineType",
    "BoDocSummaryTypes",
    "BoDocWhsAutoIssueMethod",
    "BoDocWhsUpdateTypes",
    "BoDocumentLinePickStatus",
    "BoDocumentSubType",
    "BoDocumentTypes",
    "BoDueDateEnum",
    "BoDurations",
    "BoEquipmentBPType",
    "BoExpenseOperationTypeEnum",
    "BoExtensionErrorActionEnum",
    "BoFatherCardTypes",
    "BoFieldTypes",
    "BoFldSubTypes",
    "BoForecastViewType",
    "BoFormattedSearchActionEnum",
    "BoFrequency",
    "BoFrequencyTypeEnum",
    "BoGLMethods",
    "BoGSTRegnTypeEnum",
    "BoGenderTypes",
    "BoGridTypeEnum",
    "BoHorizontalAlignmentEnum",
    "BoInterimDocTypes",
    "BoInventorySystem",
    "BoIssueMethod",
    "BoItemTreeTypes",
    "BoLineBreakEnum",
    "BoMRPComponentWarehouse",
    "BoMYFTypeEnum",
    "BoManageMethod",
    "BoMaterialTypes",
    "BoMeritalStatuses",
    "BoMoneyPrecisionTypes",
    "BoMsgPriorities",
    "BoMsgRcpTypes",
    "BoORCTPaymentTypeEnum",
    "BoObjectTypes",
    "BoOpenIncPayment",
    "BoOperationEnum",
    "BoOpexStatus",
    "BoOrientationEnum",
    "BoPayTermDueTypes",
    "BoPaymentMeansEnum",
    "BoPaymentPriorities",
    "BoPaymentTypeEnum",
    "BoPaymentsObjectType",
    "BoPermission",
    "BoPickStatus",
    "BoPictureSizeEnum",
    "BoPlanningSystem",
    "BoPriceListGroupNum",
    "BoPrintReceiptEnum",
    "BoProcurementMethod",
    "BoProductSources",
    "BoProductionOrderOriginEnum",
    "BoProductionOrderStatusEnum",
    "BoProductionOrderTypeEnum",
    "BoQueryTypeEnum",
    "BoRcptCredTypes",
    "BoRcptInvTypes",
    "BoRcptTypes",
    "BoRemindUnits",
    "BoReportLayoutItemTypeEnum",
    "BoResolutionUnits",
    "BoResponseUnit",
    "BoRoleInTeam",
    "BoRoundingMethod",
    "BoRoundingRule",
    "BoSalaryCostUnits",
    "BoSerialNumberStatus",
    "BoSeriesGroupEnum",
    "BoSeriesTypeEnum",
    "BoServicePaymentMethods",
    "BoServiceSupplyMethods",
    "BoServiceTypes",
    "BoSoClosedInTypes",
    "BoSoOsStatus",
    "BoSoStatus",
    "BoSortTypeEnum",
    "BoStatus",
    "BoStckTrnDir",
    "BoSubFrequencyTypeEnum",
    "BoSubPeriodTypeEnum",
    "BoSuppLangs",
    "BoSvcCallPriorities",
    "BoSvcContractStatus",
    "BoSvcEpxDocTypes",
    "BoSvcExpPartTypes",
    "BoTCDConditionEnum",
    "BoTCDDocumentTypeEnum",
    "BoTaxInvoiceTypes",
    "BoTaxOnInstallmentsTypeEnum",
    "BoTaxPostAccEnum",
    "BoTaxPostingAccountTypeEnum",
    "BoTaxRoundingRuleTypes",
    "BoTaxTypes",
    "BoTimeTemplate",
    "BoTransactionTypeEnum",
    "BoUDOObjType",
    "BoUPTOptions",
    "BoUTBTableType",
    "BoUniqueSerialNumber",
    "BoUpdateAllocationEnum",
    "BoUserGroup",
    "BoVatCategoryEnum",
    "BoVatStatus",
    "BoVerticalAlignmentEnum",
    "BoWeekEnum",
    "BoWeekNoRuleEnum",
    "BoWorkOrderStat",
    "BoYesNoEnum",
    "BoYesNoNoneEnum",
    "BrazilMultiIndexerTypes",
    "BrazilNumericIndexerTypes",
    "BrazilStringIndexerTypes",
    "CalculateInterestMethodEnum",
    "CalculationBaseEnum",
    "CallMessageStatusEnum",
    "CallMessageTypeEnum",
    "CampaignAssignToEnum",
    "CampaignBPStatusEnum",
    "CampaignItemTypeEnum",
    "CampaignStatusEnum",
    "CampaignTypeEnum",
    "CancelStatusEnum",
    "CardOrAccountEnum",
    "ClosingOptionEnum",
    "CommissionTradeTypeEnum",
    "ContractSequenceEnum",
    "CounterTypeEnum",
    "CountingDocumentStatusEnum",
    "CountingLineStatusEnum",
    "CountingTypeEnum",
    "CreateMethodEnum",
    "CreditOrDebitEnum",
    "CurrenciesDecimalsEnum",
    "CycleCountDeterminationCycleByEnum",
    "DataPrivacyProtectionEnum",
    "DataSensitiveStatusEnum",
    "DepreciationCalculationBaseEnum",
    "DepreciationMethodEnum",
    "DepreciationRoundingMethodEnum",
    "DirectDebitTypeEnum",
    "DiscountGroupBaseObjectEnum",
    "DiscountGroupDiscountTypeEnum",
    "DiscountGroupRelationsEnum",
    "DiscountGroupTypeEnum",
    "DisplayBatchQtyUoMByEnum",
    "DocumentAuthorizationStatusEnum",
    "DocumentDeliveryTypeEnum",
    "DocumentObjectTypeEnum",
    "DocumentPriceSourceEnum",
    "DocumentRemarksIncludeTypeEnum",
    "DomesticBankAccountValidationEnum",
    "DownPaymentTypeEnum",
    "DrawingMethodEnum",
    "DueDateTypesEnum",
    "DunningLetterTypeEnum",
    "ECDPostingTypeEnum",
    "EDocGenerationTypeEnum",
    "EDocStatusEnum",
    "EDocTypeEnum",
    "EWBSupplyTypeEnum",
    "EWBTransactionTypeEnum",
    "EffectivePriceEnum",
    "ElecCommStatusEnum",
    "ElectronicDocGenTypeEnum",
    "ElectronicDocProcessingTargetEnum",
    "ElectronicDocProtocolCodeEnum",
    "ElectronicDocProtocolCodeStrEnum",
    "ElectronicDocumentAuthorityProcessEnum",
    "ElectronicDocumentBlobContentTypeEnum",
    "ElectronicDocumentEntryCancellationStatusEnum",
    "ElectronicDocumentEntryLogTypeEnum",
    "ElectronicDocumentEntryPeriodTypeEnum",
    "ElectronicDocumentEntryStatusEnum",
    "ElectronicDocumentEntryTypeEnum",
    "EmployeeExemptionUnitEnum",
    "EmployeePaymentMethodEnum",
    "EmployeeTransferProcessingStatusEnum",
    "EmployeeTransferStatusEnum",
    "EndTypeEnum",
    "ExchangeRateSelectEnum",
    "ExemptionMaxAmountValidationTypeEnum",
    "ExternalCallStatusEnum",
    "FolioLetterEnum",
    "FormattedSearchByFieldEnum",
    "FreightTypeEnum",
    "FreightTypeForBolloEnum",
    "GSTTaxCategoryEnum",
    "GSTTransactionTypeEnum",
    "GTSResponseToExceedingEnum",
    "GeneratedAssetStatusEnum",
    "GetGLAccountByEnum",
    "GovPayCodePeriodicityEnum",
    "GovPayCodeSPEDCategoryEnum",
    "GroupingMethodEnum",
    "IdentificationCodeTypeEnum",
    "ImportFieldTypeEnum",
    "ImportOrExportTypeEnum",
    "InstallmentPaymentsPossiblityEnum",
    "IntrastatConfigurationEnum",
    "IntrastatConfigurationTriangDealEnum",
    "InvBaseDocTypeEnum",
    "InventoryAccountTypeEnum",
    "InventoryCycleTypeEnum",
    "InventoryOpeningBalancePriceSourceEnum",
    "InventoryPostingCopyOptionEnum",
    "InventoryPostingPriceSourceEnum",
    "IssuePrimarilyByEnum",
    "ItemClassEnum",
    "ItemTypeEnum",
    "ItemUoMTypeEnum",
    "KPITypeEnum",
    "LCCostTypeEnum",
    "LandedCostAllocationByEnum",
    "LandedCostBaseDocumentTypeEnum",
    "LandedCostCostCategoryEnum",
    "LandedCostDocStatusEnum",
    "LegalDataLineTypeEnum",
    "LicenseTypeEnum",
    "LicenseUpdateTypeEnum",
    "LineStatusTypeEnum",
    "LineTypeEnum",
    "LinkReferenceTypeEnum",
    "LinkedDocTypeEnum",
    "LogonMethodEnum",
    "MobileAddonSettingTypeEnum",
    "MobileAppReportChoiceEnum",
    "MultipleCounterRoleEnum",
    "OperationCode347Enum",
    "OperationCodeTypeEnum",
    "OpportunityTypeEnum",
    "PMCategorizeTypeEnum",
    "PMDocumentTypeEnum",
    "PMOperationTypeEnum",
    "PaymentInvoiceTypeEnum",
    "PaymentMeansTypeEnum",
    "PaymentRunExportRowTypeEnum",
    "PaymentsAuthorizationStatusEnum",
    "PeriodStatusEnum",
    "PostingMethodEnum",
    "PostingOfDepreciationEnum",
    "PriceModeDocumentEnum",
    "PriceModeEnum",
    "PriceProceedMethodEnum",
    "PrintOnEnum",
    "PrintStatusEnum",
    "ProductionItemType",
    "ProjectStatusTypeEnum",
    "ProjectTypeEnum",
    "RclRecurringExecutionHandlingEnum",
    "RclRecurringTransactionStatusEnum",
    "ReceivingBinLocationsMethodEnum",
    "ReceivingUpToMethodEnum",
    "RecipientTypeEnum",
    "ReconSelectDateTypeEnum",
    "ReconTypeEnum",
    "ReconciliationAccountTypeEnum",
    "RecurrenceDayOfWeekEnum",
    "RecurrencePatternEnum",
    "RecurrenceSequenceEnum",
    "ReferencedObjectTypeEnum",
    "RelatedDocumentTypeEnum",
    "RepeatOptionEnum",
    "Report349CodeListEnum",
    "ReportLayoutCategoryEnum",
    "ResidenceNumberTypeEnum",
    "ResourceAllocationEnum",
    "ResourceCapacityActionEnum",
    "ResourceCapacityBaseTypeEnum",
    "ResourceCapacityMemoSourceEnum",
    "ResourceCapacityOwningTypeEnum",
    "ResourceCapacityRevertedTypeEnum",
    "ResourceCapacitySourceTypeEnum",
    "ResourceCapacityTypeEnum",
    "ResourceDailyCapacityWeekdayEnum",
    "ResourceIssueMethodEnum",
    "ResourceTypeEnum",
    "RetirementMethodEnum",
    "RetirementPeriodControlEnum",
    "RetirementProRataTypeEnum",
    "ReturnTypeEnum",
    "RiskLevelTypeEnum",
    "RoundingContextEnum",
    "RoundingSysEnum",
    "RoundingTypeEnum",
    "SAFTProductTypeEnum",
    "SAFTTaxCodeEnum",
    "SAFTTransactionTypeEnum",
    "SEPASequenceTypeEnum",
    "SOIExcisableTypeEnum",
    "SPEDContabilAccountPurposeCode",
    "SPEDContabilQualificationCodeEnum",
    "ServiceTypeEnum",
    "Services",
    "ShaamGroupEnum",
    "SingleUserConnectionActionEnum",
    "SortOrderEnum",
    "SourceCurrencyEnum",
    "SpecialDepreciationCalculationMethodEnum",
    "SpecialDepreciationMaximumFlagEnum",
    "SpecialProductTypeEnum",
    "StageDepTypeEnum",
    "StockTransferAuthorizationStatusEnum",
    "StraightLineCalculationMethodEnum",
    "StraightLinePeriodControlDepreciationPeriodsEnum",
    "SubprojectStatusTypeEnum",
    "SubsequentAcquisitionPeriodControlEnum",
    "SubsequentAcquisitionProRataTypeEnum",
    "SupportUserLoginRecordLogReasonTypeEnum",
    "TCSAccumulationBaseEnum",
    "TargetGroupTypeEnum",
    "TargetGroupsDetailStatusEnum",
    "TaxCalcSysEnum",
    "TaxCodeDeterminationTCDByUsageTypeEnum",
    "TaxCodeDeterminationTCDDefaultWTTypeEnum",
    "TaxCodeDeterminationTCDTypeEnum",
    "TaxInvoiceReportLineTypeEnum",
    "TaxInvoiceReportNTSApprovedEnum",
    "TaxRateDeterminationEnum",
    "TaxReportFilterApArDocumentType",
    "TaxReportFilterDeclarationType",
    "TaxReportFilterDocumentType",
    "TaxReportFilterPeriod",
    "TaxReportFilterQuarterOrDates",
    "TaxReportFilterReportLayoutType",
    "TaxReportFilterType",
    "TaxTypeBlackListEnum",
    "TdsTypeEnum",
    "ThreatLevelEnum",
    "TimeSheetTypeEnum",
    "TransTypesEnum",
    "TransferSourcePeriodControlEnum",
    "TransferSourceProRataTypeEnum",
    "TransferTargetPeriodControlEnum",
    "TransferTargetProRataTypeEnum",
    "TranslationCategoryEnum",
    "TypeOfAdvancedRulesEnum",
    "TypeOfOperationEnum",
    "UDFLinkedSystemObjectTypesEnum",
    "UserAccessLogReasonIDTypeEnum",
    "UserActionTypeEnum",
    "UserGroupCategoryEnum",
    "UserMenuItemTypeEnum",
    "UserQueryTypeEnum",
    "VMCommunicationStatusEnum",
    "VMCommunicationTypeEnum",
    "VatGroupsTaxRegionEnum",
    "ViewStyleTypeEnum",
    "WTDDetailType",
    "WithholdingTaxCodeBaseTypeEnum",
    "WithholdingTaxCodeCategoryEnum",
    "WithholdingTypeEnum",
    "AFEFceAPCheckECM2Entry",
    "AFEFceAPCheckECM2EntryParams",
    "AFEFceAPGetLatestAFIPDate",
    "AFEFceARGetDateFromTo",
    "AFEFceARGetDocuments",
    "AFEFceActionGetByFceID",
    "AFEFceActionGetPaymentData",
    "AFEFceID",
    "AFERenumberFolioParams",
    "AFEUpdFceAPARGetDocuments",
    "AccountCategoryParams",
    "AccountSegmentationCategoryParams",
    "AccountSegmentationParams",
    "AccountSegmentationsCategory",
    "AccrualTypeParams",
    "ActivityInstanceParams",
    "ActivityInstancesListParams",
    "ActivityLocationParams",
    "ActivityMultipleRecipient",
    "ActivityParams",
    "ActivityRecipient",
    "ActivityRecipientListParams",
    "ActivityStatusParams",
    "ActivitySubjectParams",
    "ActivityTypeParams",
    "AdditionalExpenseParams",
    "AddressExtension",
    "AddressFormat",
    "AddressFormatParams",
    "AddressParams",
    "AddressReturnParams",
    "AdminInfo",
    "AdvancedGLAccountParams",
    "AdvancedGLAccountReturnParams",
    "AlertManagementDocument",
    "AlertManagementParams",
    "AlertManagementRecipient",
    "AlternateCatNumParams",
    "AlternativeItem",
    "ApprovalRequestDecision",
    "ApprovalRequestLine",
    "ApprovalRequestParams",
    "ApprovalStageApprover",
    "ApprovalStageParams",
    "ApprovalTemplateDocument",
    "ApprovalTemplateParams",
    "ApprovalTemplateQuery",
    "ApprovalTemplateStage",
    "ApprovalTemplateTerm",
    "ApprovalTemplateUser",
    "AssetClassLine",
    "AssetClassParams",
    "AssetDepreciationGroupParams",
    "AssetDocumentAreaJournal",
    "AssetDocumentLine",
    "AssetDocumentNewLoc",
    "AssetDocumentParams",
    "AssetGroupParams",
    "AssetRevaluationLine",
    "AssetRevaluationParams",
    "Attachments2Params",
    "Attachments2_Line",
    "AttributeGroupLine",
    "AttributeGroupParams",
    "BOEDocumentTypeParams",
    "BOEInstructionParams",
    "BOELine",
    "BOELineParams",
    "BOEPortfolioParams",
    "BPAccountReceivablePayble",
    "BPAddress",
    "BPBankAccount",
    "BPBlockSendingMarketingContent",
    "BPBranchAssignmentItem",
    "BPCode",
    "BPCurrencies",
    "BPFiscalRegistryIDParams",
    "BPFiscalTaxID",
    "BPIntrastatExtension",
    "BPPaymentDate",
    "BPPaymentMethod",
    "BPPriorityParams",
    "BPVatExemptionsLine",
    "BPVatExemptionsParams",
    "BPWithholdingTax",
    "BankChargesAllocationCodeParams",
    "BankPageParams",
    "BankParams",
    "BankStatementParams",
    "BankStatementRow",
    "BankStatementsFilter",
    "BarCodeParams",
    "BatchNumber",
    "BatchNumberDetailParams",
    "BillOfExchange",
    "BillOfExchangeTransBankPage",
    "BillOfExchangeTransDeposit",
    "BillOfExchangeTransactionLine",
    "BillOfExchangeTransactionParams",
    "BinLocationAttributeParams",
    "BinLocationFieldParams",
    "BinLocationParams",
    "BlanketAgreementParams",
    "BlanketAgreementsDocument",
    "BlanketAgreements_DetailsLine",
    "BlanketAgreements_ItemsLine",
    "Blob",
    "BlobParams",
    "BlobTableKeySegment",
    "Boxes1099Item",
    "BranchParams",
    "BrazilBeverageIndexerParams",
    "BrazilFuelIndexerParams",
    "BrazilMultiIndexerParams",
    "BrazilNumericIndexerParams",
    "BrazilStringIndexerParams",
    "BudgetCostAccountingLine",
    "BudgetDistributionParams",
    "BudgetLine",
    "BudgetParams",
    "BudgetScenarioParams",
    "BusinessPartnerGroupParams",
    "BusinessPartnerParams",
    "BusinessPartnerPropertyParams",
    "BusinessPlaceIENumber",
    "BusinessPlaceParams",
    "BusinessPlaceTributaryInfo",
    "CCDNumber",
    "CIGCodeParams",
    "CUPCodeParams",
    "CallArgument",
    "CallMessage",
    "CallMessageArgument",
    "CampaignBusinessPartner",
    "CampaignItem",
    "CampaignParams",
    "CampaignPartner",
    "CampaignResponseTypeParams",
    "CancelCheckRowParams",
    "CashDiscountParams",
    "CashFlowAssignment",
    "CashFlowLineItemParams",
    "CategoryGroup",
    "CentralBankIndicatorParams",
    "CertificateSeriesParams",
    "ChangeLogDifferenceParams",
    "ChangeLogParams",
    "ChartOfAccountParams",
    "CheckInParams",
    "CheckLine",
    "CheckLineParams",
    "ChecksforPaymentDocumentReference",
    "ChecksforPaymentLine",
    "ChecksforPaymentParams",
    "ChecksforPaymentPrintStatus",
    "ChooseFromListParams",
    "ChooseFromList_Line",
    "ClosingDateProcedureParams",
    "CockpitParams",
    "ColumnsPreferencesParams",
    "CommissionGroupParams",
    "CompanyInfo",
    "ContactEmployee",
    "ContactEmployeeBlockSendingMarketingContent",
    "ContactParams",
    "ContractTemplateParams",
    "CostCenterTypeParams",
    "CostElementParams",
    "CountryParams",
    "CountyParams",
    "CreditCardParams",
    "CreditCardPaymentParams",
    "CreditLine",
    "CreditLineParams",
    "CreditPaymentMethodParams",
    "CurrencyParams",
    "CurrencyRestriction",
    "CustomerEquipmentCardBusinessPartner",
    "CustomerEquipmentCardParams",
    "CustomsDeclarationParams",
    "CustomsGroupParams",
    "CycleCountDeterminationParams",
    "CycleCountDeterminationSetup",
    "DNFCodeSetupParams",
    "DashboardPackageImportParams",
    "DashboardPackageParams",
    "DataSensitiveStatus",
    "DecimalData",
    "DeductibleTaxParams",
    "DeductionTaxGroupParams",
    "DeductionTaxHierarchies_Line",
    "DeductionTaxHierarchyParams",
    "DeductionTaxSubGroupParams",
    "DefaultCreditCard",
    "DefaultDocument",
    "DefaultElectronicSeriesParams",
    "DefaultElementsforCRParams",
    "DefaultReportParams",
    "DepartmentParams",
    "DepositParams",
    "DepreciationAreaParams",
    "DepreciationLevel",
    "DepreciationTypeParams",
    "DepreciationTypePoolParams",
    "DeterminationCriteriaParams",
    "DimensionParams",
    "DiscountGroup",
    "DiscountGroupLine",
    "DiscountLine",
    "DistributionRuleLine",
    "DistributionRuleParams",
    "DocExpenseTaxJurisdiction",
    "DocFreightEBooksDetail",
    "DocsInWTGroups",
    "DocumentAdditionalExpense",
    "DocumentAdditionalIntrastatExpense",
    "DocumentChangeMenuName",
    "DocumentCloseParams",
    "DocumentDistributedExpense",
    "DocumentInstallment",
    "DocumentLine",
    "DocumentLineAdditionalExpense",
    "DocumentLinesBinAllocation",
    "DocumentPackage",
    "DocumentPackageItem",
    "DocumentParams",
    "DocumentReference",
    "DocumentSeriesParams",
    "DocumentSeriesUserParams",
    "DocumentSpecialLine",
    "DocumentTypeParams",
    "Document_ApprovalRequest",
    "DownPaymentToDraw",
    "DownPaymentToDrawDetails",
    "DppChangeParams",
    "DunningLetterParams",
    "DunningTermLine",
    "DunningTermParams",
    "DynamicSystemStringParams",
    "EBooksDetail",
    "EBooksLine",
    "EBooksParams",
    "EWBTransporterParams",
    "EWBTransporter_Line",
    "EWayBillDetails",
    "ElectronicFileFormatParams",
    "ElectronicProtocol",
    "ElectronicReportInfo",
    "ElectronicSeries",
    "ElectronicSeriesParams",
    "EmailGroupParams",
    "EmailRecipient",
    "EmergencyNumber",
    "EmployeeAbsenceInfo",
    "EmployeeBranchAssignmentItem",
    "EmployeeEducationInfo",
    "EmployeeFullNamesParams",
    "EmployeeIDTypeParams",
    "EmployeeInfoParams",
    "EmployeePositionParams",
    "EmployeePreviousEmpoymentInfo",
    "EmployeeReviewsInfo",
    "EmployeeRoleSetupParams",
    "EmployeeRolesInfo",
    "EmployeeSavingsPaymentInfo",
    "EmployeeStatusParams",
    "EmployeeTransferDetail",
    "EmployeeTransferParams",
    "EmploymentCategoryParams",
    "EnhancedDiscountGroupParams",
    "ExceptionalEventParams",
    "ExpenseTypeParams",
    "ExportDeterminationParams",
    "ExportDeterminationsParams",
    "ExportProcess",
    "ExtendedAdminInfo",
    "ExtendedTranslationParams",
    "ExtendedTranslation_ItemLine",
    "ExtendedTranslation_ResultLine",
    "ExternalCall",
    "ExternalCallParams",
    "ExternalReconciliation",
    "ExternalReconciliationFilterParams",
    "ExternalReconciliationParams",
    "FAAccountDeterminationParams",
    "FIFOLayer",
    "FactoringIndicatorParams",
    "FeatureStatus",
    "FieldID",
    "FinancePeriod",
    "FinancePeriodParams",
    "FinancialYearParams",
    "FiscalPrinterParams",
    "FixedAssetEndBalance",
    "FixedAssetValues",
    "FixedAssetValuesParams",
    "FormattedSearchParams",
    "Forms1099Params",
    "GLAccount",
    "GLAccountAdvancedRuleParams",
    "GTIParams",
    "GendersParams",
    "GeneratedAsset",
    "GetChangeLogParams",
    "GovPayCodeAuthority",
    "GovPayCodeParams",
    "HolidayDate",
    "HolidayParams",
    "HouseBankAccountParams",
    "IdentificationCodeParams",
    "ImportDeterminationParams",
    "ImportDeterminationsParams",
    "ImportProcess",
    "IndiaHsnParams",
    "IndiaSacCodeParams",
    "IndividualCounter",
    "IndustryParams",
    "IntegrationPackageParams",
    "InternalReconciliationBP",
    "InternalReconciliationOpenTrans",
    "InternalReconciliationOpenTransParams",
    "InternalReconciliationOpenTransRow",
    "InternalReconciliationParams",
    "InternalReconciliationRow",
    "IntrastatConfigurationParams",
    "InventoryCountingBatchNumber",
    "InventoryCountingDocumentReferences",
    "InventoryCountingDraftParams",
    "InventoryCountingLine",
    "InventoryCountingLineUoM",
    "InventoryCountingParams",
    "InventoryCountingSerialNumber",
    "InventoryCyclesParams",
    "InventoryOpeningBalanceBatchNumber",
    "InventoryOpeningBalanceCCDNumber",
    "InventoryOpeningBalanceLine",
    "InventoryOpeningBalanceParams",
    "InventoryOpeningBalanceSerialNumber",
    "InventoryPostingBatchNumber",
    "InventoryPostingCCDNumber",
    "InventoryPostingCopyOption",
    "InventoryPostingDocumentReferences",
    "InventoryPostingLine",
    "InventoryPostingLineUoM",
    "InventoryPostingParams",
    "InventoryPostingSerialNumber",
    "InvokeParams",
    "ItemAttributeGroups",
    "ItemBarCode",
    "ItemCycleCount",
    "ItemDepreciationParameter",
    "ItemDistributionRule",
    "ItemGroupParams",
    "ItemGroupsWarehouseInfo",
    "ItemIntrastatExtension",
    "ItemLocalizationInfo",
    "ItemParams",
    "ItemPeriodControl",
    "ItemPreferredVendor",
    "ItemPrice",
    "ItemPriceParams",
    "ItemPriceReturnParams",
    "ItemProject",
    "ItemPropertyParams",
    "ItemUnitOfMeasurement",
    "ItemUoMPackage",
    "ItemWarehouseInfo",
    "JournalEntryDocumentTypeParams",
    "JournalEntryLine",
    "JournalEntryParams",
    "KPIParams",
    "KPI_ItemLine",
    "KnowledgeBaseSolutionParams",
    "LandedCostParams",
    "LandedCost_CostLine",
    "LandedCost_ItemLine",
    "LandedCostsCodeParams",
    "Layer",
    "LegalDataDetail",
    "LegalDataParams",
    "LengthMeasureParams",
    "LineExpenseTaxJurisdiction",
    "LineFreightEBooksDetail",
    "LineTaxJurisdiction",
    "LocalEraParams",
    "MailElectronicDocumentParam",
    "MailParam",
    "ManufacturerParams",
    "MaterialGroupParams",
    "MaterialRevaluationDocumentReferences",
    "MaterialRevaluationFIFO",
    "MaterialRevaluationFIFOParams",
    "MaterialRevaluationLine",
    "MaterialRevaluationParams",
    "MaterialRevaluationSNBParam",
    "MaterialRevaluationSNBParams",
    "MessageDataColumn",
    "MessageDataLine",
    "MessageHeader",
    "MobileAddOnSettingParams",
    "MobileServerDateTime",
    "MultiLanguageTranslationParams",
    "MultiplePayment",
    "NCMCodeSetupParams",
    "NFModelParams",
    "NFTaxCategoryParams",
    "NatureOfAssesseeParams",
    "NotaFiscalCFOPParams",
    "NotaFiscalCSTParams",
    "NotaFiscalUsageParams",
    "OccurenceCodeParams",
    "OpenningBalanceAccount",
    "OriginalItem",
    "OriginalItemParams",
    "PMC_ActivityData",
    "PMC_AreaData",
    "PMC_PriorityData",
    "PMC_StageTypeData",
    "PMC_SubprojectTypeData",
    "PMC_TaskData",
    "PMS_ActivityData",
    "PMS_DocAttachement",
    "PMS_DocumentData",
    "PMS_OpenIssueData",
    "PMS_StageAttachement",
    "PMS_StageData",
    "PMS_SummaryData",
    "PMS_WorkOrderData",
    "PM_ActivityData",
    "PM_DocAttachement",
    "PM_DocumentData",
    "PM_OpenIssueData",
    "PM_ProjectDocumentParams",
    "PM_StageAttachement",
    "PM_StageData",
    "PM_SubprojectDocumentData",
    "PM_SubprojectDocumentParams",
    "PM_SubprojectParams",
    "PM_SummaryData",
    "PM_TimeSheetLineData",
    "PM_TimeSheetParams",
    "PM_WorkOrderData",
    "POSDailySummaryParams",
    "POSTotalizer",
    "PWPExtendedProperties",
    "PackagesTypeParams",
    "PartnersSetupParams",
    "PathAdmin",
    "PaymentAccount",
    "PaymentAmountParams",
    "PaymentBPCode",
    "PaymentBlockParams",
    "PaymentCheck",
    "PaymentCreditCard",
    "PaymentDocumentReferences",
    "PaymentInvoice",
    "PaymentInvoiceEntry",
    "PaymentParams",
    "PaymentReasonCodeParams",
    "PaymentRunExportParams",
    "PaymentRunExport_Line",
    "PaymentTermsTypeParams",
    "Payments_ApprovalRequest",
    "PeriodCategory",
    "PeriodCategoryParams",
    "PickListParams",
    "PickListsLine",
    "PostingTemplatesLine",
    "PostingTemplatesParams",
    "PredefinedTextParams",
    "PriceListParams",
    "ProductTreeLine",
    "ProductTreeParams",
    "ProductTreeStage",
    "ProductionOrderLine",
    "ProductionOrderParams",
    "ProductionOrdersDocumentReference",
    "ProductionOrdersSalesOrderLine",
    "ProductionOrdersStage",
    "ProfitCenterParams",
    "ProgressiveTax_Line",
    "ProjectParams",
    "PurchaseTaxInvoiceDocumentReference",
    "PurchaseTaxInvoiceLine",
    "PurchaseTaxInvoiceLinkedDownPayment",
    "PurchaseTaxInvoiceOperationCode",
    "PurchaseTaxInvoiceParams",
    "QRCodeData",
    "QueryAuthGroupParams",
    "QueryCategoryParams",
    "QueueMember",
    "QueueParams",
    "RclRecurringExecutionParams",
    "RclRecurringTransaction",
    "RclRecurringTransactionParams",
    "Recipient",
    "ReconciliationBankStatementLine",
    "ReconciliationJournalEntryLine",
    "RecordsetParams",
    "RecurringPostingsDocumentReference",
    "RecurringPostingsLine",
    "RecurringPostingsParams",
    "RelatedDocument",
    "RelationshipParams",
    "ReportInputParams",
    "ReportLayout",
    "ReportLayoutItem",
    "ReportLayoutParams",
    "ReportLayoutPrintParams",
    "ReportLayout_TranslationLine",
    "ReportParams",
    "ReportTypeParams",
    "ResourceCapacityParams",
    "ResourceCapacityWithFilterParams",
    "ResourceDailyCapacity",
    "ResourceEmployee",
    "ResourceFixedAsset",
    "ResourceGroupParams",
    "ResourceParams",
    "ResourcePropertyParams",
    "ResourceWarehouse",
    "RetornoCodeParams",
    "RoundedData",
    "RouteStageParams",
    "RoutingDateCalculationInput",
    "RoutingDateCalculationOutput",
    "SNBLines",
    "SQLQueryParams",
    "SQLQueryResult",
    "SQLViewParams",
    "SalesAppSetting",
    "SalesAppSettingParams",
    "SalesForecastLine",
    "SalesForecastParams",
    "SalesOpportunitiesCompetitionItem",
    "SalesOpportunitiesInterest",
    "SalesOpportunitiesLine",
    "SalesOpportunitiesParams",
    "SalesOpportunitiesPartner",
    "SalesOpportunitiesReason",
    "SalesOpportunityCompetitorSetupParams",
    "SalesOpportunityInterestSetupParams",
    "SalesOpportunityReasonSetupParams",
    "SalesOpportunitySourceSetupParams",
    "SalesPersonParams",
    "SalesStageParams",
    "SalesTaxAuthoritiesTypeParams",
    "SalesTaxAuthorityParams",
    "SalesTaxCodeParams",
    "SalesTaxCodes_Line",
    "SalesTaxInvoiceDocumentReference",
    "SalesTaxInvoiceLine",
    "SalesTaxInvoiceLinkedDownPayment",
    "SalesTaxInvoiceOperationCode",
    "SalesTaxInvoiceParams",
    "SectionParams",
    "SensitiveDataAccess",
    "SerialNumber",
    "SerialNumberDetailParams",
    "Series",
    "SeriesLine",
    "SeriesParams",
    "ServiceAppReport",
    "ServiceAppReportContent",
    "ServiceAppReportParams",
    "ServiceCallActivity",
    "ServiceCallBPAddressComponent",
    "ServiceCallInventoryExpense",
    "ServiceCallOriginParams",
    "ServiceCallParams",
    "ServiceCallProblemSubTypeParams",
    "ServiceCallProblemTypeParams",
    "ServiceCallScheduling",
    "ServiceCallSolution",
    "ServiceCallSolutionStatusParams",
    "ServiceCallStatusParams",
    "ServiceCallTypeParams",
    "ServiceContractParams",
    "ServiceContract_Line",
    "ServiceGroupParams",
    "ServiceTaxPostingParams",
    "ShippingTypeParams",
    "ShortLinkMappingParams",
    "ShowDifferenceParams",
    "SingleUserConnectionParams",
    "SpecialPriceDataArea",
    "SpecialPriceParams",
    "SpecialPriceQuantityArea",
    "StateParams",
    "StockTakingParams",
    "StockTransferLine",
    "StockTransferLinesBinAllocation",
    "StockTransferParams",
    "StockTransferTaxExtension",
    "StockTransfer_ApprovalRequest",
    "SupportUserLoginRecord",
    "TSRExceptionalEventParams",
    "TableInfo",
    "TargetGroupParams",
    "TargetGroupsDetail",
    "TaxCodeDeterminationParams",
    "TaxCodeDeterminationTCDByUsage",
    "TaxCodeDeterminationTCDDefaultWT",
    "TaxCodeDeterminationTCDKeyField",
    "TaxCodeDeterminationTCDKeyFieldValue",
    "TaxCodeDeterminationTCDKeyFieldValueDefaultWT",
    "TaxCodeDeterminationTCDKeyFieldValuePeriod",
    "TaxCodeDeterminationTCDKeyFieldValuePeriodByUsage",
    "TaxCodeDeterminationTCDParams",
    "TaxDefinition",
    "TaxExemptReasonParams",
    "TaxExtension",
    "TaxInvoiceReportLine",
    "TaxInvoiceReportParams",
    "TaxReplStateSubParams",
    "TaxReportAccount",
    "TaxReportBusinessPartner",
    "TaxReportDocument",
    "TaxReportFilterParams",
    "TaxReportGroup",
    "TaxReportSeries",
    "TaxWebSiteParams",
    "TeamCounter",
    "TeamMember",
    "TeamParams",
    "TechnicianSchedulings",
    "TechnicianSchedulingsParams",
    "TechnicianSettings",
    "TechnicianSettingsGroup",
    "TechnicianSettingsGroupParams",
    "TechnicianSettingsParams",
    "TerminationReasonParams",
    "TerritoryParams",
    "TrackingNoteBroker",
    "TrackingNoteItem",
    "TrackingNoteParams",
    "TransactionCodeParams",
    "TranslationsInUserLanguage",
    "TransportationDocumentLineData",
    "TransportationDocumentParams",
    "UnitOfMeasurementGroupParams",
    "UnitOfMeasurementParams",
    "UoMGroupDefinition",
    "UoMPrice",
    "UpdateUserLicenseParams",
    "UserAccessLog",
    "UserActionRecordItem",
    "UserBranchAssignmentItem",
    "UserDefaultGroupParams",
    "UserFieldMDParams",
    "UserGroupByUserItem",
    "UserGroupParams",
    "UserKeysMDParams",
    "UserKeysMD_Element",
    "UserLanguageParams",
    "UserMenuItem",
    "UserMenuParams",
    "UserObjectMD_ChildTable",
    "UserObjectMD_EnhancedFormColumn",
    "UserObjectMD_FindColumn",
    "UserObjectMD_FormColumn",
    "UserObjectsMDParams",
    "UserParams",
    "UserPermissionForm",
    "UserPermissionItem",
    "UserPermissionTreeParams",
    "UserQueryParams",
    "UserTablesMDParams",
    "UserValidValue",
    "ValidValueMD",
    "ValueMappingCommunicationParams",
    "ValueMappingParams",
    "VatGroupParams",
    "VatGroups_Line",
    "WIPMapping",
    "WTDBP",
    "WTDCodeParams",
    "WTDEffectiveDate",
    "WTDFreight",
    "WTDItem",
    "WTDValueRange",
    "WTGroups",
    "WTaxTypeCodeParams",
    "WarehouseLocationParams",
    "WarehouseParams",
    "WarehouseSublevelCodeParams",
    "WebClientBookmarkTileParams",
    "WebClientDashboardCard",
    "WebClientDashboardParams",
    "WebClientFormSettingItem",
    "WebClientFormSettingParams",
    "WebClientLaunchpadGroup",
    "WebClientLaunchpadParams",
    "WebClientLaunchpadTile",
    "WebClientListviewFilterCondition",
    "WebClientListviewFilterParams",
    "WebClientNotificationParams",
    "WebClientPreferenceParams",
    "WebClientRecentActivityParams",
    "WebClientVariantEmbeddedChart",
    "WebClientVariantEmbeddedChartSize",
    "WebClientVariantEmbeddedChartValue1",
    "WebClientVariantEmbeddedChartValue2",
    "WebClientVariantGroupBy",
    "WebClientVariantGroupParams",
    "WebClientVariantMChart",
    "WebClientVariantMChartSize",
    "WebClientVariantMChartValue1",
    "WebClientVariantMChartValue2",
    "WebClientVariantParams",
    "WebClientVariantSelectedColumn",
    "WebClientVariantSortBy",
    "WeightMeasureParams",
    "WithholdingTaxCertificatesData",
    "WithholdingTaxCodeParams",
    "WithholdingTaxCodes_Line",
    "WithholdingTaxCodes_ValueRange_Line",
    "WithholdingTaxData",
    "WithholdingTaxDataWTX",
    "WithholdingTaxLine",
    "WizardPaymentMethodParams",
    "WorkflowApprovalTaskListParams",
    "WorkflowTask",
    "WorkflowTaskCompleteParams",
    "WorkflowTaskInputObject",
    "WorkflowTaskNote",
    "WorkflowTaskOutputObject",
    "AccountCategory",
    "AccountSegmentation",
    "AccountSegmentationCategory",
    "AccrualType",
    "Activity",
    "ActivityLocation",
    "ActivityRecipientList",
    "ActivityStatus",
    "ActivitySubject",
    "ActivityType",
    "AdditionalExpense",
    "AlertManagement",
    "AlternateCatNum",
    "ApprovalRequest",
    "ApprovalStage",
    "ApprovalTemplate",
    "AssetClass",
    "AssetDepreciationGroup",
    "AssetDocument",
    "AssetGroup",
    "AssetRevaluation",
    "Attachments2",
    "AttributeGroup",
    "B1Session",
    "BOEDocumentType",
    "BOEInstruction",
    "BOEPortfolio",
    "BPFiscalRegistryID",
    "BPPriority",
    "BPVatExemptions",
    "Bank",
    "BankChargesAllocationCode",
    "BankPage",
    "BankStatement",
    "BarCode",
    "BatchNumberDetail",
    "BillOfExchangeTransaction",
    "BinLocation",
    "BinLocationAttribute",
    "BinLocationField",
    "BlanketAgreement",
    "Branch",
    "BrazilBeverageIndexer",
    "BrazilFuelIndexer",
    "BrazilMultiIndexer",
    "BrazilNumericIndexer",
    "BrazilStringIndexer",
    "Budget",
    "BudgetDistribution",
    "BudgetScenario",
    "BusinessPartner",
    "BusinessPartnerGroup",
    "BusinessPartnerProperty",
    "BusinessPlace",
    "CIGCode",
    "CUPCode",
    "Campaign",
    "CampaignResponseType",
    "CashDiscount",
    "CashFlowLineItem",
    "CentralBankIndicator",
    "CertificateSeries",
    "ChartOfAccount",
    "ChecksforPayment",
    "ChooseFromList",
    "ClosingDateProcedure",
    "Cockpit",
    "ColumnPreferences",
    "CommissionGroup",
    "Contact",
    "ContractTemplate",
    "CostCenterType",
    "CostElement",
    "Country",
    "County",
    "CreditCard",
    "CreditCardPayment",
    "CreditPaymentMethod",
    "Currency",
    "CustomerEquipmentCard",
    "CustomsDeclaration",
    "CustomsGroup",
    "CycleCountDetermination",
    "DNFCodeSetup",
    "DeductibleTax",
    "DeductionTaxGroup",
    "DeductionTaxHierarchy",
    "DeductionTaxSubGroup",
    "DefaultElementsforCR",
    "Department",
    "Deposit",
    "DepreciationArea",
    "DepreciationType",
    "DepreciationTypePool",
    "DeterminationCriteria",
    "Dimension",
    "DistributionRule",
    "Document",
    "DunningLetter",
    "DunningTerm",
    "DynamicSystemString",
    "EBooks",
    "EWBTransporter",
    "ElectronicFileFormat",
    "EmailGroup",
    "EmployeeIDType",
    "EmployeeImage",
    "EmployeeInfo",
    "EmployeePosition",
    "EmployeeRoleSetup",
    "EmployeeStatus",
    "EmployeeTransfer",
    "EmploymentCategory",
    "EnhancedDiscountGroup",
    "ExceptionalEvent",
    "ExpenseTypeData",
    "ExportDetermination",
    "ExtendedTranslation",
    "FAAccountDetermination",
    "FactoringIndicator",
    "FinancialYear",
    "FiscalPrinter",
    "FormattedSearch",
    "Forms1099",
    "GLAccountAdvancedRule",
    "Gender",
    "GovPayCode",
    "Holiday",
    "HouseBankAccount",
    "IdentificationCode",
    "ImportDetermination",
    "IndiaHsn",
    "IndiaSacCode",
    "Industry",
    "IntegrationPackageConfigure",
    "InternalReconciliation",
    "IntrastatConfiguration",
    "InventoryCounting",
    "InventoryCountingDraft",
    "InventoryCycles",
    "InventoryOpeningBalance",
    "InventoryPosting",
    "Item",
    "ItemGroups",
    "ItemImage",
    "ItemProperty",
    "JournalEntry",
    "JournalEntryDocumentType",
    "KPI",
    "KnowledgeBaseSolution",
    "LandedCost",
    "LandedCostsCode",
    "LegalData",
    "LengthMeasure",
    "LocalEra",
    "Manufacturer",
    "MaterialGroup",
    "MaterialRevaluation",
    "Message",
    "MobileAddOnSetting",
    "MultiLanguageTranslation",
    "NCMCodeSetup",
    "NFModel",
    "NFTaxCategory",
    "NatureOfAssessee",
    "NotaFiscalCFOP",
    "NotaFiscalCST",
    "NotaFiscalUsage",
    "OccurenceCode",
    "PM_ProjectDocumentData",
    "PM_TimeSheetData",
    "POSDailySummary",
    "PackagesType",
    "PartnersSetup",
    "Payment",
    "PaymentBlock",
    "PaymentReasonCode",
    "PaymentRunExport",
    "PaymentTermsType",
    "PickList",
    "Picture",
    "PostingTemplates",
    "PredefinedText",
    "PriceList",
    "ProductTree",
    "ProductionOrder",
    "ProfitCenter",
    "Project",
    "PurchaseTaxInvoice",
    "QueryAuthGroup",
    "QueryCategory",
    "Queue",
    "RecurringPostings",
    "Relationship",
    "ReportType",
    "Resource",
    "ResourceCapacity",
    "ResourceGroup",
    "ResourceProperty",
    "RetornoCode",
    "RouteStage",
    "SQLQuery",
    "SQLView",
    "SalesForecast",
    "SalesOpportunities",
    "SalesOpportunityCompetitorSetup",
    "SalesOpportunityInterestSetup",
    "SalesOpportunityReasonSetup",
    "SalesOpportunitySourceSetup",
    "SalesPerson",
    "SalesStage",
    "SalesTaxAuthoritiesType",
    "SalesTaxAuthority",
    "SalesTaxCode",
    "SalesTaxInvoice",
    "Section",
    "SerialNumberDetail",
    "ServiceCall",
    "ServiceCallOrigin",
    "ServiceCallProblemSubType",
    "ServiceCallProblemType",
    "ServiceCallSolutionStatus",
    "ServiceCallStatus",
    "ServiceCallType",
    "ServiceContract",
    "ServiceGroup",
    "ShippingType",
    "ShortLinkMapping",
    "SingleUserConnection",
    "SpecialPrice",
    "State",
    "StockTaking",
    "StockTransfer",
    "TSRExceptionalEvent",
    "TargetGroup",
    "TaxCodeDetermination",
    "TaxCodeDeterminationTCD",
    "TaxExemptReason",
    "TaxInvoiceReport",
    "TaxReplStateSubData",
    "TaxReportFilter",
    "TaxWebSite",
    "Team",
    "TerminationReason",
    "Territory",
    "TrackingNote",
    "TransactionCode",
    "TransportationDocumentData",
    "UnitOfMeasurement",
    "UnitOfMeasurementGroup",
    "User",
    "UserDefaultGroup",
    "UserFieldMD",
    "UserGroup",
    "UserKeysMD",
    "UserLanguage",
    "UserObjectsMD",
    "UserPermissionTree",
    "UserQuery",
    "UserTablesMD",
    "ValueMappingCommunicationData",
    "VatGroup",
    "WTDCode",
    "WTaxTypeCode",
    "Warehouse",
    "WarehouseLocation",
    "WarehouseSublevelCode",
    "WebClientBookmarkTile",
    "WebClientDashboard",
    "WebClientFormSetting",
    "WebClientLaunchpad",
    "WebClientListviewFilter",
    "WebClientNotification",
    "WebClientPreference",
    "WebClientRecentActivity",
    "WebClientVariant",
    "WebClientVariantGroup",
    "WeightMeasure",
    "WithholdingTaxCode",
    "WizardPaymentMethod",
    "AssetCapitalization",
    "AssetCapitalizationCreditMemo",
    "AssetManualDepreciation",
    "AssetRetirement",
    "AssetTransfer",
    "CorrectionInvoice",
    "CorrectionInvoiceReversal",
    "CorrectionPurchaseInvoice",
    "CorrectionPurchaseInvoiceReversal",
    "CreditNote",
    "DeliveryNote",
    "DownPayment",
    "Draft",
    "EmployeeRolesSetup",
    "EmployeesInfo",
    "FormPreference",
    "GoodsReturnRequest",
    "IncomingPayment",
    "IntegrationPackagesConfigure",
    "InventoryCycle",
    "InventoryGenEntry",
    "InventoryGenExit",
    "InventoryTransferRequest",
    "Invoice",
    "ItemGroup",
    "NCMCodesSetup",
    "OccurrenceCode",
    "Order",
    "PaymentDraft",
    "ProjectManagement",
    "ProjectManagementTimeSheet",
    "PurchaseCreditNote",
    "PurchaseDeliveryNote",
    "PurchaseDownPayment",
    "PurchaseInvoice",
    "PurchaseOrder",
    "PurchaseQuotation",
    "PurchaseRequest",
    "PurchaseReturn",
    "Quotation",
    "ReportFilter",
    "Return",
    "ReturnRequest",
    "SalesOpportunity",
    "SalesOpportunityCompetitorsSetup",
    "SalesOpportunityInterestsSetup",
    "SalesOpportunityReasonsSetup",
    "SalesOpportunitySourcesSetup",
    "SelfCreditMemo",
    "SelfInvoice",
    "StockTransferDraft",
    "TaxCodeDeterminationsTCD",
    "TransportationDocument",
    "UserFieldsMD",
    "ValueMappingCommunication",
    "VendorPayment",
    "WitholdingTaxDefinition",
]

# Master namespace for cross-domain resolution
_NAMESPACE = {
    "AccountCategory": AccountCategory,
    "AccountSegmentation": AccountSegmentation,
    "AccountSegmentationCategory": AccountSegmentationCategory,
    "AccrualType": AccrualType,
    "Activity": Activity,
    "ActivityLocation": ActivityLocation,
    "ActivityRecipientList": ActivityRecipientList,
    "ActivityStatus": ActivityStatus,
    "ActivitySubject": ActivitySubject,
    "ActivityType": ActivityType,
    "AdditionalExpense": AdditionalExpense,
    "AlertManagement": AlertManagement,
    "AlternateCatNum": AlternateCatNum,
    "ApprovalRequest": ApprovalRequest,
    "ApprovalStage": ApprovalStage,
    "ApprovalTemplate": ApprovalTemplate,
    "AssetClass": AssetClass,
    "AssetDepreciationGroup": AssetDepreciationGroup,
    "AssetDocument": AssetDocument,
    "AssetGroup": AssetGroup,
    "AssetRevaluation": AssetRevaluation,
    "Attachments2": Attachments2,
    "AttributeGroup": AttributeGroup,
    "B1Session": B1Session,
    "BOEDocumentType": BOEDocumentType,
    "BOEInstruction": BOEInstruction,
    "BOEPortfolio": BOEPortfolio,
    "BPFiscalRegistryID": BPFiscalRegistryID,
    "BPPriority": BPPriority,
    "BPVatExemptions": BPVatExemptions,
    "Bank": Bank,
    "BankChargesAllocationCode": BankChargesAllocationCode,
    "BankPage": BankPage,
    "BankStatement": BankStatement,
    "BarCode": BarCode,
    "BatchNumberDetail": BatchNumberDetail,
    "BillOfExchangeTransaction": BillOfExchangeTransaction,
    "BinLocation": BinLocation,
    "BinLocationAttribute": BinLocationAttribute,
    "BinLocationField": BinLocationField,
    "BlanketAgreement": BlanketAgreement,
    "Branch": Branch,
    "BrazilBeverageIndexer": BrazilBeverageIndexer,
    "BrazilFuelIndexer": BrazilFuelIndexer,
    "BrazilMultiIndexer": BrazilMultiIndexer,
    "BrazilNumericIndexer": BrazilNumericIndexer,
    "BrazilStringIndexer": BrazilStringIndexer,
    "Budget": Budget,
    "BudgetDistribution": BudgetDistribution,
    "BudgetScenario": BudgetScenario,
    "BusinessPartner": BusinessPartner,
    "BusinessPartnerGroup": BusinessPartnerGroup,
    "BusinessPartnerProperty": BusinessPartnerProperty,
    "BusinessPlace": BusinessPlace,
    "CIGCode": CIGCode,
    "CUPCode": CUPCode,
    "Campaign": Campaign,
    "CampaignResponseType": CampaignResponseType,
    "CashDiscount": CashDiscount,
    "CashFlowLineItem": CashFlowLineItem,
    "CentralBankIndicator": CentralBankIndicator,
    "CertificateSeries": CertificateSeries,
    "ChartOfAccount": ChartOfAccount,
    "ChecksforPayment": ChecksforPayment,
    "ChooseFromList": ChooseFromList,
    "ClosingDateProcedure": ClosingDateProcedure,
    "Cockpit": Cockpit,
    "ColumnPreferences": ColumnPreferences,
    "CommissionGroup": CommissionGroup,
    "Contact": Contact,
    "ContractTemplate": ContractTemplate,
    "CostCenterType": CostCenterType,
    "CostElement": CostElement,
    "Country": Country,
    "County": County,
    "CreditCard": CreditCard,
    "CreditCardPayment": CreditCardPayment,
    "CreditPaymentMethod": CreditPaymentMethod,
    "Currency": Currency,
    "CustomerEquipmentCard": CustomerEquipmentCard,
    "CustomsDeclaration": CustomsDeclaration,
    "CustomsGroup": CustomsGroup,
    "CycleCountDetermination": CycleCountDetermination,
    "DNFCodeSetup": DNFCodeSetup,
    "DeductibleTax": DeductibleTax,
    "DeductionTaxGroup": DeductionTaxGroup,
    "DeductionTaxHierarchy": DeductionTaxHierarchy,
    "DeductionTaxSubGroup": DeductionTaxSubGroup,
    "DefaultElementsforCR": DefaultElementsforCR,
    "Department": Department,
    "Deposit": Deposit,
    "DepreciationArea": DepreciationArea,
    "DepreciationType": DepreciationType,
    "DepreciationTypePool": DepreciationTypePool,
    "DeterminationCriteria": DeterminationCriteria,
    "Dimension": Dimension,
    "DistributionRule": DistributionRule,
    "Document": Document,
    "DunningLetter": DunningLetter,
    "DunningTerm": DunningTerm,
    "DynamicSystemString": DynamicSystemString,
    "EBooks": EBooks,
    "EWBTransporter": EWBTransporter,
    "ElectronicFileFormat": ElectronicFileFormat,
    "EmailGroup": EmailGroup,
    "EmployeeIDType": EmployeeIDType,
    "EmployeeImage": EmployeeImage,
    "EmployeeInfo": EmployeeInfo,
    "EmployeePosition": EmployeePosition,
    "EmployeeRoleSetup": EmployeeRoleSetup,
    "EmployeeStatus": EmployeeStatus,
    "EmployeeTransfer": EmployeeTransfer,
    "EmploymentCategory": EmploymentCategory,
    "EnhancedDiscountGroup": EnhancedDiscountGroup,
    "ExceptionalEvent": ExceptionalEvent,
    "ExpenseTypeData": ExpenseTypeData,
    "ExportDetermination": ExportDetermination,
    "ExtendedTranslation": ExtendedTranslation,
    "FAAccountDetermination": FAAccountDetermination,
    "FactoringIndicator": FactoringIndicator,
    "FinancialYear": FinancialYear,
    "FiscalPrinter": FiscalPrinter,
    "FormattedSearch": FormattedSearch,
    "Forms1099": Forms1099,
    "GLAccountAdvancedRule": GLAccountAdvancedRule,
    "Gender": Gender,
    "GovPayCode": GovPayCode,
    "Holiday": Holiday,
    "HouseBankAccount": HouseBankAccount,
    "IdentificationCode": IdentificationCode,
    "ImportDetermination": ImportDetermination,
    "IndiaHsn": IndiaHsn,
    "IndiaSacCode": IndiaSacCode,
    "Industry": Industry,
    "IntegrationPackageConfigure": IntegrationPackageConfigure,
    "InternalReconciliation": InternalReconciliation,
    "IntrastatConfiguration": IntrastatConfiguration,
    "InventoryCounting": InventoryCounting,
    "InventoryCountingDraft": InventoryCountingDraft,
    "InventoryCycles": InventoryCycles,
    "InventoryOpeningBalance": InventoryOpeningBalance,
    "InventoryPosting": InventoryPosting,
    "Item": Item,
    "ItemGroups": ItemGroups,
    "ItemImage": ItemImage,
    "ItemProperty": ItemProperty,
    "JournalEntry": JournalEntry,
    "JournalEntryDocumentType": JournalEntryDocumentType,
    "KPI": KPI,
    "KnowledgeBaseSolution": KnowledgeBaseSolution,
    "LandedCost": LandedCost,
    "LandedCostsCode": LandedCostsCode,
    "LegalData": LegalData,
    "LengthMeasure": LengthMeasure,
    "LocalEra": LocalEra,
    "Manufacturer": Manufacturer,
    "MaterialGroup": MaterialGroup,
    "MaterialRevaluation": MaterialRevaluation,
    "Message": Message,
    "MobileAddOnSetting": MobileAddOnSetting,
    "MultiLanguageTranslation": MultiLanguageTranslation,
    "NCMCodeSetup": NCMCodeSetup,
    "NFModel": NFModel,
    "NFTaxCategory": NFTaxCategory,
    "NatureOfAssessee": NatureOfAssessee,
    "NotaFiscalCFOP": NotaFiscalCFOP,
    "NotaFiscalCST": NotaFiscalCST,
    "NotaFiscalUsage": NotaFiscalUsage,
    "OccurenceCode": OccurenceCode,
    "PM_ProjectDocumentData": PM_ProjectDocumentData,
    "PM_TimeSheetData": PM_TimeSheetData,
    "POSDailySummary": POSDailySummary,
    "PackagesType": PackagesType,
    "PartnersSetup": PartnersSetup,
    "Payment": Payment,
    "PaymentBlock": PaymentBlock,
    "PaymentReasonCode": PaymentReasonCode,
    "PaymentRunExport": PaymentRunExport,
    "PaymentTermsType": PaymentTermsType,
    "PickList": PickList,
    "Picture": Picture,
    "PostingTemplates": PostingTemplates,
    "PredefinedText": PredefinedText,
    "PriceList": PriceList,
    "ProductTree": ProductTree,
    "ProductionOrder": ProductionOrder,
    "ProfitCenter": ProfitCenter,
    "Project": Project,
    "PurchaseTaxInvoice": PurchaseTaxInvoice,
    "QueryAuthGroup": QueryAuthGroup,
    "QueryCategory": QueryCategory,
    "Queue": Queue,
    "RecurringPostings": RecurringPostings,
    "Relationship": Relationship,
    "ReportType": ReportType,
    "Resource": Resource,
    "ResourceCapacity": ResourceCapacity,
    "ResourceGroup": ResourceGroup,
    "ResourceProperty": ResourceProperty,
    "RetornoCode": RetornoCode,
    "RouteStage": RouteStage,
    "SQLQuery": SQLQuery,
    "SQLView": SQLView,
    "SalesForecast": SalesForecast,
    "SalesOpportunities": SalesOpportunities,
    "SalesOpportunityCompetitorSetup": SalesOpportunityCompetitorSetup,
    "SalesOpportunityInterestSetup": SalesOpportunityInterestSetup,
    "SalesOpportunityReasonSetup": SalesOpportunityReasonSetup,
    "SalesOpportunitySourceSetup": SalesOpportunitySourceSetup,
    "SalesPerson": SalesPerson,
    "SalesStage": SalesStage,
    "SalesTaxAuthoritiesType": SalesTaxAuthoritiesType,
    "SalesTaxAuthority": SalesTaxAuthority,
    "SalesTaxCode": SalesTaxCode,
    "SalesTaxInvoice": SalesTaxInvoice,
    "Section": Section,
    "SerialNumberDetail": SerialNumberDetail,
    "ServiceCall": ServiceCall,
    "ServiceCallOrigin": ServiceCallOrigin,
    "ServiceCallProblemSubType": ServiceCallProblemSubType,
    "ServiceCallProblemType": ServiceCallProblemType,
    "ServiceCallSolutionStatus": ServiceCallSolutionStatus,
    "ServiceCallStatus": ServiceCallStatus,
    "ServiceCallType": ServiceCallType,
    "ServiceContract": ServiceContract,
    "ServiceGroup": ServiceGroup,
    "ShippingType": ShippingType,
    "ShortLinkMapping": ShortLinkMapping,
    "SingleUserConnection": SingleUserConnection,
    "SpecialPrice": SpecialPrice,
    "State": State,
    "StockTaking": StockTaking,
    "StockTransfer": StockTransfer,
    "TSRExceptionalEvent": TSRExceptionalEvent,
    "TargetGroup": TargetGroup,
    "TaxCodeDetermination": TaxCodeDetermination,
    "TaxCodeDeterminationTCD": TaxCodeDeterminationTCD,
    "TaxExemptReason": TaxExemptReason,
    "TaxInvoiceReport": TaxInvoiceReport,
    "TaxReplStateSubData": TaxReplStateSubData,
    "TaxReportFilter": TaxReportFilter,
    "TaxWebSite": TaxWebSite,
    "Team": Team,
    "TerminationReason": TerminationReason,
    "Territory": Territory,
    "TrackingNote": TrackingNote,
    "TransactionCode": TransactionCode,
    "TransportationDocumentData": TransportationDocumentData,
    "UnitOfMeasurement": UnitOfMeasurement,
    "UnitOfMeasurementGroup": UnitOfMeasurementGroup,
    "User": User,
    "UserDefaultGroup": UserDefaultGroup,
    "UserFieldMD": UserFieldMD,
    "UserGroup": UserGroup,
    "UserKeysMD": UserKeysMD,
    "UserLanguage": UserLanguage,
    "UserObjectsMD": UserObjectsMD,
    "UserPermissionTree": UserPermissionTree,
    "UserQuery": UserQuery,
    "UserTablesMD": UserTablesMD,
    "ValueMappingCommunicationData": ValueMappingCommunicationData,
    "VatGroup": VatGroup,
    "WTDCode": WTDCode,
    "WTaxTypeCode": WTaxTypeCode,
    "Warehouse": Warehouse,
    "WarehouseLocation": WarehouseLocation,
    "WarehouseSublevelCode": WarehouseSublevelCode,
    "WebClientBookmarkTile": WebClientBookmarkTile,
    "WebClientDashboard": WebClientDashboard,
    "WebClientFormSetting": WebClientFormSetting,
    "WebClientLaunchpad": WebClientLaunchpad,
    "WebClientListviewFilter": WebClientListviewFilter,
    "WebClientNotification": WebClientNotification,
    "WebClientPreference": WebClientPreference,
    "WebClientRecentActivity": WebClientRecentActivity,
    "WebClientVariant": WebClientVariant,
    "WebClientVariantGroup": WebClientVariantGroup,
    "WeightMeasure": WeightMeasure,
    "WithholdingTaxCode": WithholdingTaxCode,
    "WizardPaymentMethod": WizardPaymentMethod,
    "AssetCapitalization": AssetCapitalization,
    "AssetCapitalizationCreditMemo": AssetCapitalizationCreditMemo,
    "AssetManualDepreciation": AssetManualDepreciation,
    "AssetRetirement": AssetRetirement,
    "AssetTransfer": AssetTransfer,
    "CorrectionInvoice": CorrectionInvoice,
    "CorrectionInvoiceReversal": CorrectionInvoiceReversal,
    "CorrectionPurchaseInvoice": CorrectionPurchaseInvoice,
    "CorrectionPurchaseInvoiceReversal": CorrectionPurchaseInvoiceReversal,
    "CreditNote": CreditNote,
    "DeliveryNote": DeliveryNote,
    "DownPayment": DownPayment,
    "Draft": Draft,
    "EmployeeRolesSetup": EmployeeRolesSetup,
    "EmployeesInfo": EmployeesInfo,
    "FormPreference": FormPreference,
    "GoodsReturnRequest": GoodsReturnRequest,
    "IncomingPayment": IncomingPayment,
    "IntegrationPackagesConfigure": IntegrationPackagesConfigure,
    "InventoryCycle": InventoryCycle,
    "InventoryGenEntry": InventoryGenEntry,
    "InventoryGenExit": InventoryGenExit,
    "InventoryTransferRequest": InventoryTransferRequest,
    "Invoice": Invoice,
    "ItemGroup": ItemGroup,
    "NCMCodesSetup": NCMCodesSetup,
    "OccurrenceCode": OccurrenceCode,
    "Order": Order,
    "PaymentDraft": PaymentDraft,
    "ProjectManagement": ProjectManagement,
    "ProjectManagementTimeSheet": ProjectManagementTimeSheet,
    "PurchaseCreditNote": PurchaseCreditNote,
    "PurchaseDeliveryNote": PurchaseDeliveryNote,
    "PurchaseDownPayment": PurchaseDownPayment,
    "PurchaseInvoice": PurchaseInvoice,
    "PurchaseOrder": PurchaseOrder,
    "PurchaseQuotation": PurchaseQuotation,
    "PurchaseRequest": PurchaseRequest,
    "PurchaseReturn": PurchaseReturn,
    "Quotation": Quotation,
    "ReportFilter": ReportFilter,
    "Return": Return,
    "ReturnRequest": ReturnRequest,
    "SalesOpportunity": SalesOpportunity,
    "SalesOpportunityCompetitorsSetup": SalesOpportunityCompetitorsSetup,
    "SalesOpportunityInterestsSetup": SalesOpportunityInterestsSetup,
    "SalesOpportunityReasonsSetup": SalesOpportunityReasonsSetup,
    "SalesOpportunitySourcesSetup": SalesOpportunitySourcesSetup,
    "SelfCreditMemo": SelfCreditMemo,
    "SelfInvoice": SelfInvoice,
    "StockTransferDraft": StockTransferDraft,
    "TaxCodeDeterminationsTCD": TaxCodeDeterminationsTCD,
    "TransportationDocument": TransportationDocument,
    "UserFieldsMD": UserFieldsMD,
    "ValueMappingCommunication": ValueMappingCommunication,
    "VendorPayment": VendorPayment,
    "WitholdingTaxDefinition": WitholdingTaxDefinition,
}

# Rebuild models to resolve forward references
for name in _NAMESPACE:
    model = _NAMESPACE[name]
    if hasattr(model, "model_rebuild"):
        model.model_rebuild(_types_namespace=_NAMESPACE)
