# AUTO-GENERATED — do not edit by hand.
from __future__ import annotations

from . import (
    businesspartners,
    finance,
    general,
    inventory,
    production,
    purchasing,
    sales,
)
from .businesspartners import (
    Activity,
    ActivityLocation,
    ActivityRecipientList,
    ActivityStatus,
    ActivitySubject,
    ActivityType,
    BusinessPartner,
    BusinessPartnerGroup,
    BusinessPartnerProperty,
)
from .finance import (
    AssetClass,
    ChartOfAccount,
    CostCenterType,
    Currency,
    JournalEntry,
    JournalEntryDocumentType,
    ProfitCenter,
    VatGroup,
    WithholdingTaxCode,
)
from .general import (
    KPI,
    AccountCategory,
    AccountSegmentation,
    AccountSegmentationCategory,
    AccrualType,
    AdditionalExpense,
    AlertManagement,
    AlternateCatNum,
    ApprovalRequest,
    ApprovalStage,
    ApprovalTemplate,
    AssetDepreciationGroup,
    AssetDocument,
    AssetGroup,
    AssetRevaluation,
    Attachments2,
    AttributeGroup,
    B1Session,
    Bank,
    BankChargesAllocationCode,
    BankPage,
    BankStatement,
    BarCode,
    BatchNumberDetail,
    BillOfExchangeTransaction,
    BinLocation,
    BinLocationAttribute,
    BinLocationField,
    BOEDocumentType,
    BOEInstruction,
    BOEPortfolio,
    BPFiscalRegistryID,
    BPPriority,
    BPVatExemptions,
    Branch,
    BrazilBeverageIndexer,
    BrazilFuelIndexer,
    BrazilMultiIndexer,
    BrazilNumericIndexer,
    BrazilStringIndexer,
    Budget,
    BudgetDistribution,
    BudgetScenario,
    BusinessPlace,
    Campaign,
    CampaignResponseType,
    CashDiscount,
    CashFlowLineItem,
    CentralBankIndicator,
    CertificateSeries,
    ChecksforPayment,
    ChooseFromList,
    CIGCode,
    ClosingDateProcedure,
    Cockpit,
    ColumnPreferences,
    CommissionGroup,
    Contact,
    CostElement,
    Country,
    County,
    CreditCard,
    CreditCardPayment,
    CreditPaymentMethod,
    CUPCode,
    CustomerEquipmentCard,
    CustomsDeclaration,
    CustomsGroup,
    DeductibleTax,
    DeductionTaxGroup,
    DeductionTaxHierarchy,
    DeductionTaxSubGroup,
    DefaultElementsforCR,
    Department,
    Deposit,
    DepreciationArea,
    DepreciationType,
    DepreciationTypePool,
    DeterminationCriteria,
    Dimension,
    DistributionRule,
    DNFCodeSetup,
    Document,
    DunningLetter,
    DunningTerm,
    DynamicSystemString,
    EBooks,
    ElectronicFileFormat,
    EmailGroup,
    EmployeeIDType,
    EmployeeImage,
    EmployeeInfo,
    EmployeePosition,
    EmployeeRoleSetup,
    EmployeeStatus,
    EmployeeTransfer,
    EmploymentCategory,
    EnhancedDiscountGroup,
    EWBTransporter,
    ExceptionalEvent,
    ExpenseTypeData,
    ExportDetermination,
    ExtendedTranslation,
    FAAccountDetermination,
    FactoringIndicator,
    FinancialYear,
    FiscalPrinter,
    FormattedSearch,
    Forms1099,
    Gender,
    GLAccountAdvancedRule,
    GovPayCode,
    Holiday,
    HouseBankAccount,
    IdentificationCode,
    ImportDetermination,
    IndiaHsn,
    IndiaSacCode,
    Industry,
    IntegrationPackageConfigure,
    InternalReconciliation,
    IntrastatConfiguration,
    InventoryCycles,
    KnowledgeBaseSolution,
    LegalData,
    LengthMeasure,
    LocalEra,
    Manufacturer,
    MaterialGroup,
    Message,
    MobileAddOnSetting,
    MultiLanguageTranslation,
    NatureOfAssessee,
    NCMCodeSetup,
    NFModel,
    NFTaxCategory,
    NotaFiscalCFOP,
    NotaFiscalCST,
    NotaFiscalUsage,
    OccurenceCode,
    PackagesType,
    PartnersSetup,
    Payment,
    PaymentBlock,
    PaymentReasonCode,
    PaymentRunExport,
    PaymentTermsType,
    PickList,
    Picture,
    PM_ProjectDocumentData,
    PM_TimeSheetData,
    POSDailySummary,
    PostingTemplates,
    PredefinedText,
    PriceList,
    Project,
    PurchaseTaxInvoice,
    QueryAuthGroup,
    QueryCategory,
    Queue,
    RecurringPostings,
    Relationship,
    ReportType,
    RetornoCode,
    RouteStage,
    SalesForecast,
    SalesOpportunities,
    SalesOpportunityCompetitorSetup,
    SalesOpportunityInterestSetup,
    SalesOpportunityReasonSetup,
    SalesOpportunitySourceSetup,
    SalesPerson,
    SalesStage,
    SalesTaxAuthoritiesType,
    SalesTaxAuthority,
    SalesTaxCode,
    SalesTaxInvoice,
    Section,
    SerialNumberDetail,
    ServiceContract,
    ServiceGroup,
    ShippingType,
    ShortLinkMapping,
    SingleUserConnection,
    SpecialPrice,
    SQLQuery,
    SQLView,
    State,
    StockTaking,
    TargetGroup,
    TaxCodeDetermination,
    TaxCodeDeterminationTCD,
    TaxExemptReason,
    TaxInvoiceReport,
    TaxReplStateSubData,
    TaxReportFilter,
    TaxWebSite,
    Team,
    TerminationReason,
    Territory,
    TrackingNote,
    TransactionCode,
    TransportationDocumentData,
    TSRExceptionalEvent,
    UnitOfMeasurement,
    UnitOfMeasurementGroup,
    User,
    UserDefaultGroup,
    UserFieldMD,
    UserGroup,
    UserKeysMD,
    UserLanguage,
    UserObjectsMD,
    UserPermissionTree,
    UserQuery,
    UserTablesMD,
    ValueMappingCommunicationData,
    WebClientBookmarkTile,
    WebClientDashboard,
    WebClientFormSetting,
    WebClientLaunchpad,
    WebClientListviewFilter,
    WebClientNotification,
    WebClientPreference,
    WebClientRecentActivity,
    WebClientVariant,
    WebClientVariantGroup,
    WeightMeasure,
    WizardPaymentMethod,
    WTaxTypeCode,
    WTDCode,
)
from .inventory import (
    CycleCountDetermination,
    InventoryCounting,
    InventoryCountingDraft,
    InventoryOpeningBalance,
    InventoryPosting,
    Item,
    ItemGroups,
    ItemImage,
    ItemProperty,
    MaterialRevaluation,
    StockTransfer,
    Warehouse,
    WarehouseLocation,
    WarehouseSublevelCode,
)
from .production import (
    ProductionOrder,
    ProductTree,
    Resource,
    ResourceCapacity,
    ResourceGroup,
    ResourceProperty,
)
from .purchasing import LandedCost, LandedCostsCode
from .sales import (
    BlanketAgreement,
    ContractTemplate,
    ServiceCall,
    ServiceCallOrigin,
    ServiceCallProblemSubType,
    ServiceCallProblemType,
    ServiceCallSolutionStatus,
    ServiceCallStatus,
    ServiceCallType,
)

_ALL_MODELS = []
_ALL_MODELS.append(general.AccountCategory)
_ALL_MODELS.append(general.AccountSegmentation)
_ALL_MODELS.append(general.AccountSegmentationCategory)
_ALL_MODELS.append(general.AccrualType)
_ALL_MODELS.append(businesspartners.Activity)
_ALL_MODELS.append(businesspartners.ActivityLocation)
_ALL_MODELS.append(businesspartners.ActivityRecipientList)
_ALL_MODELS.append(businesspartners.ActivityStatus)
_ALL_MODELS.append(businesspartners.ActivitySubject)
_ALL_MODELS.append(businesspartners.ActivityType)
_ALL_MODELS.append(general.AdditionalExpense)
_ALL_MODELS.append(general.AlertManagement)
_ALL_MODELS.append(general.AlternateCatNum)
_ALL_MODELS.append(general.ApprovalRequest)
_ALL_MODELS.append(general.ApprovalStage)
_ALL_MODELS.append(general.ApprovalTemplate)
_ALL_MODELS.append(finance.AssetClass)
_ALL_MODELS.append(general.AssetDepreciationGroup)
_ALL_MODELS.append(general.AssetDocument)
_ALL_MODELS.append(general.AssetGroup)
_ALL_MODELS.append(general.AssetRevaluation)
_ALL_MODELS.append(general.Attachments2)
_ALL_MODELS.append(general.AttributeGroup)
_ALL_MODELS.append(general.B1Session)
_ALL_MODELS.append(general.BOEDocumentType)
_ALL_MODELS.append(general.BOEInstruction)
_ALL_MODELS.append(general.BOEPortfolio)
_ALL_MODELS.append(general.BPFiscalRegistryID)
_ALL_MODELS.append(general.BPPriority)
_ALL_MODELS.append(general.BPVatExemptions)
_ALL_MODELS.append(general.Bank)
_ALL_MODELS.append(general.BankChargesAllocationCode)
_ALL_MODELS.append(general.BankPage)
_ALL_MODELS.append(general.BankStatement)
_ALL_MODELS.append(general.BarCode)
_ALL_MODELS.append(general.BatchNumberDetail)
_ALL_MODELS.append(general.BillOfExchangeTransaction)
_ALL_MODELS.append(general.BinLocation)
_ALL_MODELS.append(general.BinLocationAttribute)
_ALL_MODELS.append(general.BinLocationField)
_ALL_MODELS.append(sales.BlanketAgreement)
_ALL_MODELS.append(general.Branch)
_ALL_MODELS.append(general.BrazilBeverageIndexer)
_ALL_MODELS.append(general.BrazilFuelIndexer)
_ALL_MODELS.append(general.BrazilMultiIndexer)
_ALL_MODELS.append(general.BrazilNumericIndexer)
_ALL_MODELS.append(general.BrazilStringIndexer)
_ALL_MODELS.append(general.Budget)
_ALL_MODELS.append(general.BudgetDistribution)
_ALL_MODELS.append(general.BudgetScenario)
_ALL_MODELS.append(businesspartners.BusinessPartner)
_ALL_MODELS.append(businesspartners.BusinessPartnerGroup)
_ALL_MODELS.append(businesspartners.BusinessPartnerProperty)
_ALL_MODELS.append(general.BusinessPlace)
_ALL_MODELS.append(general.CIGCode)
_ALL_MODELS.append(general.CUPCode)
_ALL_MODELS.append(general.Campaign)
_ALL_MODELS.append(general.CampaignResponseType)
_ALL_MODELS.append(general.CashDiscount)
_ALL_MODELS.append(general.CashFlowLineItem)
_ALL_MODELS.append(general.CentralBankIndicator)
_ALL_MODELS.append(general.CertificateSeries)
_ALL_MODELS.append(finance.ChartOfAccount)
_ALL_MODELS.append(general.ChecksforPayment)
_ALL_MODELS.append(general.ChooseFromList)
_ALL_MODELS.append(general.ClosingDateProcedure)
_ALL_MODELS.append(general.Cockpit)
_ALL_MODELS.append(general.ColumnPreferences)
_ALL_MODELS.append(general.CommissionGroup)
_ALL_MODELS.append(general.Contact)
_ALL_MODELS.append(sales.ContractTemplate)
_ALL_MODELS.append(finance.CostCenterType)
_ALL_MODELS.append(general.CostElement)
_ALL_MODELS.append(general.Country)
_ALL_MODELS.append(general.County)
_ALL_MODELS.append(general.CreditCard)
_ALL_MODELS.append(general.CreditCardPayment)
_ALL_MODELS.append(general.CreditPaymentMethod)
_ALL_MODELS.append(finance.Currency)
_ALL_MODELS.append(general.CustomerEquipmentCard)
_ALL_MODELS.append(general.CustomsDeclaration)
_ALL_MODELS.append(general.CustomsGroup)
_ALL_MODELS.append(inventory.CycleCountDetermination)
_ALL_MODELS.append(general.DNFCodeSetup)
_ALL_MODELS.append(general.DeductibleTax)
_ALL_MODELS.append(general.DeductionTaxGroup)
_ALL_MODELS.append(general.DeductionTaxHierarchy)
_ALL_MODELS.append(general.DeductionTaxSubGroup)
_ALL_MODELS.append(general.DefaultElementsforCR)
_ALL_MODELS.append(general.Department)
_ALL_MODELS.append(general.Deposit)
_ALL_MODELS.append(general.DepreciationArea)
_ALL_MODELS.append(general.DepreciationType)
_ALL_MODELS.append(general.DepreciationTypePool)
_ALL_MODELS.append(general.DeterminationCriteria)
_ALL_MODELS.append(general.Dimension)
_ALL_MODELS.append(general.DistributionRule)
_ALL_MODELS.append(general.Document)
_ALL_MODELS.append(general.DunningLetter)
_ALL_MODELS.append(general.DunningTerm)
_ALL_MODELS.append(general.DynamicSystemString)
_ALL_MODELS.append(general.EBooks)
_ALL_MODELS.append(general.EWBTransporter)
_ALL_MODELS.append(general.ElectronicFileFormat)
_ALL_MODELS.append(general.EmailGroup)
_ALL_MODELS.append(general.EmployeeIDType)
_ALL_MODELS.append(general.EmployeeImage)
_ALL_MODELS.append(general.EmployeeInfo)
_ALL_MODELS.append(general.EmployeePosition)
_ALL_MODELS.append(general.EmployeeRoleSetup)
_ALL_MODELS.append(general.EmployeeStatus)
_ALL_MODELS.append(general.EmployeeTransfer)
_ALL_MODELS.append(general.EmploymentCategory)
_ALL_MODELS.append(general.EnhancedDiscountGroup)
_ALL_MODELS.append(general.ExceptionalEvent)
_ALL_MODELS.append(general.ExpenseTypeData)
_ALL_MODELS.append(general.ExportDetermination)
_ALL_MODELS.append(general.ExtendedTranslation)
_ALL_MODELS.append(general.FAAccountDetermination)
_ALL_MODELS.append(general.FactoringIndicator)
_ALL_MODELS.append(general.FinancialYear)
_ALL_MODELS.append(general.FiscalPrinter)
_ALL_MODELS.append(general.FormattedSearch)
_ALL_MODELS.append(general.Forms1099)
_ALL_MODELS.append(general.GLAccountAdvancedRule)
_ALL_MODELS.append(general.Gender)
_ALL_MODELS.append(general.GovPayCode)
_ALL_MODELS.append(general.Holiday)
_ALL_MODELS.append(general.HouseBankAccount)
_ALL_MODELS.append(general.IdentificationCode)
_ALL_MODELS.append(general.ImportDetermination)
_ALL_MODELS.append(general.IndiaHsn)
_ALL_MODELS.append(general.IndiaSacCode)
_ALL_MODELS.append(general.Industry)
_ALL_MODELS.append(general.IntegrationPackageConfigure)
_ALL_MODELS.append(general.InternalReconciliation)
_ALL_MODELS.append(general.IntrastatConfiguration)
_ALL_MODELS.append(inventory.InventoryCounting)
_ALL_MODELS.append(inventory.InventoryCountingDraft)
_ALL_MODELS.append(general.InventoryCycles)
_ALL_MODELS.append(inventory.InventoryOpeningBalance)
_ALL_MODELS.append(inventory.InventoryPosting)
from ..._overrides.inventory import Item

_ALL_MODELS.append(Item)
_ALL_MODELS.append(inventory.ItemGroups)
_ALL_MODELS.append(inventory.ItemImage)
_ALL_MODELS.append(inventory.ItemProperty)
_ALL_MODELS.append(finance.JournalEntry)
_ALL_MODELS.append(finance.JournalEntryDocumentType)
_ALL_MODELS.append(general.KPI)
_ALL_MODELS.append(general.KnowledgeBaseSolution)
_ALL_MODELS.append(purchasing.LandedCost)
_ALL_MODELS.append(purchasing.LandedCostsCode)
_ALL_MODELS.append(general.LegalData)
_ALL_MODELS.append(general.LengthMeasure)
_ALL_MODELS.append(general.LocalEra)
_ALL_MODELS.append(general.Manufacturer)
_ALL_MODELS.append(general.MaterialGroup)
_ALL_MODELS.append(inventory.MaterialRevaluation)
_ALL_MODELS.append(general.Message)
_ALL_MODELS.append(general.MobileAddOnSetting)
_ALL_MODELS.append(general.MultiLanguageTranslation)
_ALL_MODELS.append(general.NCMCodeSetup)
_ALL_MODELS.append(general.NFModel)
_ALL_MODELS.append(general.NFTaxCategory)
_ALL_MODELS.append(general.NatureOfAssessee)
_ALL_MODELS.append(general.NotaFiscalCFOP)
_ALL_MODELS.append(general.NotaFiscalCST)
_ALL_MODELS.append(general.NotaFiscalUsage)
_ALL_MODELS.append(general.OccurenceCode)
_ALL_MODELS.append(general.PM_ProjectDocumentData)
_ALL_MODELS.append(general.PM_TimeSheetData)
_ALL_MODELS.append(general.POSDailySummary)
_ALL_MODELS.append(general.PackagesType)
_ALL_MODELS.append(general.PartnersSetup)
_ALL_MODELS.append(general.Payment)
_ALL_MODELS.append(general.PaymentBlock)
_ALL_MODELS.append(general.PaymentReasonCode)
_ALL_MODELS.append(general.PaymentRunExport)
_ALL_MODELS.append(general.PaymentTermsType)
_ALL_MODELS.append(general.PickList)
_ALL_MODELS.append(general.Picture)
_ALL_MODELS.append(general.PostingTemplates)
_ALL_MODELS.append(general.PredefinedText)
_ALL_MODELS.append(general.PriceList)
_ALL_MODELS.append(production.ProductTree)
_ALL_MODELS.append(production.ProductionOrder)
_ALL_MODELS.append(finance.ProfitCenter)
_ALL_MODELS.append(general.Project)
_ALL_MODELS.append(general.PurchaseTaxInvoice)
_ALL_MODELS.append(general.QueryAuthGroup)
_ALL_MODELS.append(general.QueryCategory)
_ALL_MODELS.append(general.Queue)
_ALL_MODELS.append(general.RecurringPostings)
_ALL_MODELS.append(general.Relationship)
_ALL_MODELS.append(general.ReportType)
_ALL_MODELS.append(production.Resource)
_ALL_MODELS.append(production.ResourceCapacity)
_ALL_MODELS.append(production.ResourceGroup)
_ALL_MODELS.append(production.ResourceProperty)
_ALL_MODELS.append(general.RetornoCode)
_ALL_MODELS.append(general.RouteStage)
_ALL_MODELS.append(general.SQLQuery)
_ALL_MODELS.append(general.SQLView)
_ALL_MODELS.append(general.SalesForecast)
_ALL_MODELS.append(general.SalesOpportunities)
_ALL_MODELS.append(general.SalesOpportunityCompetitorSetup)
_ALL_MODELS.append(general.SalesOpportunityInterestSetup)
_ALL_MODELS.append(general.SalesOpportunityReasonSetup)
_ALL_MODELS.append(general.SalesOpportunitySourceSetup)
_ALL_MODELS.append(general.SalesPerson)
_ALL_MODELS.append(general.SalesStage)
_ALL_MODELS.append(general.SalesTaxAuthoritiesType)
_ALL_MODELS.append(general.SalesTaxAuthority)
_ALL_MODELS.append(general.SalesTaxCode)
_ALL_MODELS.append(general.SalesTaxInvoice)
_ALL_MODELS.append(general.Section)
_ALL_MODELS.append(general.SerialNumberDetail)
_ALL_MODELS.append(sales.ServiceCall)
_ALL_MODELS.append(sales.ServiceCallOrigin)
_ALL_MODELS.append(sales.ServiceCallProblemSubType)
_ALL_MODELS.append(sales.ServiceCallProblemType)
_ALL_MODELS.append(sales.ServiceCallSolutionStatus)
_ALL_MODELS.append(sales.ServiceCallStatus)
_ALL_MODELS.append(sales.ServiceCallType)
_ALL_MODELS.append(general.ServiceContract)
_ALL_MODELS.append(general.ServiceGroup)
_ALL_MODELS.append(general.ShippingType)
_ALL_MODELS.append(general.ShortLinkMapping)
_ALL_MODELS.append(general.SingleUserConnection)
_ALL_MODELS.append(general.SpecialPrice)
_ALL_MODELS.append(general.State)
_ALL_MODELS.append(general.StockTaking)
_ALL_MODELS.append(inventory.StockTransfer)
_ALL_MODELS.append(general.TSRExceptionalEvent)
_ALL_MODELS.append(general.TargetGroup)
_ALL_MODELS.append(general.TaxCodeDetermination)
_ALL_MODELS.append(general.TaxCodeDeterminationTCD)
_ALL_MODELS.append(general.TaxExemptReason)
_ALL_MODELS.append(general.TaxInvoiceReport)
_ALL_MODELS.append(general.TaxReplStateSubData)
_ALL_MODELS.append(general.TaxReportFilter)
_ALL_MODELS.append(general.TaxWebSite)
_ALL_MODELS.append(general.Team)
_ALL_MODELS.append(general.TerminationReason)
_ALL_MODELS.append(general.Territory)
_ALL_MODELS.append(general.TrackingNote)
_ALL_MODELS.append(general.TransactionCode)
_ALL_MODELS.append(general.TransportationDocumentData)
_ALL_MODELS.append(general.UnitOfMeasurement)
_ALL_MODELS.append(general.UnitOfMeasurementGroup)
_ALL_MODELS.append(general.User)
_ALL_MODELS.append(general.UserDefaultGroup)
_ALL_MODELS.append(general.UserFieldMD)
_ALL_MODELS.append(general.UserGroup)
_ALL_MODELS.append(general.UserKeysMD)
_ALL_MODELS.append(general.UserLanguage)
_ALL_MODELS.append(general.UserObjectsMD)
_ALL_MODELS.append(general.UserPermissionTree)
_ALL_MODELS.append(general.UserQuery)
_ALL_MODELS.append(general.UserTablesMD)
_ALL_MODELS.append(general.ValueMappingCommunicationData)
_ALL_MODELS.append(finance.VatGroup)
_ALL_MODELS.append(general.WTDCode)
_ALL_MODELS.append(general.WTaxTypeCode)
_ALL_MODELS.append(inventory.Warehouse)
_ALL_MODELS.append(inventory.WarehouseLocation)
_ALL_MODELS.append(inventory.WarehouseSublevelCode)
_ALL_MODELS.append(general.WebClientBookmarkTile)
_ALL_MODELS.append(general.WebClientDashboard)
_ALL_MODELS.append(general.WebClientFormSetting)
_ALL_MODELS.append(general.WebClientLaunchpad)
_ALL_MODELS.append(general.WebClientListviewFilter)
_ALL_MODELS.append(general.WebClientNotification)
_ALL_MODELS.append(general.WebClientPreference)
_ALL_MODELS.append(general.WebClientRecentActivity)
_ALL_MODELS.append(general.WebClientVariant)
_ALL_MODELS.append(general.WebClientVariantGroup)
_ALL_MODELS.append(general.WeightMeasure)
_ALL_MODELS.append(finance.WithholdingTaxCode)
_ALL_MODELS.append(general.WizardPaymentMethod)

# Master namespace for cross-domain resolution
_NAMESPACE = {m.__name__: m for m in _ALL_MODELS}

# Rebuild models to resolve circular dependencies
for model in _ALL_MODELS:
    model.model_rebuild(_types_namespace=_NAMESPACE)
