from __future__ import annotations
from typing import Any, TYPE_CHECKING, Literal
from pydantic import Field as PydanticField
from b1sl.b1sl.models.base import B1Model, SapBool
from ..enums import *
from ..complex_types import *
if TYPE_CHECKING:
    from .._types import *
    from .businesspartners import *
    from .finance import *
    from .general import *
    from .production import *
    from .sales import *

class ItemProperty(B1Model):
    """SAP ItemProperty Entity"""
    number: int | None = PydanticField(None, alias='Number')
    property_name: str | None = PydanticField(None, alias='PropertyName')

class Warehouse(B1Model):
    """SAP Warehouse Entity"""
    warehouse_code: str | None = PydanticField(None, alias='WarehouseCode')
    street: str | None = PydanticField(None, alias='Street')
    stock_inflation_offset_account: str | None = PydanticField(None, alias='StockInflationOffsetAccount')
    zip_code: str | None = PydanticField(None, alias='ZipCode')
    decreasing_account: str | None = PydanticField(None, alias='DecreasingAccount')
    purchase_account: str | None = PydanticField(None, alias='PurchaseAccount')
    returning_account: str | None = PydanticField(None, alias='ReturningAccount')
    shipped_goods_account: str | None = PydanticField(None, alias='ShippedGoodsAccount')
    stock_inflation_adjust_account: str | None = PydanticField(None, alias='StockInflationAdjustAccount')
    allow_use_tax: SapBool | None = PydanticField(None, alias='AllowUseTax')
    cost_inflation_account: str | None = PydanticField(None, alias='CostInflationAccount')
    foreign_expenses_account: str | None = PydanticField(None, alias='ForeignExpensesAccount')
    eu_expenses_account: str | None = PydanticField(None, alias='EUExpensesAccount')
    cost_inflation_offset_account: str | None = PydanticField(None, alias='CostInflationOffsetAccount')
    expenses_clearing_account: str | None = PydanticField(None, alias='ExpensesClearingAccount')
    purchase_returning_account: str | None = PydanticField(None, alias='PurchaseReturningAccount')
    vat_in_revenue_account: str | None = PydanticField(None, alias='VATInRevenueAccount')
    federal_tax_id: str | None = PydanticField(None, alias='FederalTaxID')
    location: int | None = PydanticField(None, alias='Location')
    block: str | None = PydanticField(None, alias='Block')
    expense_account: str | None = PydanticField(None, alias='ExpenseAccount')
    decrease_gl_account: str | None = PydanticField(None, alias='DecreaseGLAccount')
    revenues_account: str | None = PydanticField(None, alias='RevenuesAccount')
    tax_group: str | None = PydanticField(None, alias='TaxGroup')
    exempt_revenues_account: str | None = PydanticField(None, alias='ExemptRevenuesAccount')
    purchase_offset_account: str | None = PydanticField(None, alias='PurchaseOffsetAccount')
    cost_of_goods_sold: str | None = PydanticField(None, alias='CostOfGoodsSold')
    state: str | None = PydanticField(None, alias='State')
    city: str | None = PydanticField(None, alias='City')
    price_differences_account: str | None = PydanticField(None, alias='PriceDifferencesAccount')
    variance_account: str | None = PydanticField(None, alias='VarianceAccount')
    country: str | None = PydanticField(None, alias='Country')
    increase_gl_account: str | None = PydanticField(None, alias='IncreaseGLAccount')
    exchange_rate_differences_account: str | None = PydanticField(None, alias='ExchangeRateDifferencesAccount')
    wip_material_account: str | None = PydanticField(None, alias='WIPMaterialAccount')
    warehouse_name: str | None = PydanticField(None, alias='WarehouseName')
    drop_ship: SapBool | None = PydanticField(None, alias='DropShip')
    wip_material_variance_account: str | None = PydanticField(None, alias='WIPMaterialVarianceAccount')
    transfers_acc: str | None = PydanticField(None, alias='TransfersAcc')
    internal_key: int | None = PydanticField(None, alias='InternalKey')
    foreign_revenues_acc: str | None = PydanticField(None, alias='ForeignRevenuesAcc')
    building_floor_room: str | None = PydanticField(None, alias='BuildingFloorRoom')
    county: str | None = PydanticField(None, alias='County')
    nettable: SapBool | None = PydanticField(None, alias='Nettable')
    increasing_acc: str | None = PydanticField(None, alias='IncreasingAcc')
    expense_offseting_act: str | None = PydanticField(None, alias='ExpenseOffsetingAct')
    goods_clearing_acc: str | None = PydanticField(None, alias='GoodsClearingAcc')
    stock_account: str | None = PydanticField(None, alias='StockAccount')
    business_place_id: int | None = PydanticField(None, alias='BusinessPlaceID')
    purchase_credit_acc: str | None = PydanticField(None, alias='PurchaseCreditAcc')
    eu_purchase_credit_acc: str | None = PydanticField(None, alias='EUPurchaseCreditAcc')
    foreign_purchase_credit_acc: str | None = PydanticField(None, alias='ForeignPurchaseCreditAcc')
    sales_credit_acc: str | None = PydanticField(None, alias='SalesCreditAcc')
    sales_credit_eu_acc: str | None = PydanticField(None, alias='SalesCreditEUAcc')
    exempted_credits: str | None = PydanticField(None, alias='ExemptedCredits')
    sales_credit_foreign_acc: str | None = PydanticField(None, alias='SalesCreditForeignAcc')
    negative_inventory_adjustment_account: str | None = PydanticField(None, alias='NegativeInventoryAdjustmentAccount')
    wh_ship_to_name: str | None = PydanticField(None, alias='WHShipToName')
    excisable: SapBool | None = PydanticField(None, alias='Excisable')
    wh_incoming_cenvat_account: str | None = PydanticField(None, alias='WHIncomingCenvatAccount')
    wh_outgoing_cenvat_account: str | None = PydanticField(None, alias='WHOutgoingCenvatAccount')
    stock_in_transit_account: str | None = PydanticField(None, alias='StockInTransitAccount')
    wip_offset_profit_and_loss_account: str | None = PydanticField(None, alias='WipOffsetProfitAndLossAccount')
    inventory_offset_profit_and_loss_account: str | None = PydanticField(None, alias='InventoryOffsetProfitAndLossAccount')
    address_type: str | None = PydanticField(None, alias='AddressType')
    street_no: str | None = PydanticField(None, alias='StreetNo')
    storekeeper: int | None = PydanticField(None, alias='Storekeeper')
    shipper: str | None = PydanticField(None, alias='Shipper')
    manage_serial_and_batch_numbers: SapBool | None = PydanticField(None, alias='ManageSerialAndBatchNumbers')
    global_location_number: str | None = PydanticField(None, alias='GlobalLocationNumber')
    enable_bin_locations: SapBool | None = PydanticField(None, alias='EnableBinLocations')
    bin_loc_code_separator: str | None = PydanticField(None, alias='BinLocCodeSeparator')
    default_bin: int | None = PydanticField(None, alias='DefaultBin')
    default_bin_enforced: SapBool | None = PydanticField(None, alias='DefaultBinEnforced')
    auto_alloc_on_issue: BoDocWhsAutoIssueMethod | Literal['whsBinSingleChoiceOnly', 'whsBinBinCodeOrder', 'whsBinAltSortCodeOrder', 'whsBinQtyDescendingOrder', 'whsBinQtyAscendingOrder', 'whsBinFIFO', 'whsBinLIFO', 'whsBinSingleBinPreferred'] | None = PydanticField(None, alias='AutoAllocOnIssue')
    enable_receiving_bin_locations: SapBool | None = PydanticField(None, alias='EnableReceivingBinLocations')
    receiving_bin_locations_by: ReceivingBinLocationsMethodEnum | Literal['rblmBinLocationCodeOrder', 'rblmAlternativeSortCodeOrder'] | None = PydanticField(None, alias='ReceivingBinLocationsBy')
    purchase_balance_account: str | None = PydanticField(None, alias='PurchaseBalanceAccount')
    inactive: SapBool | None = PydanticField(None, alias='Inactive')
    restrict_receipt_to_empty_bin_location: SapBool | None = PydanticField(None, alias='RestrictReceiptToEmptyBinLocation')
    receive_up_to_max_quantity: SapBool | None = PydanticField(None, alias='ReceiveUpToMaxQuantity')
    auto_alloc_on_receipt: AutoAllocOnReceiptMethodEnum | Literal['aaormDefaultBin', 'aaormItemCurrentAndHistoricalBins', 'aaormItemCurrentBins', 'aaormLastBinReceivedItem'] | None = PydanticField(None, alias='AutoAllocOnReceipt')
    receive_up_to_max_weight: SapBool | None = PydanticField(None, alias='ReceiveUpToMaxWeight')
    receive_up_to_method: ReceivingUpToMethodEnum | Literal['rutmBothMaxQtyAndWeight', 'rutmMaximumQty', 'rutmMaximumWeight'] | None = PydanticField(None, alias='ReceiveUpToMethod')
    legal_text: str | None = PydanticField(None, alias='LegalText')
    address_name2: str | None = PydanticField(None, alias='AddressName2')
    address_name3: str | None = PydanticField(None, alias='AddressName3')
    user_default_groups: list[UserDefaultGroup] | None = PydanticField(None, alias='UserDefaultGroups')
    stock_transfers: list[StockTransfer] | None = PydanticField(None, alias='StockTransfers')
    chart_of_account: ChartOfAccount | None = PydanticField(None, alias='ChartOfAccount')
    warehouse_location: WarehouseLocation | None = PydanticField(None, alias='WarehouseLocation')
    sales_tax_code: SalesTaxCode | None = PydanticField(None, alias='SalesTaxCode')
    country2: Country | None = PydanticField(None, alias='Country2')
    county2: County | None = PydanticField(None, alias='County2')
    employee_info: EmployeeInfo | None = PydanticField(None, alias='EmployeeInfo')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')
    bin_location: BinLocation | None = PydanticField(None, alias='BinLocation')
    bin_locations: list[BinLocation] | None = PydanticField(None, alias='BinLocations')
    gl_account_advanced_rules: list[GLAccountAdvancedRule] | None = PydanticField(None, alias='GLAccountAdvancedRules')
    inventory_transfer_requests: list[StockTransfer] | None = PydanticField(None, alias='InventoryTransferRequests')
    resource_capacities: list[ResourceCapacity] | None = PydanticField(None, alias='ResourceCapacities')
    stock_transfer_drafts: list[StockTransfer] | None = PydanticField(None, alias='StockTransferDrafts')
    production_orders: list[ProductionOrder] | None = PydanticField(None, alias='ProductionOrders')
    business_places: list[BusinessPlace] | None = PydanticField(None, alias='BusinessPlaces')
    stock_takings: list[StockTaking] | None = PydanticField(None, alias='StockTakings')

class CycleCountDetermination(B1Model):
    """SAP CycleCountDetermination Entity"""
    warehouse_code: str | None = PydanticField(None, alias='WarehouseCode')
    cycle_by: CycleCountDeterminationCycleByEnum | Literal['ccdcbItemGroup', 'ccdcbWarehouseSublevel1', 'ccdcbWarehouseSublevel2', 'ccdcbWarehouseSublevel3', 'ccdcbWarehouseSublevel4'] | None = PydanticField(None, alias='CycleBy')
    cycle_count_determination_setup_collection: list[CycleCountDeterminationSetup] | None = PydanticField(None, alias='CycleCountDeterminationSetupCollection')

class InventoryCounting(B1Model):
    """SAP InventoryCounting Entity"""
    document_entry: int | None = PydanticField(None, alias='DocumentEntry')
    document_number: int | None = PydanticField(None, alias='DocumentNumber')
    series: int | None = PydanticField(None, alias='Series')
    count_date: str | None = PydanticField(None, alias='CountDate')
    count_time: str | None = PydanticField(None, alias='CountTime')
    single_counter_type: CounterTypeEnum | Literal['ctUser', 'ctEmployee'] | None = PydanticField(None, alias='SingleCounterType')
    single_counter_id: int | None = PydanticField(None, alias='SingleCounterID')
    document_status: CountingDocumentStatusEnum | Literal['cdsOpen', 'cdsClosed'] | None = PydanticField(None, alias='DocumentStatus')
    remarks: str | None = PydanticField(None, alias='Remarks')
    reference2: str | None = PydanticField(None, alias='Reference2')
    branch_id: int | None = PydanticField(None, alias='BranchID')
    doc_object_code_ex: str | None = PydanticField(None, alias='DocObjectCodeEx')
    financial_period: int | None = PydanticField(None, alias='FinancialPeriod')
    period_indicator: str | None = PydanticField(None, alias='PeriodIndicator')
    counting_type: CountingTypeEnum | Literal['ctSingleCounter', 'ctMultipleCounters'] | None = PydanticField(None, alias='CountingType')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    year_end_date: str | None = PydanticField(None, alias='YearEndDate')
    team_counters: list[TeamCounter] | None = PydanticField(None, alias='TeamCounters')
    individual_counters: list[IndividualCounter] | None = PydanticField(None, alias='IndividualCounters')
    inventory_counting_lines: list[InventoryCountingLine] | None = PydanticField(None, alias='InventoryCountingLines')
    inventory_counting_document_references_collection: list[InventoryCountingDocumentReferences] | None = PydanticField(None, alias='InventoryCountingDocumentReferencesCollection')
    business_place: BusinessPlace | None = PydanticField(None, alias='BusinessPlace')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')

class InventoryCountingDraft(B1Model):
    """SAP InventoryCountingDraft Entity"""
    document_entry: int | None = PydanticField(None, alias='DocumentEntry')
    document_number: int | None = PydanticField(None, alias='DocumentNumber')
    series: int | None = PydanticField(None, alias='Series')
    count_date: str | None = PydanticField(None, alias='CountDate')
    count_time: str | None = PydanticField(None, alias='CountTime')
    single_counter_type: CounterTypeEnum | Literal['ctUser', 'ctEmployee'] | None = PydanticField(None, alias='SingleCounterType')
    single_counter_id: int | None = PydanticField(None, alias='SingleCounterID')
    document_status: CountingDocumentStatusEnum | Literal['cdsOpen', 'cdsClosed'] | None = PydanticField(None, alias='DocumentStatus')
    remarks: str | None = PydanticField(None, alias='Remarks')
    reference2: str | None = PydanticField(None, alias='Reference2')
    branch_id: int | None = PydanticField(None, alias='BranchID')
    doc_object_code_ex: str | None = PydanticField(None, alias='DocObjectCodeEx')
    financial_period: int | None = PydanticField(None, alias='FinancialPeriod')
    period_indicator: str | None = PydanticField(None, alias='PeriodIndicator')
    counting_type: CountingTypeEnum | Literal['ctSingleCounter', 'ctMultipleCounters'] | None = PydanticField(None, alias='CountingType')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    year_end_date: str | None = PydanticField(None, alias='YearEndDate')
    business_place: BusinessPlace | None = PydanticField(None, alias='BusinessPlace')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')

class WarehouseSublevelCode(B1Model):
    """SAP WarehouseSublevelCode Entity"""
    abs_entry: int | None = PydanticField(None, alias='AbsEntry')
    warehouse_sublevel: int | None = PydanticField(None, alias='WarehouseSublevel')
    code: str | None = PydanticField(None, alias='Code')
    description: str | None = PydanticField(None, alias='Description')
    bin_location_field: BinLocationField | None = PydanticField(None, alias='BinLocationField')

class StockTransfer(B1Model):
    """SAP StockTransfer Entity"""
    doc_entry: int | None = PydanticField(None, alias='DocEntry')
    series: int | None = PydanticField(None, alias='Series')
    printed: SapBool | None = PydanticField(None, alias='Printed')
    doc_date: str | None = PydanticField(None, alias='DocDate')
    due_date: str | None = PydanticField(None, alias='DueDate')
    card_code: str | None = PydanticField(None, alias='CardCode')
    card_name: str | None = PydanticField(None, alias='CardName')
    address: str | None = PydanticField(None, alias='Address')
    reference1: str | None = PydanticField(None, alias='Reference1')
    reference2: str | None = PydanticField(None, alias='Reference2')
    comments: str | None = PydanticField(None, alias='Comments')
    journal_memo: str | None = PydanticField(None, alias='JournalMemo')
    price_list: int | None = PydanticField(None, alias='PriceList')
    sales_person_code: int | None = PydanticField(None, alias='SalesPersonCode')
    from_warehouse: str | None = PydanticField(None, alias='FromWarehouse')
    to_warehouse: str | None = PydanticField(None, alias='ToWarehouse')
    creation_date: str | None = PydanticField(None, alias='CreationDate')
    update_date: str | None = PydanticField(None, alias='UpdateDate')
    financial_period: int | None = PydanticField(None, alias='FinancialPeriod')
    trans_num: int | None = PydanticField(None, alias='TransNum')
    doc_num: int | None = PydanticField(None, alias='DocNum')
    tax_date: str | None = PydanticField(None, alias='TaxDate')
    contact_person: int | None = PydanticField(None, alias='ContactPerson')
    folio_prefix_string: str | None = PydanticField(None, alias='FolioPrefixString')
    folio_number: int | None = PydanticField(None, alias='FolioNumber')
    doc_object_code: str | None = PydanticField(None, alias='DocObjectCode')
    authorization_status: StockTransferAuthorizationStatusEnum | Literal['sasWithout', 'sasPending', 'sasApproved', 'sasRejected', 'sasGenerated', 'sasGeneratedbyAuthorizer', 'sasCancelled'] | None = PydanticField(None, alias='AuthorizationStatus')
    bplid: int | None = PydanticField(None, alias='BPLID')
    bpl_name: str | None = PydanticField(None, alias='BPLName')
    vat_reg_num: str | None = PydanticField(None, alias='VATRegNum')
    authorization_code: str | None = PydanticField(None, alias='AuthorizationCode')
    start_delivery_date: str | None = PydanticField(None, alias='StartDeliveryDate')
    start_delivery_time: str | None = PydanticField(None, alias='StartDeliveryTime')
    end_delivery_date: str | None = PydanticField(None, alias='EndDeliveryDate')
    end_delivery_time: str | None = PydanticField(None, alias='EndDeliveryTime')
    vehicle_plate: str | None = PydanticField(None, alias='VehiclePlate')
    at_document_type: str | None = PydanticField(None, alias='ATDocumentType')
    e_doc_export_format: int | None = PydanticField(None, alias='EDocExportFormat')
    elec_comm_status: ElecCommStatusEnum | Literal['ecsApproved', 'ecsPendingApproval', 'ecsRejected'] | None = PydanticField(None, alias='ElecCommStatus')
    elec_comm_message: str | None = PydanticField(None, alias='ElecCommMessage')
    point_of_issue_code: str | None = PydanticField(None, alias='PointOfIssueCode')
    letter: FolioLetterEnum | Literal['fLetterA', 'fLetterB', 'fLetterC', 'fLetterE', 'fLetterM', 'fLetterR', 'fLetterT', 'fLetterX', 'fLetterEMPTY'] | None = PydanticField(None, alias='Letter')
    folio_number_from: int | None = PydanticField(None, alias='FolioNumberFrom')
    folio_number_to: int | None = PydanticField(None, alias='FolioNumberTo')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    document_status: BoStatus | Literal['bost_Open', 'bost_Close', 'bost_Paid', 'bost_Delivered'] | None = PydanticField(None, alias='DocumentStatus')
    ship_to_code: str | None = PydanticField(None, alias='ShipToCode')
    sap_passport: str | None = PydanticField(None, alias='SAPPassport')
    last_page_folio_number: int | None = PydanticField(None, alias='LastPageFolioNumber')
    duty_status: SapBool | None = PydanticField(None, alias='DutyStatus')
    stock_transfer_approval_requests: list[StockTransfer_ApprovalRequest] | None = PydanticField(None, alias='StockTransfer_ApprovalRequests')
    electronic_protocols: list[ElectronicProtocol] | None = PydanticField(None, alias='ElectronicProtocols')
    stock_transfer_lines: list[StockTransferLine] | None = PydanticField(None, alias='StockTransferLines')
    stock_transfer_tax_extension: StockTransferTaxExtension | None = PydanticField(None, alias='StockTransferTaxExtension')
    document_references: list[DocumentReference] | None = PydanticField(None, alias='DocumentReferences')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')
    price_list2: PriceList | None = PydanticField(None, alias='PriceList2')
    sales_person: SalesPerson | None = PydanticField(None, alias='SalesPerson')
    warehouse: Warehouse | None = PydanticField(None, alias='Warehouse')
    journal_entry: JournalEntry | None = PydanticField(None, alias='JournalEntry')
    business_place: BusinessPlace | None = PydanticField(None, alias='BusinessPlace')
    payment_terms_type: PaymentTermsType | None = PydanticField(None, alias='PaymentTermsType')

class InventoryPosting(B1Model):
    """SAP InventoryPosting Entity"""
    document_entry: int | None = PydanticField(None, alias='DocumentEntry')
    document_number: int | None = PydanticField(None, alias='DocumentNumber')
    series: int | None = PydanticField(None, alias='Series')
    posting_date: str | None = PydanticField(None, alias='PostingDate')
    count_date: str | None = PydanticField(None, alias='CountDate')
    count_time: str | None = PydanticField(None, alias='CountTime')
    remarks: str | None = PydanticField(None, alias='Remarks')
    reference2: str | None = PydanticField(None, alias='Reference2')
    branch_id: int | None = PydanticField(None, alias='BranchID')
    price_source: InventoryPostingPriceSourceEnum | Literal['ippsByPriceList', 'ippsLastEvaluatedPrice', 'ippsItemCost'] | None = PydanticField(None, alias='PriceSource')
    price_list: int | None = PydanticField(None, alias='PriceList')
    journal_remark: str | None = PydanticField(None, alias='JournalRemark')
    doc_object_code_ex: str | None = PydanticField(None, alias='DocObjectCodeEx')
    financial_period: int | None = PydanticField(None, alias='FinancialPeriod')
    period_indicator: str | None = PydanticField(None, alias='PeriodIndicator')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    year_end_date: str | None = PydanticField(None, alias='YearEndDate')
    inventory_posting_lines: list[InventoryPostingLine] | None = PydanticField(None, alias='InventoryPostingLines')
    inventory_posting_document_references_collection: list[InventoryPostingDocumentReferences] | None = PydanticField(None, alias='InventoryPostingDocumentReferencesCollection')
    business_place: BusinessPlace | None = PydanticField(None, alias='BusinessPlace')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')

class MaterialRevaluation(B1Model):
    """SAP MaterialRevaluation Entity"""
    doc_entry: int | None = PydanticField(None, alias='DocEntry')
    doc_num: int | None = PydanticField(None, alias='DocNum')
    doc_date: str | None = PydanticField(None, alias='DocDate')
    reference1: str | None = PydanticField(None, alias='Reference1')
    reference2: str | None = PydanticField(None, alias='Reference2')
    comments: str | None = PydanticField(None, alias='Comments')
    journal_memo: str | None = PydanticField(None, alias='JournalMemo')
    doc_time: str | None = PydanticField(None, alias='DocTime')
    series: int | None = PydanticField(None, alias='Series')
    tax_date: str | None = PydanticField(None, alias='TaxDate')
    creation_date: str | None = PydanticField(None, alias='CreationDate')
    update_date: str | None = PydanticField(None, alias='UpdateDate')
    trans_num: int | None = PydanticField(None, alias='TransNum')
    reval_type: str | None = PydanticField(None, alias='RevalType')
    revaluation_income_account: str | None = PydanticField(None, alias='RevaluationIncomeAccount')
    revaluation_expense_account: str | None = PydanticField(None, alias='RevaluationExpenseAccount')
    data_source: str | None = PydanticField(None, alias='DataSource')
    user_signature: int | None = PydanticField(None, alias='UserSignature')
    inflation_revaluation: SapBool | None = PydanticField(None, alias='InflationRevaluation')
    card_code: str | None = PydanticField(None, alias='CardCode')
    card_name: str | None = PydanticField(None, alias='CardName')
    material_revaluation_lines: list[MaterialRevaluationLine] | None = PydanticField(None, alias='MaterialRevaluationLines')
    material_revaluation_document_references_collection: list[MaterialRevaluationDocumentReferences] | None = PydanticField(None, alias='MaterialRevaluationDocumentReferencesCollection')
    journal_entry: JournalEntry | None = PydanticField(None, alias='JournalEntry')
    user: User | None = PydanticField(None, alias='User')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')

class InventoryOpeningBalance(B1Model):
    """SAP InventoryOpeningBalance Entity"""
    document_entry: int | None = PydanticField(None, alias='DocumentEntry')
    posting_date: str | None = PydanticField(None, alias='PostingDate')
    document_date: str | None = PydanticField(None, alias='DocumentDate')
    document_number: int | None = PydanticField(None, alias='DocumentNumber')
    series: int | None = PydanticField(None, alias='Series')
    reference2: str | None = PydanticField(None, alias='Reference2')
    remarks: str | None = PydanticField(None, alias='Remarks')
    branch_id: int | None = PydanticField(None, alias='BranchID')
    price_source: InventoryOpeningBalancePriceSourceEnum | Literal['iobpsByPriceList', 'iobpsLastEvaluatedPrice', 'iobpsItemCost'] | None = PydanticField(None, alias='PriceSource')
    price_list: int | None = PydanticField(None, alias='PriceList')
    journal_remark: str | None = PydanticField(None, alias='JournalRemark')
    doc_object_code_ex: str | None = PydanticField(None, alias='DocObjectCodeEx')
    period_indicator: str | None = PydanticField(None, alias='PeriodIndicator')
    financial_period: int | None = PydanticField(None, alias='FinancialPeriod')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    inventory_opening_balance_lines: list[InventoryOpeningBalanceLine] | None = PydanticField(None, alias='InventoryOpeningBalanceLines')
    business_place: BusinessPlace | None = PydanticField(None, alias='BusinessPlace')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')

class WarehouseLocation(B1Model):
    """SAP WarehouseLocation Entity"""
    code: int | None = PydanticField(None, alias='Code')
    name: str | None = PydanticField(None, alias='Name')
    lstvat_number: str | None = PydanticField(None, alias='LSTVATNumber')
    cst_number: str | None = PydanticField(None, alias='CSTNumber')
    exemption_number: str | None = PydanticField(None, alias='ExemptionNumber')
    tan_number: str | None = PydanticField(None, alias='TANNumber')
    service_tax_number: str | None = PydanticField(None, alias='ServiceTaxNumber')
    assessee_type: str | None = PydanticField(None, alias='AssesseeType')
    company_type: str | None = PydanticField(None, alias='CompanyType')
    nature_of_business: str | None = PydanticField(None, alias='NatureOfBusiness')
    tin_number: str | None = PydanticField(None, alias='TINNumber')
    registration_type: str | None = PydanticField(None, alias='RegistrationType')
    ecc_number: str | None = PydanticField(None, alias='EccNumber')
    ce_range: str | None = PydanticField(None, alias='CERange')
    ce_division: str | None = PydanticField(None, alias='CEDivision')
    ce_commissionerate: str | None = PydanticField(None, alias='CECommissionerate')
    manufacturer_code: str | None = PydanticField(None, alias='ManufacturerCode')
    jurisdiction: str | None = PydanticField(None, alias='Jurisdiction')
    street: str | None = PydanticField(None, alias='Street')
    block: str | None = PydanticField(None, alias='Block')
    zip_code: str | None = PydanticField(None, alias='ZipCode')
    city: str | None = PydanticField(None, alias='City')
    county: str | None = PydanticField(None, alias='County')
    country: str | None = PydanticField(None, alias='Country')
    state: str | None = PydanticField(None, alias='State')
    pan_number: str | None = PydanticField(None, alias='PANNumber')
    ce_register_number: str | None = PydanticField(None, alias='CERegisterNumber')
    building_floor_room: str | None = PydanticField(None, alias='BuildingFloorRoom')
    gstin: str | None = PydanticField(None, alias='GSTIN')
    gst_type: BoGSTRegnTypeEnum | Literal['invalid', 'gstRegularTDSISD', 'gstCasualTaxablePerson', 'gstCompositionLevy', 'gstGoverDepartPSU', 'gstNonResidentTaxablePerson', 'gstUNAgencyEmbassy'] | None = PydanticField(None, alias='GstType')
    gsttds: str | None = PydanticField(None, alias='GSTTDS')
    gstisd: str | None = PydanticField(None, alias='GSTISD')
    warehouses: list[Warehouse] | None = PydanticField(None, alias='Warehouses')
    vendor_payments: list[Payment] | None = PydanticField(None, alias='VendorPayments')
    withholding_tax_codes: list[WithholdingTaxCode] | None = PydanticField(None, alias='WithholdingTaxCodes')
    journal_entries: list[JournalEntry] | None = PydanticField(None, alias='JournalEntries')
    country2: Country | None = PydanticField(None, alias='Country2')
    items: list[Item] | None = PydanticField(None, alias='Items')
    certificate_series: list[CertificateSeries] | None = PydanticField(None, alias='CertificateSeries')
    payment_drafts: list[Payment] | None = PydanticField(None, alias='PaymentDrafts')
    incoming_payments: list[Payment] | None = PydanticField(None, alias='IncomingPayments')

class Item(B1Model):
    """SAP Item Entity"""
    item_code: str | None = PydanticField(None, alias='ItemCode')
    item_name: str | None = PydanticField(None, alias='ItemName')
    foreign_name: str | None = PydanticField(None, alias='ForeignName')
    items_group_code: int | None = PydanticField(None, alias='ItemsGroupCode')
    customs_group_code: int | None = PydanticField(None, alias='CustomsGroupCode')
    sales_vat_group: str | None = PydanticField(None, alias='SalesVATGroup')
    bar_code: str | None = PydanticField(None, alias='BarCode')
    vat_liable: SapBool | None = PydanticField(None, alias='VatLiable')
    purchase_item: SapBool | None = PydanticField(None, alias='PurchaseItem')
    sales_item: SapBool | None = PydanticField(None, alias='SalesItem')
    inventory_item: SapBool | None = PydanticField(None, alias='InventoryItem')
    income_account: str | None = PydanticField(None, alias='IncomeAccount')
    exempt_income_account: str | None = PydanticField(None, alias='ExemptIncomeAccount')
    expanse_account: str | None = PydanticField(None, alias='ExpanseAccount')
    mainsupplier: str | None = PydanticField(None, alias='Mainsupplier')
    supplier_catalog_no: str | None = PydanticField(None, alias='SupplierCatalogNo')
    desired_inventory: float | None = PydanticField(None, alias='DesiredInventory')
    min_inventory: float | None = PydanticField(None, alias='MinInventory')
    picture: str | None = PydanticField(None, alias='Picture')
    user_text: str | None = PydanticField(None, alias='User_Text')
    serial_num: str | None = PydanticField(None, alias='SerialNum')
    commission_percent: float | None = PydanticField(None, alias='CommissionPercent')
    commission_sum: float | None = PydanticField(None, alias='CommissionSum')
    commission_group: int | None = PydanticField(None, alias='CommissionGroup')
    tree_type: BoItemTreeTypes | Literal['iNotATree', 'iAssemblyTree', 'iSalesTree', 'iProductionTree', 'iTemplateTree', 'iIngredient'] | None = PydanticField(None, alias='TreeType')
    asset_item: SapBool | None = PydanticField(None, alias='AssetItem')
    data_export_code: str | None = PydanticField(None, alias='DataExportCode')
    manufacturer: int | None = PydanticField(None, alias='Manufacturer')
    quantity_on_stock: float | None = PydanticField(None, alias='QuantityOnStock')
    quantity_ordered_from_vendors: float | None = PydanticField(None, alias='QuantityOrderedFromVendors')
    quantity_ordered_by_customers: float | None = PydanticField(None, alias='QuantityOrderedByCustomers')
    manage_serial_numbers: SapBool | None = PydanticField(None, alias='ManageSerialNumbers')
    manage_batch_numbers: SapBool | None = PydanticField(None, alias='ManageBatchNumbers')
    valid: SapBool | None = PydanticField(None, alias='Valid')
    valid_from: str | None = PydanticField(None, alias='ValidFrom')
    valid_to: str | None = PydanticField(None, alias='ValidTo')
    valid_remarks: str | None = PydanticField(None, alias='ValidRemarks')
    frozen: SapBool | None = PydanticField(None, alias='Frozen')
    frozen_from: str | None = PydanticField(None, alias='FrozenFrom')
    frozen_to: str | None = PydanticField(None, alias='FrozenTo')
    frozen_remarks: str | None = PydanticField(None, alias='FrozenRemarks')
    sales_unit: str | None = PydanticField(None, alias='SalesUnit')
    sales_items_per_unit: float | None = PydanticField(None, alias='SalesItemsPerUnit')
    sales_packaging_unit: str | None = PydanticField(None, alias='SalesPackagingUnit')
    sales_qty_per_pack_unit: float | None = PydanticField(None, alias='SalesQtyPerPackUnit')
    sales_unit_length: float | None = PydanticField(None, alias='SalesUnitLength')
    sales_length_unit: int | None = PydanticField(None, alias='SalesLengthUnit')
    sales_unit_width: float | None = PydanticField(None, alias='SalesUnitWidth')
    sales_width_unit: int | None = PydanticField(None, alias='SalesWidthUnit')
    sales_unit_height: float | None = PydanticField(None, alias='SalesUnitHeight')
    sales_height_unit: int | None = PydanticField(None, alias='SalesHeightUnit')
    sales_unit_volume: float | None = PydanticField(None, alias='SalesUnitVolume')
    sales_volume_unit: int | None = PydanticField(None, alias='SalesVolumeUnit')
    sales_unit_weight: float | None = PydanticField(None, alias='SalesUnitWeight')
    sales_weight_unit: int | None = PydanticField(None, alias='SalesWeightUnit')
    purchase_unit: str | None = PydanticField(None, alias='PurchaseUnit')
    purchase_items_per_unit: float | None = PydanticField(None, alias='PurchaseItemsPerUnit')
    purchase_packaging_unit: str | None = PydanticField(None, alias='PurchasePackagingUnit')
    purchase_qty_per_pack_unit: float | None = PydanticField(None, alias='PurchaseQtyPerPackUnit')
    purchase_unit_length: float | None = PydanticField(None, alias='PurchaseUnitLength')
    purchase_length_unit: int | None = PydanticField(None, alias='PurchaseLengthUnit')
    purchase_unit_width: float | None = PydanticField(None, alias='PurchaseUnitWidth')
    purchase_width_unit: int | None = PydanticField(None, alias='PurchaseWidthUnit')
    purchase_unit_height: float | None = PydanticField(None, alias='PurchaseUnitHeight')
    purchase_height_unit: int | None = PydanticField(None, alias='PurchaseHeightUnit')
    purchase_unit_volume: float | None = PydanticField(None, alias='PurchaseUnitVolume')
    purchase_volume_unit: int | None = PydanticField(None, alias='PurchaseVolumeUnit')
    purchase_unit_weight: float | None = PydanticField(None, alias='PurchaseUnitWeight')
    purchase_weight_unit: int | None = PydanticField(None, alias='PurchaseWeightUnit')
    purchase_vat_group: str | None = PydanticField(None, alias='PurchaseVATGroup')
    sales_factor1: float | None = PydanticField(None, alias='SalesFactor1')
    sales_factor2: float | None = PydanticField(None, alias='SalesFactor2')
    sales_factor3: float | None = PydanticField(None, alias='SalesFactor3')
    sales_factor4: float | None = PydanticField(None, alias='SalesFactor4')
    purchase_factor1: float | None = PydanticField(None, alias='PurchaseFactor1')
    purchase_factor2: float | None = PydanticField(None, alias='PurchaseFactor2')
    purchase_factor3: float | None = PydanticField(None, alias='PurchaseFactor3')
    purchase_factor4: float | None = PydanticField(None, alias='PurchaseFactor4')
    moving_average_price: float | None = PydanticField(None, alias='MovingAveragePrice')
    foreign_revenues_account: str | None = PydanticField(None, alias='ForeignRevenuesAccount')
    ec_revenues_account: str | None = PydanticField(None, alias='ECRevenuesAccount')
    foreign_expenses_account: str | None = PydanticField(None, alias='ForeignExpensesAccount')
    ec_expenses_account: str | None = PydanticField(None, alias='ECExpensesAccount')
    avg_std_price: float | None = PydanticField(None, alias='AvgStdPrice')
    default_warehouse: str | None = PydanticField(None, alias='DefaultWarehouse')
    ship_type: int | None = PydanticField(None, alias='ShipType')
    gl_method: BoGLMethods | Literal['glm_WH', 'glm_ItemClass', 'glm_ItemLevel'] | None = PydanticField(None, alias='GLMethod')
    tax_type: BoTaxTypes | Literal['tt_Yes', 'tt_No', 'tt_UseTax', 'tt_OffsetTax'] | None = PydanticField(None, alias='TaxType')
    max_inventory: float | None = PydanticField(None, alias='MaxInventory')
    manage_stock_by_warehouse: SapBool | None = PydanticField(None, alias='ManageStockByWarehouse')
    purchase_height_unit1: int | None = PydanticField(None, alias='PurchaseHeightUnit1')
    purchase_unit_height1: float | None = PydanticField(None, alias='PurchaseUnitHeight1')
    purchase_length_unit1: int | None = PydanticField(None, alias='PurchaseLengthUnit1')
    purchase_unit_length1: float | None = PydanticField(None, alias='PurchaseUnitLength1')
    purchase_weight_unit1: int | None = PydanticField(None, alias='PurchaseWeightUnit1')
    purchase_unit_weight1: float | None = PydanticField(None, alias='PurchaseUnitWeight1')
    purchase_width_unit1: int | None = PydanticField(None, alias='PurchaseWidthUnit1')
    purchase_unit_width1: float | None = PydanticField(None, alias='PurchaseUnitWidth1')
    sales_height_unit1: int | None = PydanticField(None, alias='SalesHeightUnit1')
    sales_unit_height1: float | None = PydanticField(None, alias='SalesUnitHeight1')
    sales_length_unit1: int | None = PydanticField(None, alias='SalesLengthUnit1')
    sales_unit_length1: float | None = PydanticField(None, alias='SalesUnitLength1')
    sales_weight_unit1: int | None = PydanticField(None, alias='SalesWeightUnit1')
    sales_unit_weight1: float | None = PydanticField(None, alias='SalesUnitWeight1')
    sales_width_unit1: int | None = PydanticField(None, alias='SalesWidthUnit1')
    sales_unit_width1: float | None = PydanticField(None, alias='SalesUnitWidth1')
    force_selection_of_serial_number: SapBool | None = PydanticField(None, alias='ForceSelectionOfSerialNumber')
    manage_serial_numbers_on_release_only: SapBool | None = PydanticField(None, alias='ManageSerialNumbersOnReleaseOnly')
    wt_liable: SapBool | None = PydanticField(None, alias='WTLiable')
    cost_accounting_method: BoInventorySystem | Literal['bis_MovingAverage', 'bis_Standard', 'bis_FIFO', 'bis_SNB'] | None = PydanticField(None, alias='CostAccountingMethod')
    sww: str | None = PydanticField(None, alias='SWW')
    warranty_template: str | None = PydanticField(None, alias='WarrantyTemplate')
    indirect_tax: SapBool | None = PydanticField(None, alias='IndirectTax')
    ar_tax_code: str | None = PydanticField(None, alias='ArTaxCode')
    ap_tax_code: str | None = PydanticField(None, alias='ApTaxCode')
    base_unit_name: str | None = PydanticField(None, alias='BaseUnitName')
    item_country_org: str | None = PydanticField(None, alias='ItemCountryOrg')
    issue_method: BoIssueMethod | Literal['im_Backflush', 'im_Manual'] | None = PydanticField(None, alias='IssueMethod')
    sri_and_batch_manage_method: BoManageMethod | Literal['bomm_OnEveryTransaction', 'bomm_OnReleaseOnly'] | None = PydanticField(None, alias='SRIAndBatchManageMethod')
    is_phantom: SapBool | None = PydanticField(None, alias='IsPhantom')
    inventory_uom: str | None = PydanticField(None, alias='InventoryUOM')
    planning_system: BoPlanningSystem | Literal['bop_MRP', 'bop_None'] | None = PydanticField(None, alias='PlanningSystem')
    procurement_method: BoProcurementMethod | Literal['bom_Buy', 'bom_Make'] | None = PydanticField(None, alias='ProcurementMethod')
    component_warehouse: BoMRPComponentWarehouse | Literal['bomcw_BOM', 'bomcw_Parent'] | None = PydanticField(None, alias='ComponentWarehouse')
    order_intervals: int | None = PydanticField(None, alias='OrderIntervals')
    order_multiple: float | None = PydanticField(None, alias='OrderMultiple')
    lead_time: int | None = PydanticField(None, alias='LeadTime')
    min_order_quantity: float | None = PydanticField(None, alias='MinOrderQuantity')
    item_type: ItemTypeEnum | Literal['itItems', 'itLabor', 'itTravel', 'itFixedAssets'] | None = PydanticField(None, alias='ItemType')
    item_class: ItemClassEnum | Literal['itcService', 'itcMaterial'] | None = PydanticField(None, alias='ItemClass')
    outgoing_service_code: int | None = PydanticField(None, alias='OutgoingServiceCode')
    incoming_service_code: int | None = PydanticField(None, alias='IncomingServiceCode')
    service_group: int | None = PydanticField(None, alias='ServiceGroup')
    ncm_code: int | None = PydanticField(None, alias='NCMCode')
    material_type: BoMaterialTypes | Literal['mt_GoodsForReseller', 'mt_FinishedGoods', 'mt_GoodsInProcess', 'mt_RawMaterial', 'mt_Package', 'mt_SubProduct', 'mt_IntermediateMaterial', 'mt_ConsumerMaterial', 'mt_FixedAsset', 'mt_Service', 'mt_OtherInput', 'mt_Other'] | None = PydanticField(None, alias='MaterialType')
    material_group: int | None = PydanticField(None, alias='MaterialGroup')
    product_source: str | None = PydanticField(None, alias='ProductSource')
    properties1: SapBool | None = PydanticField(None, alias='Properties1')
    properties2: SapBool | None = PydanticField(None, alias='Properties2')
    properties3: SapBool | None = PydanticField(None, alias='Properties3')
    properties4: SapBool | None = PydanticField(None, alias='Properties4')
    properties5: SapBool | None = PydanticField(None, alias='Properties5')
    properties6: SapBool | None = PydanticField(None, alias='Properties6')
    properties7: SapBool | None = PydanticField(None, alias='Properties7')
    properties8: SapBool | None = PydanticField(None, alias='Properties8')
    properties9: SapBool | None = PydanticField(None, alias='Properties9')
    properties10: SapBool | None = PydanticField(None, alias='Properties10')
    properties11: SapBool | None = PydanticField(None, alias='Properties11')
    properties12: SapBool | None = PydanticField(None, alias='Properties12')
    properties13: SapBool | None = PydanticField(None, alias='Properties13')
    properties14: SapBool | None = PydanticField(None, alias='Properties14')
    properties15: SapBool | None = PydanticField(None, alias='Properties15')
    properties16: SapBool | None = PydanticField(None, alias='Properties16')
    properties17: SapBool | None = PydanticField(None, alias='Properties17')
    properties18: SapBool | None = PydanticField(None, alias='Properties18')
    properties19: SapBool | None = PydanticField(None, alias='Properties19')
    properties20: SapBool | None = PydanticField(None, alias='Properties20')
    properties21: SapBool | None = PydanticField(None, alias='Properties21')
    properties22: SapBool | None = PydanticField(None, alias='Properties22')
    properties23: SapBool | None = PydanticField(None, alias='Properties23')
    properties24: SapBool | None = PydanticField(None, alias='Properties24')
    properties25: SapBool | None = PydanticField(None, alias='Properties25')
    properties26: SapBool | None = PydanticField(None, alias='Properties26')
    properties27: SapBool | None = PydanticField(None, alias='Properties27')
    properties28: SapBool | None = PydanticField(None, alias='Properties28')
    properties29: SapBool | None = PydanticField(None, alias='Properties29')
    properties30: SapBool | None = PydanticField(None, alias='Properties30')
    properties31: SapBool | None = PydanticField(None, alias='Properties31')
    properties32: SapBool | None = PydanticField(None, alias='Properties32')
    properties33: SapBool | None = PydanticField(None, alias='Properties33')
    properties34: SapBool | None = PydanticField(None, alias='Properties34')
    properties35: SapBool | None = PydanticField(None, alias='Properties35')
    properties36: SapBool | None = PydanticField(None, alias='Properties36')
    properties37: SapBool | None = PydanticField(None, alias='Properties37')
    properties38: SapBool | None = PydanticField(None, alias='Properties38')
    properties39: SapBool | None = PydanticField(None, alias='Properties39')
    properties40: SapBool | None = PydanticField(None, alias='Properties40')
    properties41: SapBool | None = PydanticField(None, alias='Properties41')
    properties42: SapBool | None = PydanticField(None, alias='Properties42')
    properties43: SapBool | None = PydanticField(None, alias='Properties43')
    properties44: SapBool | None = PydanticField(None, alias='Properties44')
    properties45: SapBool | None = PydanticField(None, alias='Properties45')
    properties46: SapBool | None = PydanticField(None, alias='Properties46')
    properties47: SapBool | None = PydanticField(None, alias='Properties47')
    properties48: SapBool | None = PydanticField(None, alias='Properties48')
    properties49: SapBool | None = PydanticField(None, alias='Properties49')
    properties50: SapBool | None = PydanticField(None, alias='Properties50')
    properties51: SapBool | None = PydanticField(None, alias='Properties51')
    properties52: SapBool | None = PydanticField(None, alias='Properties52')
    properties53: SapBool | None = PydanticField(None, alias='Properties53')
    properties54: SapBool | None = PydanticField(None, alias='Properties54')
    properties55: SapBool | None = PydanticField(None, alias='Properties55')
    properties56: SapBool | None = PydanticField(None, alias='Properties56')
    properties57: SapBool | None = PydanticField(None, alias='Properties57')
    properties58: SapBool | None = PydanticField(None, alias='Properties58')
    properties59: SapBool | None = PydanticField(None, alias='Properties59')
    properties60: SapBool | None = PydanticField(None, alias='Properties60')
    properties61: SapBool | None = PydanticField(None, alias='Properties61')
    properties62: SapBool | None = PydanticField(None, alias='Properties62')
    properties63: SapBool | None = PydanticField(None, alias='Properties63')
    properties64: SapBool | None = PydanticField(None, alias='Properties64')
    auto_create_serial_numbers_on_release: SapBool | None = PydanticField(None, alias='AutoCreateSerialNumbersOnRelease')
    dnf_entry: int | None = PydanticField(None, alias='DNFEntry')
    gts_item_spec: str | None = PydanticField(None, alias='GTSItemSpec')
    gts_item_tax_category: str | None = PydanticField(None, alias='GTSItemTaxCategory')
    fuel_id: int | None = PydanticField(None, alias='FuelID')
    beverage_table_code: str | None = PydanticField(None, alias='BeverageTableCode')
    beverage_group_code: str | None = PydanticField(None, alias='BeverageGroupCode')
    beverage_commercial_brand_code: int | None = PydanticField(None, alias='BeverageCommercialBrandCode')
    series: int | None = PydanticField(None, alias='Series')
    tolerance_days: int | None = PydanticField(None, alias='ToleranceDays')
    type_of_advanced_rules: TypeOfAdvancedRulesEnum | Literal['toarGeneral', 'toarWarehouse', 'toarItemGroup'] | None = PydanticField(None, alias='TypeOfAdvancedRules')
    issue_primarily_by: IssuePrimarilyByEnum | Literal['ipbSerialAndBatchNumbers', 'ipbBinLocations'] | None = PydanticField(None, alias='IssuePrimarilyBy')
    no_discounts: SapBool | None = PydanticField(None, alias='NoDiscounts')
    asset_class: str | None = PydanticField(None, alias='AssetClass')
    asset_group: str | None = PydanticField(None, alias='AssetGroup')
    inventory_number: str | None = PydanticField(None, alias='InventoryNumber')
    technician: int | None = PydanticField(None, alias='Technician')
    employee: int | None = PydanticField(None, alias='Employee')
    location: int | None = PydanticField(None, alias='Location')
    asset_status: AssetStatusEnum | Literal['New', 'Active', 'Inactive'] | None = PydanticField(None, alias='AssetStatus')
    capitalization_date: str | None = PydanticField(None, alias='CapitalizationDate')
    statistical_asset: SapBool | None = PydanticField(None, alias='StatisticalAsset')
    cession: SapBool | None = PydanticField(None, alias='Cession')
    deactivate_after_useful_life: SapBool | None = PydanticField(None, alias='DeactivateAfterUsefulLife')
    manage_by_quantity: SapBool | None = PydanticField(None, alias='ManageByQuantity')
    uo_m_group_entry: int | None = PydanticField(None, alias='UoMGroupEntry')
    inventory_uo_m_entry: int | None = PydanticField(None, alias='InventoryUoMEntry')
    default_sales_uo_m_entry: int | None = PydanticField(None, alias='DefaultSalesUoMEntry')
    default_purchasing_uo_m_entry: int | None = PydanticField(None, alias='DefaultPurchasingUoMEntry')
    depreciation_group: str | None = PydanticField(None, alias='DepreciationGroup')
    asset_serial_number: str | None = PydanticField(None, alias='AssetSerialNumber')
    inventory_weight: float | None = PydanticField(None, alias='InventoryWeight')
    inventory_weight_unit: int | None = PydanticField(None, alias='InventoryWeightUnit')
    inventory_weight1: float | None = PydanticField(None, alias='InventoryWeight1')
    inventory_weight_unit1: int | None = PydanticField(None, alias='InventoryWeightUnit1')
    default_counting_unit: str | None = PydanticField(None, alias='DefaultCountingUnit')
    counting_items_per_unit: float | None = PydanticField(None, alias='CountingItemsPerUnit')
    default_counting_uo_m_entry: int | None = PydanticField(None, alias='DefaultCountingUoMEntry')
    excisable: SapBool | None = PydanticField(None, alias='Excisable')
    chapter_id: int | None = PydanticField(None, alias='ChapterID')
    scs_code: str | None = PydanticField(None, alias='ScsCode')
    sp_prod_type: SpecialProductTypeEnum | Literal['sptMT', 'sptIO'] | None = PydanticField(None, alias='SpProdType')
    prod_std_cost: float | None = PydanticField(None, alias='ProdStdCost')
    in_cost_rollup: SapBool | None = PydanticField(None, alias='InCostRollup')
    virtual_asset_item: SapBool | None = PydanticField(None, alias='VirtualAssetItem')
    enforce_asset_serial_numbers: SapBool | None = PydanticField(None, alias='EnforceAssetSerialNumbers')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    linked_resource: str | None = PydanticField(None, alias='LinkedResource')
    update_date: str | None = PydanticField(None, alias='UpdateDate')
    update_time: str | None = PydanticField(None, alias='UpdateTime')
    gst_relevnt: SapBool | None = PydanticField(None, alias='GSTRelevnt')
    sac_entry: int | None = PydanticField(None, alias='SACEntry')
    gst_tax_category: GSTTaxCategoryEnum | Literal['gtc_Regular', 'gtc_NilRated', 'gtc_Exempt'] | None = PydanticField(None, alias='GSTTaxCategory')
    service_category_entry: int | None = PydanticField(None, alias='ServiceCategoryEntry')
    capital_goods_on_hold_percent: float | None = PydanticField(None, alias='CapitalGoodsOnHoldPercent')
    capital_goods_on_hold_limit: float | None = PydanticField(None, alias='CapitalGoodsOnHoldLimit')
    assessable_value: float | None = PydanticField(None, alias='AssessableValue')
    ass_val4_wtr: float | None = PydanticField(None, alias='AssVal4WTR')
    soi_excisable: SOIExcisableTypeEnum | Literal['se_Excisable', 'se_Exemption', 'se_PaidToOther', 'se_NotExcisable'] | None = PydanticField(None, alias='SOIExcisable')
    tnved: str | None = PydanticField(None, alias='TNVED')
    imported_item: SapBool | None = PydanticField(None, alias='ImportedItem')
    pricing_unit: int | None = PydanticField(None, alias='PricingUnit')
    create_date: str | None = PydanticField(None, alias='CreateDate')
    create_time: str | None = PydanticField(None, alias='CreateTime')
    nve_code: str | None = PydanticField(None, alias='NVECode')
    ctr_seal_qty: float | None = PydanticField(None, alias='CtrSealQty')
    legal_text: str | None = PydanticField(None, alias='LegalText')
    data_version: int | None = PydanticField(None, alias='DataVersion')
    create_qr_code_from: str | None = PydanticField(None, alias='CreateQRCodeFrom')
    traceable_item: SapBool | None = PydanticField(None, alias='TraceableItem')
    commodity_classification: int | None = PydanticField(None, alias='CommodityClassification')
    weight_of_recycled_plastic: float | None = PydanticField(None, alias='WeightOfRecycledPlastic')
    plastic_package_tax_category: str | None = PydanticField(None, alias='PlasticPackageTaxCategory')
    plastic_package_exemption_reason_for_purchase: str | None = PydanticField(None, alias='PlasticPackageExemptionReasonForPurchase')
    plastic_package_exemption_reason_for_production: str | None = PydanticField(None, alias='PlasticPackageExemptionReasonForProduction')
    saft_product_type: SAFTProductTypeEnum | Literal['saftpt_Products', 'saftpt_Services', 'saftpt_Other', 'saftpt_Taxes', 'saftpt_NonSystem'] | None = PydanticField(None, alias='SAFTProductType')
    saft_product_type_ex: str | None = PydanticField(None, alias='SAFTProductTypeEx')
    item_prices: list[ItemPrice] | None = PydanticField(None, alias='ItemPrices')
    item_warehouse_info_collection: list[ItemWarehouseInfo] | None = PydanticField(None, alias='ItemWarehouseInfoCollection')
    item_preferred_vendors: list[ItemPreferredVendor] | None = PydanticField(None, alias='ItemPreferredVendors')
    item_localization_infos: list[ItemLocalizationInfo] | None = PydanticField(None, alias='ItemLocalizationInfos')
    item_projects: list[ItemProject] | None = PydanticField(None, alias='ItemProjects')
    item_distribution_rules: list[ItemDistributionRule] | None = PydanticField(None, alias='ItemDistributionRules')
    item_attribute_groups: list[ItemAttributeGroups] | None = PydanticField(None, alias='ItemAttributeGroups')
    item_depreciation_parameters: list[ItemDepreciationParameter] | None = PydanticField(None, alias='ItemDepreciationParameters')
    item_period_controls: list[ItemPeriodControl] | None = PydanticField(None, alias='ItemPeriodControls')
    item_unit_of_measurement_collection: list[ItemUnitOfMeasurement] | None = PydanticField(None, alias='ItemUnitOfMeasurementCollection')
    item_bar_code_collection: list[ItemBarCode] | None = PydanticField(None, alias='ItemBarCodeCollection')
    item_intrastat_extension: ItemIntrastatExtension | None = PydanticField(None, alias='ItemIntrastatExtension')
    product_trees: list[ProductTree] | None = PydanticField(None, alias='ProductTrees')
    customer_equipment_cards: list[CustomerEquipmentCard] | None = PydanticField(None, alias='CustomerEquipmentCards')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')
    item_groups: ItemGroups | None = PydanticField(None, alias='ItemGroups')
    customs_group: CustomsGroup | None = PydanticField(None, alias='CustomsGroup')
    vat_group: VatGroup | None = PydanticField(None, alias='VatGroup')
    chart_of_account: ChartOfAccount | None = PydanticField(None, alias='ChartOfAccount')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')
    commission_group2: CommissionGroup | None = PydanticField(None, alias='CommissionGroup2')
    manufacturer2: Manufacturer | None = PydanticField(None, alias='Manufacturer2')
    shipping_type: ShippingType | None = PydanticField(None, alias='ShippingType')
    contract_template: ContractTemplate | None = PydanticField(None, alias='ContractTemplate')
    sales_tax_code: SalesTaxCode | None = PydanticField(None, alias='SalesTaxCode')
    inventory_cycles: InventoryCycles | None = PydanticField(None, alias='InventoryCycles')
    service_group2: ServiceGroup | None = PydanticField(None, alias='ServiceGroup2')
    ncm_code_setup: NCMCodeSetup | None = PydanticField(None, alias='NCMCodeSetup')
    material_group2: MaterialGroup | None = PydanticField(None, alias='MaterialGroup2')
    dnf_code_setup: DNFCodeSetup | None = PydanticField(None, alias='DNFCodeSetup')
    brazil_fuel_indexer: BrazilFuelIndexer | None = PydanticField(None, alias='BrazilFuelIndexer')
    brazil_string_indexer: BrazilStringIndexer | None = PydanticField(None, alias='BrazilStringIndexer')
    brazil_numeric_indexer: BrazilNumericIndexer | None = PydanticField(None, alias='BrazilNumericIndexer')
    asset_class2: AssetClass | None = PydanticField(None, alias='AssetClass2')
    asset_group2: AssetGroup | None = PydanticField(None, alias='AssetGroup2')
    employee_info: EmployeeInfo | None = PydanticField(None, alias='EmployeeInfo')
    warehouse_location: WarehouseLocation | None = PydanticField(None, alias='WarehouseLocation')
    unit_of_measurement_group: UnitOfMeasurementGroup | None = PydanticField(None, alias='UnitOfMeasurementGroup')
    unit_of_measurement: UnitOfMeasurement | None = PydanticField(None, alias='UnitOfMeasurement')
    asset_depreciation_group: AssetDepreciationGroup | None = PydanticField(None, alias='AssetDepreciationGroup')
    india_hsn: IndiaHsn | None = PydanticField(None, alias='IndiaHsn')
    resource: Resource | None = PydanticField(None, alias='Resource')
    india_sac_code: IndiaSacCode | None = PydanticField(None, alias='IndiaSacCode')
    identification_code: IdentificationCode | None = PydanticField(None, alias='IdentificationCode')
    bin_locations: list[BinLocation] | None = PydanticField(None, alias='BinLocations')
    alternate_cat_num: list[AlternateCatNum] | None = PydanticField(None, alias='AlternateCatNum')
    gl_account_advanced_rules: list[GLAccountAdvancedRule] | None = PydanticField(None, alias='GLAccountAdvancedRules')
    bar_codes: list[BarCode] | None = PydanticField(None, alias='BarCodes')
    resources: list[Resource] | None = PydanticField(None, alias='Resources')
    knowledge_base_solutions: list[KnowledgeBaseSolution] | None = PydanticField(None, alias='KnowledgeBaseSolutions')
    depreciation_areas: list[DepreciationArea] | None = PydanticField(None, alias='DepreciationAreas')
    special_prices: list[SpecialPrice] | None = PydanticField(None, alias='SpecialPrices')
    serial_number_details: list[SerialNumberDetail] | None = PydanticField(None, alias='SerialNumberDetails')
    batch_number_details: list[BatchNumberDetail] | None = PydanticField(None, alias='BatchNumberDetails')
    stock_takings: list[StockTaking] | None = PydanticField(None, alias='StockTakings')

class ItemGroups(B1Model):
    """SAP ItemGroups Entity"""
    number: int | None = PydanticField(None, alias='Number')
    price_differences_account: str | None = PydanticField(None, alias='PriceDifferencesAccount')
    stock_inflation_adjust_account: str | None = PydanticField(None, alias='StockInflationAdjustAccount')
    minimum_order_quantity: float | None = PydanticField(None, alias='MinimumOrderQuantity')
    order_interval: int | None = PydanticField(None, alias='OrderInterval')
    exchange_rate_differences_account: str | None = PydanticField(None, alias='ExchangeRateDifferencesAccount')
    increasing_account: str | None = PydanticField(None, alias='IncreasingAccount')
    stock_inflation_offset_account: str | None = PydanticField(None, alias='StockInflationOffsetAccount')
    procurement_method: BoProcurementMethod | Literal['bom_Buy', 'bom_Make'] | None = PydanticField(None, alias='ProcurementMethod')
    component_warehouse: BoMRPComponentWarehouse | Literal['bomcw_BOM', 'bomcw_Parent'] | None = PydanticField(None, alias='ComponentWarehouse')
    purchase_offset_account: str | None = PydanticField(None, alias='PurchaseOffsetAccount')
    inventory_system: BoInventorySystem | Literal['bis_MovingAverage', 'bis_Standard', 'bis_FIFO', 'bis_SNB'] | None = PydanticField(None, alias='InventorySystem')
    wip_material_variance_account: str | None = PydanticField(None, alias='WIPMaterialVarianceAccount')
    planning_system: BoPlanningSystem | Literal['bop_MRP', 'bop_None'] | None = PydanticField(None, alias='PlanningSystem')
    purchase_account: str | None = PydanticField(None, alias='PurchaseAccount')
    returning_account: str | None = PydanticField(None, alias='ReturningAccount')
    cost_inflation_account: str | None = PydanticField(None, alias='CostInflationAccount')
    expenses_account: str | None = PydanticField(None, alias='ExpensesAccount')
    revenues_account: str | None = PydanticField(None, alias='RevenuesAccount')
    transfers_account: str | None = PydanticField(None, alias='TransfersAccount')
    lead_time: int | None = PydanticField(None, alias='LeadTime')
    order_multiple: float | None = PydanticField(None, alias='OrderMultiple')
    cost_inflation_offset_account: str | None = PydanticField(None, alias='CostInflationOffsetAccount')
    inventory_account: str | None = PydanticField(None, alias='InventoryAccount')
    decrease_gl_account: str | None = PydanticField(None, alias='DecreaseGLAccount')
    goods_clearing_account: str | None = PydanticField(None, alias='GoodsClearingAccount')
    increase_gl_account: str | None = PydanticField(None, alias='IncreaseGLAccount')
    foreign_revenues_account: str | None = PydanticField(None, alias='ForeignRevenuesAccount')
    alert: SapBool | None = PydanticField(None, alias='Alert')
    wip_material_account: str | None = PydanticField(None, alias='WIPMaterialAccount')
    shipped_goods_account: str | None = PydanticField(None, alias='ShippedGoodsAccount')
    exempt_revenues_account: str | None = PydanticField(None, alias='ExemptRevenuesAccount')
    decreasing_account: str | None = PydanticField(None, alias='DecreasingAccount')
    vat_in_revenue_account: str | None = PydanticField(None, alias='VATInRevenueAccount')
    variance_account: str | None = PydanticField(None, alias='VarianceAccount')
    eu_expenses_account: str | None = PydanticField(None, alias='EUExpensesAccount')
    foreign_expenses_account: str | None = PydanticField(None, alias='ForeignExpensesAccount')
    cycle_code: int | None = PydanticField(None, alias='CycleCode')
    cost_account: str | None = PydanticField(None, alias='CostAccount')
    pa_return_account: str | None = PydanticField(None, alias='PAReturnAccount')
    group_name: str | None = PydanticField(None, alias='GroupName')
    expense_clearing_act: str | None = PydanticField(None, alias='ExpenseClearingAct')
    purchase_credit_acc: str | None = PydanticField(None, alias='PurchaseCreditAcc')
    eu_purchase_credit_acc: str | None = PydanticField(None, alias='EUPurchaseCreditAcc')
    foreign_purchase_credit_acc: str | None = PydanticField(None, alias='ForeignPurchaseCreditAcc')
    sales_credit_acc: str | None = PydanticField(None, alias='SalesCreditAcc')
    sales_credit_eu_acc: str | None = PydanticField(None, alias='SalesCreditEUAcc')
    exempted_credits: str | None = PydanticField(None, alias='ExemptedCredits')
    sales_credit_foreign_acc: str | None = PydanticField(None, alias='SalesCreditForeignAcc')
    expense_offset_account: str | None = PydanticField(None, alias='ExpenseOffsetAccount')
    negative_inventory_adjustment_account: str | None = PydanticField(None, alias='NegativeInventoryAdjustmentAccount')
    wh_incoming_cenvat_account: str | None = PydanticField(None, alias='WHIncomingCenvatAccount')
    wh_outgoing_cenvat_account: str | None = PydanticField(None, alias='WHOutgoingCenvatAccount')
    stock_in_transit_account: str | None = PydanticField(None, alias='StockInTransitAccount')
    wip_offset_profit_and_loss_account: str | None = PydanticField(None, alias='WipOffsetProfitAndLossAccount')
    inventory_offset_profit_and_loss_account: str | None = PydanticField(None, alias='InventoryOffsetProfitAndLossAccount')
    tolerance_days: int | None = PydanticField(None, alias='ToleranceDays')
    default_uo_m_group: int | None = PydanticField(None, alias='DefaultUoMGroup')
    default_inventory_uo_m: int | None = PydanticField(None, alias='DefaultInventoryUoM')
    purchase_balance_account: str | None = PydanticField(None, alias='PurchaseBalanceAccount')
    item_class: ItemClassEnum | Literal['itcService', 'itcMaterial'] | None = PydanticField(None, alias='ItemClass')
    raw_material: SapBool | None = PydanticField(None, alias='RawMaterial')
    item_groups_warehouse_infos: list[ItemGroupsWarehouseInfo] | None = PydanticField(None, alias='ItemGroupsWarehouseInfos')
    chart_of_account: ChartOfAccount | None = PydanticField(None, alias='ChartOfAccount')
    inventory_cycles: InventoryCycles | None = PydanticField(None, alias='InventoryCycles')
    unit_of_measurement_group: UnitOfMeasurementGroup | None = PydanticField(None, alias='UnitOfMeasurementGroup')
    unit_of_measurement: UnitOfMeasurement | None = PydanticField(None, alias='UnitOfMeasurement')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')
    items: list[Item] | None = PydanticField(None, alias='Items')
    bin_locations: list[BinLocation] | None = PydanticField(None, alias='BinLocations')
    gl_account_advanced_rules: list[GLAccountAdvancedRule] | None = PydanticField(None, alias='GLAccountAdvancedRules')

class ItemImage(B1Model):
    """SAP ItemImage Entity"""
    item_code: str | None = PydanticField(None, alias='ItemCode')
    picture: str | None = PydanticField(None, alias='Picture')
