from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import Field as PydanticField

from b1sl.b1sl.models.base import B1Model, SapBool

from ..complex_types import *
from ..enums import *

if TYPE_CHECKING:
    from .._types import *
    from .businesspartners import *
    from .finance import *
    from .general import *
    from .inventory import *

class ProductTree(B1Model):
    """SAP ProductTree Entity"""
    tree_code: str | None = PydanticField(None, alias='TreeCode')
    tree_type: BoItemTreeTypes | None = PydanticField(None, alias='TreeType')
    quantity: float | None = PydanticField(None, alias='Quantity')
    distribution_rule: str | None = PydanticField(None, alias='DistributionRule')
    project: str | None = PydanticField(None, alias='Project')
    distribution_rule2: str | None = PydanticField(None, alias='DistributionRule2')
    distribution_rule3: str | None = PydanticField(None, alias='DistributionRule3')
    distribution_rule4: str | None = PydanticField(None, alias='DistributionRule4')
    distribution_rule5: str | None = PydanticField(None, alias='DistributionRule5')
    price_list: int | None = PydanticField(None, alias='PriceList')
    warehouse: str | None = PydanticField(None, alias='Warehouse')
    plan_avg_prod_size: float | None = PydanticField(None, alias='PlanAvgProdSize')
    hide_bom_components_in_printout: SapBool | None = PydanticField(None, alias='HideBOMComponentsInPrintout')
    product_description: str | None = PydanticField(None, alias='ProductDescription')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    product_tree_lines: list[ProductTreeLine] | None = PydanticField(None, alias='ProductTreeLines')
    product_tree_stages: list[ProductTreeStage] | None = PydanticField(None, alias='ProductTreeStages')
    item: Item | None = PydanticField(None, alias='Item')
    distribution_rule6: DistributionRule | None = PydanticField(None, alias='DistributionRule6')
    project2: Project | None = PydanticField(None, alias='Project2')
    price_list2: PriceList | None = PydanticField(None, alias='PriceList2')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')
    production_orders: list[ProductionOrder] | None = PydanticField(None, alias='ProductionOrders')

class ProductionOrder(B1Model):
    """SAP ProductionOrder Entity"""
    absolute_entry: int | None = PydanticField(None, alias='AbsoluteEntry')
    document_number: int | None = PydanticField(None, alias='DocumentNumber')
    series: int | None = PydanticField(None, alias='Series')
    item_no: str | None = PydanticField(None, alias='ItemNo')
    production_order_status: BoProductionOrderStatusEnum | None = PydanticField(None, alias='ProductionOrderStatus')
    production_order_type: BoProductionOrderTypeEnum | None = PydanticField(None, alias='ProductionOrderType')
    planned_quantity: float | None = PydanticField(None, alias='PlannedQuantity')
    completed_quantity: float | None = PydanticField(None, alias='CompletedQuantity')
    rejected_quantity: float | None = PydanticField(None, alias='RejectedQuantity')
    posting_date: str | None = PydanticField(None, alias='PostingDate')
    due_date: str | None = PydanticField(None, alias='DueDate')
    production_order_origin_entry: int | None = PydanticField(None, alias='ProductionOrderOriginEntry')
    production_order_origin_number: int | None = PydanticField(None, alias='ProductionOrderOriginNumber')
    production_order_origin: BoProductionOrderOriginEnum | None = PydanticField(None, alias='ProductionOrderOrigin')
    user_signature: int | None = PydanticField(None, alias='UserSignature')
    remarks: str | None = PydanticField(None, alias='Remarks')
    closing_date: str | None = PydanticField(None, alias='ClosingDate')
    release_date: str | None = PydanticField(None, alias='ReleaseDate')
    customer_code: str | None = PydanticField(None, alias='CustomerCode')
    warehouse: str | None = PydanticField(None, alias='Warehouse')
    inventory_uom: str | None = PydanticField(None, alias='InventoryUOM')
    journal_remarks: str | None = PydanticField(None, alias='JournalRemarks')
    transaction_number: int | None = PydanticField(None, alias='TransactionNumber')
    creation_date: str | None = PydanticField(None, alias='CreationDate')
    printed: SapBool | None = PydanticField(None, alias='Printed')
    distribution_rule: str | None = PydanticField(None, alias='DistributionRule')
    project: str | None = PydanticField(None, alias='Project')
    distribution_rule2: str | None = PydanticField(None, alias='DistributionRule2')
    distribution_rule3: str | None = PydanticField(None, alias='DistributionRule3')
    distribution_rule4: str | None = PydanticField(None, alias='DistributionRule4')
    distribution_rule5: str | None = PydanticField(None, alias='DistributionRule5')
    uo_m_entry: int | None = PydanticField(None, alias='UoMEntry')
    start_date: str | None = PydanticField(None, alias='StartDate')
    product_description: str | None = PydanticField(None, alias='ProductDescription')
    priority: int | None = PydanticField(None, alias='Priority')
    routing_date_calculation: ResourceAllocationEnum | None = PydanticField(None, alias='RoutingDateCalculation')
    update_allocation: BoUpdateAllocationEnum | None = PydanticField(None, alias='UpdateAllocation')
    sap_passport: str | None = PydanticField(None, alias='SAPPassport')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    pick_remarks: str | None = PydanticField(None, alias='PickRemarks')
    production_order_lines: list[ProductionOrderLine] | None = PydanticField(None, alias='ProductionOrderLines')
    production_orders_sales_order_lines: list[ProductionOrdersSalesOrderLine] | None = PydanticField(None, alias='ProductionOrdersSalesOrderLines')
    production_orders_stages: list[ProductionOrdersStage] | None = PydanticField(None, alias='ProductionOrdersStages')
    production_orders_document_references: list[ProductionOrdersDocumentReference] | None = PydanticField(None, alias='ProductionOrdersDocumentReferences')
    product_tree: ProductTree | None = PydanticField(None, alias='ProductTree')
    user: User | None = PydanticField(None, alias='User')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')
    warehouse2: Warehouse | None = PydanticField(None, alias='Warehouse2')
    journal_entry: JournalEntry | None = PydanticField(None, alias='JournalEntry')
    distribution_rule6: DistributionRule | None = PydanticField(None, alias='DistributionRule6')
    project2: Project | None = PydanticField(None, alias='Project2')
    unit_of_measurement: UnitOfMeasurement | None = PydanticField(None, alias='UnitOfMeasurement')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')

class ResourceCapacity(B1Model):
    """SAP ResourceCapacity Entity"""
    id: int | None = PydanticField(None, alias='Id')
    code: str | None = PydanticField(None, alias='Code')
    warehouse: str | None = PydanticField(None, alias='Warehouse')
    date: str | None = PydanticField(None, alias='Date')
    type: ResourceCapacityTypeEnum | None = PydanticField(None, alias='Type')
    capacity: float | None = PydanticField(None, alias='Capacity')
    source_type: ResourceCapacitySourceTypeEnum | None = PydanticField(None, alias='SourceType')
    source_entry: int | None = PydanticField(None, alias='SourceEntry')
    source_line_num: int | None = PydanticField(None, alias='SourceLineNum')
    base_type: ResourceCapacityBaseTypeEnum | None = PydanticField(None, alias='BaseType')
    base_entry: int | None = PydanticField(None, alias='BaseEntry')
    base_line_num: int | None = PydanticField(None, alias='BaseLineNum')
    action: ResourceCapacityActionEnum | None = PydanticField(None, alias='Action')
    owning_type: ResourceCapacityOwningTypeEnum | None = PydanticField(None, alias='OwningType')
    owning_entry: int | None = PydanticField(None, alias='OwningEntry')
    owning_line_num: int | None = PydanticField(None, alias='OwningLineNum')
    reverted_type: ResourceCapacityRevertedTypeEnum | None = PydanticField(None, alias='RevertedType')
    reverted_entry: int | None = PydanticField(None, alias='RevertedEntry')
    reverted_line_num: int | None = PydanticField(None, alias='RevertedLineNum')
    memo_source: ResourceCapacityMemoSourceEnum | None = PydanticField(None, alias='MemoSource')
    memo: str | None = PydanticField(None, alias='Memo')
    single_run_capacity: float | None = PydanticField(None, alias='SingleRunCapacity')
    single_run_memo_source: ResourceCapacityMemoSourceEnum | None = PydanticField(None, alias='SingleRunMemoSource')
    single_run_memo: str | None = PydanticField(None, alias='SingleRunMemo')
    resource: Resource | None = PydanticField(None, alias='Resource')
    warehouse2: Warehouse | None = PydanticField(None, alias='Warehouse2')

class ResourceProperty(B1Model):
    """SAP ResourceProperty Entity"""
    code: int | None = PydanticField(None, alias='Code')
    name: str | None = PydanticField(None, alias='Name')

class Resource(B1Model):
    """SAP Resource Entity"""
    code: str | None = PydanticField(None, alias='Code')
    vis_code: str | None = PydanticField(None, alias='VisCode')
    series: int | None = PydanticField(None, alias='Series')
    number: int | None = PydanticField(None, alias='Number')
    code_bar: str | None = PydanticField(None, alias='CodeBar')
    name: str | None = PydanticField(None, alias='Name')
    foreign_name: str | None = PydanticField(None, alias='ForeignName')
    type: ResourceTypeEnum | None = PydanticField(None, alias='Type')
    group: int | None = PydanticField(None, alias='Group')
    unit_of_measure: str | None = PydanticField(None, alias='UnitOfMeasure')
    issue_method: ResourceIssueMethodEnum | None = PydanticField(None, alias='IssueMethod')
    cost1: float | None = PydanticField(None, alias='Cost1')
    cost2: float | None = PydanticField(None, alias='Cost2')
    cost3: float | None = PydanticField(None, alias='Cost3')
    cost4: float | None = PydanticField(None, alias='Cost4')
    cost5: float | None = PydanticField(None, alias='Cost5')
    cost6: float | None = PydanticField(None, alias='Cost6')
    cost7: float | None = PydanticField(None, alias='Cost7')
    cost8: float | None = PydanticField(None, alias='Cost8')
    cost9: float | None = PydanticField(None, alias='Cost9')
    cost10: float | None = PydanticField(None, alias='Cost10')
    active: SapBool | None = PydanticField(None, alias='Active')
    active_from: str | None = PydanticField(None, alias='ActiveFrom')
    active_to: str | None = PydanticField(None, alias='ActiveTo')
    inactive: SapBool | None = PydanticField(None, alias='Inactive')
    inactive_from: str | None = PydanticField(None, alias='InactiveFrom')
    inactive_to: str | None = PydanticField(None, alias='InactiveTo')
    default_warehouse: str | None = PydanticField(None, alias='DefaultWarehouse')
    picture: str | None = PydanticField(None, alias='Picture')
    remarks: str | None = PydanticField(None, alias='Remarks')
    property1: SapBool | None = PydanticField(None, alias='Property1')
    property2: SapBool | None = PydanticField(None, alias='Property2')
    property3: SapBool | None = PydanticField(None, alias='Property3')
    property4: SapBool | None = PydanticField(None, alias='Property4')
    property5: SapBool | None = PydanticField(None, alias='Property5')
    property6: SapBool | None = PydanticField(None, alias='Property6')
    property7: SapBool | None = PydanticField(None, alias='Property7')
    property8: SapBool | None = PydanticField(None, alias='Property8')
    property9: SapBool | None = PydanticField(None, alias='Property9')
    property10: SapBool | None = PydanticField(None, alias='Property10')
    property11: SapBool | None = PydanticField(None, alias='Property11')
    property12: SapBool | None = PydanticField(None, alias='Property12')
    property13: SapBool | None = PydanticField(None, alias='Property13')
    property14: SapBool | None = PydanticField(None, alias='Property14')
    property15: SapBool | None = PydanticField(None, alias='Property15')
    property16: SapBool | None = PydanticField(None, alias='Property16')
    property17: SapBool | None = PydanticField(None, alias='Property17')
    property18: SapBool | None = PydanticField(None, alias='Property18')
    property19: SapBool | None = PydanticField(None, alias='Property19')
    property20: SapBool | None = PydanticField(None, alias='Property20')
    property21: SapBool | None = PydanticField(None, alias='Property21')
    property22: SapBool | None = PydanticField(None, alias='Property22')
    property23: SapBool | None = PydanticField(None, alias='Property23')
    property24: SapBool | None = PydanticField(None, alias='Property24')
    property25: SapBool | None = PydanticField(None, alias='Property25')
    property26: SapBool | None = PydanticField(None, alias='Property26')
    property27: SapBool | None = PydanticField(None, alias='Property27')
    property28: SapBool | None = PydanticField(None, alias='Property28')
    property29: SapBool | None = PydanticField(None, alias='Property29')
    property30: SapBool | None = PydanticField(None, alias='Property30')
    property31: SapBool | None = PydanticField(None, alias='Property31')
    property32: SapBool | None = PydanticField(None, alias='Property32')
    property33: SapBool | None = PydanticField(None, alias='Property33')
    property34: SapBool | None = PydanticField(None, alias='Property34')
    property35: SapBool | None = PydanticField(None, alias='Property35')
    property36: SapBool | None = PydanticField(None, alias='Property36')
    property37: SapBool | None = PydanticField(None, alias='Property37')
    property38: SapBool | None = PydanticField(None, alias='Property38')
    property39: SapBool | None = PydanticField(None, alias='Property39')
    property40: SapBool | None = PydanticField(None, alias='Property40')
    property41: SapBool | None = PydanticField(None, alias='Property41')
    property42: SapBool | None = PydanticField(None, alias='Property42')
    property43: SapBool | None = PydanticField(None, alias='Property43')
    property44: SapBool | None = PydanticField(None, alias='Property44')
    property45: SapBool | None = PydanticField(None, alias='Property45')
    property46: SapBool | None = PydanticField(None, alias='Property46')
    property47: SapBool | None = PydanticField(None, alias='Property47')
    property48: SapBool | None = PydanticField(None, alias='Property48')
    property49: SapBool | None = PydanticField(None, alias='Property49')
    property50: SapBool | None = PydanticField(None, alias='Property50')
    property51: SapBool | None = PydanticField(None, alias='Property51')
    property52: SapBool | None = PydanticField(None, alias='Property52')
    property53: SapBool | None = PydanticField(None, alias='Property53')
    property54: SapBool | None = PydanticField(None, alias='Property54')
    property55: SapBool | None = PydanticField(None, alias='Property55')
    property56: SapBool | None = PydanticField(None, alias='Property56')
    property57: SapBool | None = PydanticField(None, alias='Property57')
    property58: SapBool | None = PydanticField(None, alias='Property58')
    property59: SapBool | None = PydanticField(None, alias='Property59')
    property60: SapBool | None = PydanticField(None, alias='Property60')
    property61: SapBool | None = PydanticField(None, alias='Property61')
    property62: SapBool | None = PydanticField(None, alias='Property62')
    property63: SapBool | None = PydanticField(None, alias='Property63')
    property64: SapBool | None = PydanticField(None, alias='Property64')
    active_remarks: str | None = PydanticField(None, alias='ActiveRemarks')
    inactive_remarks: str | None = PydanticField(None, alias='InactiveRemarks')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    units_per_time: int | None = PydanticField(None, alias='UnitsPerTime')
    time_per_units: int | None = PydanticField(None, alias='TimePerUnits')
    allocation: ResourceAllocationEnum | None = PydanticField(None, alias='Allocation')
    linked_item: str | None = PydanticField(None, alias='LinkedItem')
    relevant_for_single_run1: SapBool | None = PydanticField(None, alias='RelevantForSingleRun1')
    relevant_for_single_run2: SapBool | None = PydanticField(None, alias='RelevantForSingleRun2')
    relevant_for_single_run3: SapBool | None = PydanticField(None, alias='RelevantForSingleRun3')
    relevant_for_single_run4: SapBool | None = PydanticField(None, alias='RelevantForSingleRun4')
    resource_warehouses: list[ResourceWarehouse] | None = PydanticField(None, alias='ResourceWarehouses')
    resource_fixed_assets: list[ResourceFixedAsset] | None = PydanticField(None, alias='ResourceFixedAssets')
    resource_employees: list[ResourceEmployee] | None = PydanticField(None, alias='ResourceEmployees')
    resource_daily_capacities: list[ResourceDailyCapacity] | None = PydanticField(None, alias='ResourceDailyCapacities')
    items: list[Item] | None = PydanticField(None, alias='Items')
    resource_capacities: list[ResourceCapacity] | None = PydanticField(None, alias='ResourceCapacities')
    resource_group: ResourceGroup | None = PydanticField(None, alias='ResourceGroup')
    item: Item | None = PydanticField(None, alias='Item')

class ResourceGroup(B1Model):
    """SAP ResourceGroup Entity"""
    code: int | None = PydanticField(None, alias='Code')
    name: str | None = PydanticField(None, alias='Name')
    type: ResourceTypeEnum | None = PydanticField(None, alias='Type')
    cost_name1: str | None = PydanticField(None, alias='CostName1')
    cost1: float | None = PydanticField(None, alias='Cost1')
    cost_name2: str | None = PydanticField(None, alias='CostName2')
    cost2: float | None = PydanticField(None, alias='Cost2')
    cost_name3: str | None = PydanticField(None, alias='CostName3')
    cost3: float | None = PydanticField(None, alias='Cost3')
    cost_name4: str | None = PydanticField(None, alias='CostName4')
    cost4: float | None = PydanticField(None, alias='Cost4')
    cost_name5: str | None = PydanticField(None, alias='CostName5')
    cost5: float | None = PydanticField(None, alias='Cost5')
    cost_name6: str | None = PydanticField(None, alias='CostName6')
    cost6: float | None = PydanticField(None, alias='Cost6')
    cost_name7: str | None = PydanticField(None, alias='CostName7')
    cost7: float | None = PydanticField(None, alias='Cost7')
    cost_name8: str | None = PydanticField(None, alias='CostName8')
    cost8: float | None = PydanticField(None, alias='Cost8')
    cost_name9: str | None = PydanticField(None, alias='CostName9')
    cost9: float | None = PydanticField(None, alias='Cost9')
    cost_name10: str | None = PydanticField(None, alias='CostName10')
    cost10: float | None = PydanticField(None, alias='Cost10')
    num_of_units_text: str | None = PydanticField(None, alias='NumOfUnitsText')
    resources: list[Resource] | None = PydanticField(None, alias='Resources')
