from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import Field as PydanticField

from b1sl.b1sl.models.base import B1Model, SapBool

from ..complex_types import *
from ..enums import *

if TYPE_CHECKING:
    from .._types import *
    from .businesspartners import *
    from .finance import *
    from .general import *
    from .inventory import *

class ServiceCallProblemSubType(B1Model):
    """SAP ServiceCallProblemSubType Entity"""
    problem_sub_type_id: int | None = PydanticField(None, alias='ProblemSubTypeID')
    name: str | None = PydanticField(None, alias='Name')
    description: str | None = PydanticField(None, alias='Description')
    active: SapBool | None = PydanticField(None, alias='Active')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')

class ContractTemplate(B1Model):
    """SAP ContractTemplate Entity"""
    template_name: str | None = PydanticField(None, alias='TemplateName')
    template_is_deleted: SapBool | None = PydanticField(None, alias='TemplateIsDeleted')
    template_is_renewal: SapBool | None = PydanticField(None, alias='TemplateIsRenewal')
    remind_before_renewal: int | None = PydanticField(None, alias='RemindBeforeRenewal')
    remind_unit: BoRemindUnits | None = PydanticField(None, alias='RemindUnit')
    duration_of_coverage: int | None = PydanticField(None, alias='DurationOfCoverage')
    response_value: int | None = PydanticField(None, alias='ResponseValue')
    resolution_unit: BoResolutionUnits | None = PydanticField(None, alias='ResolutionUnit')
    description: str | None = PydanticField(None, alias='Description')
    contract_type: BoContractTypes | None = PydanticField(None, alias='ContractType')
    monday_enabled: SapBool | None = PydanticField(None, alias='MondayEnabled')
    tuesday_enabled: SapBool | None = PydanticField(None, alias='TuesdayEnabled')
    wednesday_enabled: SapBool | None = PydanticField(None, alias='WednesdayEnabled')
    thursday_enabled: SapBool | None = PydanticField(None, alias='ThursdayEnabled')
    friday_enabled: SapBool | None = PydanticField(None, alias='FridayEnabled')
    saturday_enabled: SapBool | None = PydanticField(None, alias='SaturdayEnabled')
    sunday_enabled: SapBool | None = PydanticField(None, alias='SundayEnabled')
    monday_start: str | None = PydanticField(None, alias='MondayStart')
    monday_end: str | None = PydanticField(None, alias='MondayEnd')
    tuesday_start: str | None = PydanticField(None, alias='TuesdayStart')
    tuesday_end: str | None = PydanticField(None, alias='TuesdayEnd')
    wednesday_start: str | None = PydanticField(None, alias='WednesdayStart')
    wednesday_end: str | None = PydanticField(None, alias='WednesdayEnd')
    thursday_start: str | None = PydanticField(None, alias='ThursdayStart')
    thursday_end: str | None = PydanticField(None, alias='ThursdayEnd')
    friday_start: str | None = PydanticField(None, alias='FridayStart')
    friday_end: str | None = PydanticField(None, alias='FridayEnd')
    saturday_start: str | None = PydanticField(None, alias='SaturdayStart')
    saturday_end: str | None = PydanticField(None, alias='SaturdayEnd')
    sunday_start: str | None = PydanticField(None, alias='SundayStart')
    sunday_end: str | None = PydanticField(None, alias='SundayEnd')
    include_parts: SapBool | None = PydanticField(None, alias='IncludeParts')
    include_labor: SapBool | None = PydanticField(None, alias='IncludeLabor')
    include_travel: SapBool | None = PydanticField(None, alias='IncludeTravel')
    remarks: str | None = PydanticField(None, alias='Remarks')
    include_holidays: SapBool | None = PydanticField(None, alias='IncludeHolidays')
    response_unit: BoResponseUnit | None = PydanticField(None, alias='ResponseUnit')
    resolution_time: int | None = PydanticField(None, alias='ResolutionTime')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    items: list[Item] | None = PydanticField(None, alias='Items')
    service_contracts: list[ServiceContract] | None = PydanticField(None, alias='ServiceContracts')

class ServiceCallType(B1Model):
    """SAP ServiceCallType Entity"""
    call_type_id: int | None = PydanticField(None, alias='CallTypeID')
    name: str | None = PydanticField(None, alias='Name')
    description: str | None = PydanticField(None, alias='Description')
    active: SapBool | None = PydanticField(None, alias='Active')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')

class BlanketAgreement(B1Model):
    """SAP BlanketAgreement Entity"""
    agreement_no: int | None = PydanticField(None, alias='AgreementNo')
    bp_code: str | None = PydanticField(None, alias='BPCode')
    bp_name: str | None = PydanticField(None, alias='BPName')
    contact_person_code: int | None = PydanticField(None, alias='ContactPersonCode')
    start_date: str | None = PydanticField(None, alias='StartDate')
    end_date: str | None = PydanticField(None, alias='EndDate')
    terminate_date: str | None = PydanticField(None, alias='TerminateDate')
    description: str | None = PydanticField(None, alias='Description')
    agreement_type: BlanketAgreementTypeEnum | None = PydanticField(None, alias='AgreementType')
    status: BlanketAgreementStatusEnum | None = PydanticField(None, alias='Status')
    owner: int | None = PydanticField(None, alias='Owner')
    ignore_prices_in_agreement: SapBool | None = PydanticField(None, alias='IgnorePricesInAgreement')
    renewal: SapBool | None = PydanticField(None, alias='Renewal')
    remind_unit: BoRemindUnits | None = PydanticField(None, alias='RemindUnit')
    remind_time: int | None = PydanticField(None, alias='RemindTime')
    remarks: str | None = PydanticField(None, alias='Remarks')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    settlement_probability: float | None = PydanticField(None, alias='SettlementProbability')
    agreement_method: BlanketAgreementMethodEnum | None = PydanticField(None, alias='AgreementMethod')
    payment_terms: int | None = PydanticField(None, alias='PaymentTerms')
    price_list: int | None = PydanticField(None, alias='PriceList')
    signing_date: str | None = PydanticField(None, alias='SigningDate')
    amendment_to: int | None = PydanticField(None, alias='AmendmentTo')
    series: int | None = PydanticField(None, alias='Series')
    doc_num: int | None = PydanticField(None, alias='DocNum')
    hand_written: SapBool | None = PydanticField(None, alias='HandWritten')
    period_indicator: str | None = PydanticField(None, alias='PeriodIndicator')
    payment_method: str | None = PydanticField(None, alias='PaymentMethod')
    exchange_rate: float | None = PydanticField(None, alias='ExchangeRate')
    shipping_type: int | None = PydanticField(None, alias='ShippingType')
    num_at_card: str | None = PydanticField(None, alias='NumAtCard')
    project: str | None = PydanticField(None, alias='Project')
    price_mode: PriceModeEnum | None = PydanticField(None, alias='PriceMode')
    bp_currency: str | None = PydanticField(None, alias='BPCurrency')
    bp_type: BlanketAgreementBPTypeEnum | None = PydanticField(None, alias='BPType')
    sap_passport: str | None = PydanticField(None, alias='SAPPassport')
    blanket_agreements_items_lines: list[BlanketAgreements_ItemsLine] | None = PydanticField(None, alias='BlanketAgreements_ItemsLines')
    vendor_payments: list[Payment] | None = PydanticField(None, alias='VendorPayments')
    journal_entries: list[JournalEntry] | None = PydanticField(None, alias='JournalEntries')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')
    employee_info: EmployeeInfo | None = PydanticField(None, alias='EmployeeInfo')
    attachments2: Attachments2 | None = PydanticField(None, alias='Attachments2')
    payment_terms_type: PaymentTermsType | None = PydanticField(None, alias='PaymentTermsType')
    price_list2: PriceList | None = PydanticField(None, alias='PriceList2')
    wizard_payment_method: WizardPaymentMethod | None = PydanticField(None, alias='WizardPaymentMethod')
    shipping_type2: ShippingType | None = PydanticField(None, alias='ShippingType2')
    project2: Project | None = PydanticField(None, alias='Project2')
    currency: Currency | None = PydanticField(None, alias='Currency')
    payment_drafts: list[Payment] | None = PydanticField(None, alias='PaymentDrafts')
    business_partners: list[BusinessPartner] | None = PydanticField(None, alias='BusinessPartners')
    incoming_payments: list[Payment] | None = PydanticField(None, alias='IncomingPayments')

class ServiceCallProblemType(B1Model):
    """SAP ServiceCallProblemType Entity"""
    problem_type_id: int | None = PydanticField(None, alias='ProblemTypeID')
    name: str | None = PydanticField(None, alias='Name')
    description: str | None = PydanticField(None, alias='Description')
    active: SapBool | None = PydanticField(None, alias='Active')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')

class ServiceCallSolutionStatus(B1Model):
    """SAP ServiceCallSolutionStatus Entity"""
    status_id: int | None = PydanticField(None, alias='StatusId')
    name: str | None = PydanticField(None, alias='Name')
    description: str | None = PydanticField(None, alias='Description')
    active: SapBool | None = PydanticField(None, alias='Active')
    knowledge_base_solutions: list[KnowledgeBaseSolution] | None = PydanticField(None, alias='KnowledgeBaseSolutions')

class ServiceCallStatus(B1Model):
    """SAP ServiceCallStatus Entity"""
    status_id: int | None = PydanticField(None, alias='StatusId')
    name: str | None = PydanticField(None, alias='Name')
    description: str | None = PydanticField(None, alias='Description')
    active: SapBool | None = PydanticField(None, alias='Active')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')

class ServiceCallOrigin(B1Model):
    """SAP ServiceCallOrigin Entity"""
    origin_id: int | None = PydanticField(None, alias='OriginID')
    name: str | None = PydanticField(None, alias='Name')
    description: str | None = PydanticField(None, alias='Description')
    active: SapBool | None = PydanticField(None, alias='Active')
    service_calls: list[ServiceCall] | None = PydanticField(None, alias='ServiceCalls')

class ServiceCall(B1Model):
    """SAP ServiceCall Entity"""
    service_call_id: int | None = PydanticField(None, alias='ServiceCallID')
    subject: str | None = PydanticField(None, alias='Subject')
    customer_code: str | None = PydanticField(None, alias='CustomerCode')
    customer_name: str | None = PydanticField(None, alias='CustomerName')
    contact_code: int | None = PydanticField(None, alias='ContactCode')
    manufacturer_serial_num: str | None = PydanticField(None, alias='ManufacturerSerialNum')
    internal_serial_num: str | None = PydanticField(None, alias='InternalSerialNum')
    contract_id: int | None = PydanticField(None, alias='ContractID')
    contract_end_date: str | None = PydanticField(None, alias='ContractEndDate')
    resolution_date: str | None = PydanticField(None, alias='ResolutionDate')
    resolution_time: str | None = PydanticField(None, alias='ResolutionTime')
    origin: int | None = PydanticField(None, alias='Origin')
    item_code: str | None = PydanticField(None, alias='ItemCode')
    item_description: str | None = PydanticField(None, alias='ItemDescription')
    item_group_code: int | None = PydanticField(None, alias='ItemGroupCode')
    status: int | None = PydanticField(None, alias='Status')
    priority: BoSvcCallPriorities | None = PydanticField(None, alias='Priority')
    call_type: int | None = PydanticField(None, alias='CallType')
    problem_type: int | None = PydanticField(None, alias='ProblemType')
    assignee_code: int | None = PydanticField(None, alias='AssigneeCode')
    description: str | None = PydanticField(None, alias='Description')
    technician_code: int | None = PydanticField(None, alias='TechnicianCode')
    resolution: str | None = PydanticField(None, alias='Resolution')
    creation_date: str | None = PydanticField(None, alias='CreationDate')
    creation_time: str | None = PydanticField(None, alias='CreationTime')
    responder: int | None = PydanticField(None, alias='Responder')
    updated_time: str | None = PydanticField(None, alias='UpdatedTime')
    belongs_to_a_queue: SapBool | None = PydanticField(None, alias='BelongsToAQueue')
    response_by_time: str | None = PydanticField(None, alias='ResponseByTime')
    response_by_date: str | None = PydanticField(None, alias='ResponseByDate')
    resolution_on_date: str | None = PydanticField(None, alias='ResolutionOnDate')
    response_on_time: str | None = PydanticField(None, alias='ResponseOnTime')
    response_on_date: str | None = PydanticField(None, alias='ResponseOnDate')
    closing_time: str | None = PydanticField(None, alias='ClosingTime')
    assigned_date: str | None = PydanticField(None, alias='AssignedDate')
    queue: str | None = PydanticField(None, alias='Queue')
    response_assignee: int | None = PydanticField(None, alias='ResponseAssignee')
    entitledfor_service: SapBool | None = PydanticField(None, alias='EntitledforService')
    resolution_on_time: str | None = PydanticField(None, alias='ResolutionOnTime')
    assigned_time: str | None = PydanticField(None, alias='AssignedTime')
    closing_date: str | None = PydanticField(None, alias='ClosingDate')
    series: int | None = PydanticField(None, alias='Series')
    doc_num: int | None = PydanticField(None, alias='DocNum')
    hand_written: SapBool | None = PydanticField(None, alias='HandWritten')
    period_indicator: str | None = PydanticField(None, alias='PeriodIndicator')
    start_date: str | None = PydanticField(None, alias='StartDate')
    start_time: str | None = PydanticField(None, alias='StartTime')
    end_due_date: str | None = PydanticField(None, alias='EndDueDate')
    end_time: str | None = PydanticField(None, alias='EndTime')
    duration: float | None = PydanticField(None, alias='Duration')
    duration_type: BoDurations | None = PydanticField(None, alias='DurationType')
    reminder: SapBool | None = PydanticField(None, alias='Reminder')
    reminder_period: float | None = PydanticField(None, alias='ReminderPeriod')
    reminder_type: BoDurations | None = PydanticField(None, alias='ReminderType')
    location: int | None = PydanticField(None, alias='Location')
    address_name: str | None = PydanticField(None, alias='AddressName')
    address_type: BoAddressType | None = PydanticField(None, alias='AddressType')
    street: str | None = PydanticField(None, alias='Street')
    city: str | None = PydanticField(None, alias='City')
    room: str | None = PydanticField(None, alias='Room')
    state: str | None = PydanticField(None, alias='State')
    country: str | None = PydanticField(None, alias='Country')
    display_in_calendar: SapBool | None = PydanticField(None, alias='DisplayInCalendar')
    customer_ref_no: str | None = PydanticField(None, alias='CustomerRefNo')
    problem_sub_type: int | None = PydanticField(None, alias='ProblemSubType')
    attachment_entry: int | None = PydanticField(None, alias='AttachmentEntry')
    service_bp_type: ServiceTypeEnum | None = PydanticField(None, alias='ServiceBPType')
    bp_contact_person: str | None = PydanticField(None, alias='BPContactPerson')
    bp_phone1: str | None = PydanticField(None, alias='BPPhone1')
    bp_phone2: str | None = PydanticField(None, alias='BPPhone2')
    bp_cellular: str | None = PydanticField(None, alias='BPCellular')
    bp_fax: str | None = PydanticField(None, alias='BPFax')
    b_pe_mail: str | None = PydanticField(None, alias='BPeMail')
    bp_project_code: str | None = PydanticField(None, alias='BPProjectCode')
    bp_territory: int | None = PydanticField(None, alias='BPTerritory')
    bp_ship_to_code: str | None = PydanticField(None, alias='BPShipToCode')
    bp_ship_to_address: str | None = PydanticField(None, alias='BPShipToAddress')
    bp_bill_to_code: str | None = PydanticField(None, alias='BPBillToCode')
    bp_bill_to_address: str | None = PydanticField(None, alias='BPBillToAddress')
    telephone: str | None = PydanticField(None, alias='Telephone')
    update_date: str | None = PydanticField(None, alias='UpdateDate')
    supplementary_code: str | None = PydanticField(None, alias='SupplementaryCode')
    service_call_activities: list[ServiceCallActivity] | None = PydanticField(None, alias='ServiceCallActivities')
    service_call_inventory_expenses: list[ServiceCallInventoryExpense] | None = PydanticField(None, alias='ServiceCallInventoryExpenses')
    service_call_solutions: list[ServiceCallSolution] | None = PydanticField(None, alias='ServiceCallSolutions')
    service_call_schedulings: list[ServiceCallScheduling] | None = PydanticField(None, alias='ServiceCallSchedulings')
    service_call_bp_address_components: list[ServiceCallBPAddressComponent] | None = PydanticField(None, alias='ServiceCallBPAddressComponents')
    business_partner: BusinessPartner | None = PydanticField(None, alias='BusinessPartner')
    service_contract: ServiceContract | None = PydanticField(None, alias='ServiceContract')
    service_call_origin: ServiceCallOrigin | None = PydanticField(None, alias='ServiceCallOrigin')
    item: Item | None = PydanticField(None, alias='Item')
    item_groups: ItemGroups | None = PydanticField(None, alias='ItemGroups')
    service_call_status: ServiceCallStatus | None = PydanticField(None, alias='ServiceCallStatus')
    service_call_type: ServiceCallType | None = PydanticField(None, alias='ServiceCallType')
    service_call_problem_type: ServiceCallProblemType | None = PydanticField(None, alias='ServiceCallProblemType')
    user: User | None = PydanticField(None, alias='User')
    employee_info: EmployeeInfo | None = PydanticField(None, alias='EmployeeInfo')
    queue2: Queue | None = PydanticField(None, alias='Queue2')
    activity_location: ActivityLocation | None = PydanticField(None, alias='ActivityLocation')
    country2: Country | None = PydanticField(None, alias='Country2')
    service_call_problem_sub_type: ServiceCallProblemSubType | None = PydanticField(None, alias='ServiceCallProblemSubType')
    project: Project | None = PydanticField(None, alias='Project')
